// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: absence_markers.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const absenceMarkersClear = `-- name: AbsenceMarkersClear :one
UPDATE absence_markers
SET cleared_at = $4,
    cleared_by_user_id = $5,
    cleared_by_membership_id = $6,
    updated_at = now()
WHERE tenant_id = $1
  AND branch_id = $2
  AND id = $3
  AND cleared_at IS NULL
RETURNING id, tenant_id, branch_id, child_id, local_date, marked_at, marked_by_user_id, marked_by_membership_id, cleared_at, cleared_by_user_id, cleared_by_membership_id, created_at, updated_at
`

type AbsenceMarkersClearParams struct {
	TenantID              pgtype.UUID
	BranchID              pgtype.UUID
	ID                    pgtype.UUID
	ClearedAt             pgtype.Timestamptz
	ClearedByUserID       pgtype.UUID
	ClearedByMembershipID pgtype.UUID
}

func (q *Queries) AbsenceMarkersClear(ctx context.Context, arg AbsenceMarkersClearParams) (AbsenceMarker, error) {
	row := q.db.QueryRow(ctx, absenceMarkersClear,
		arg.TenantID,
		arg.BranchID,
		arg.ID,
		arg.ClearedAt,
		arg.ClearedByUserID,
		arg.ClearedByMembershipID,
	)
	var i AbsenceMarker
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BranchID,
		&i.ChildID,
		&i.LocalDate,
		&i.MarkedAt,
		&i.MarkedByUserID,
		&i.MarkedByMembershipID,
		&i.ClearedAt,
		&i.ClearedByUserID,
		&i.ClearedByMembershipID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const absenceMarkersCreate = `-- name: AbsenceMarkersCreate :one
INSERT INTO absence_markers (
    id, tenant_id, branch_id, child_id, local_date,
    marked_at, marked_by_user_id, marked_by_membership_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, branch_id, child_id, local_date, marked_at, marked_by_user_id, marked_by_membership_id, cleared_at, cleared_by_user_id, cleared_by_membership_id, created_at, updated_at
`

type AbsenceMarkersCreateParams struct {
	ID                   pgtype.UUID
	TenantID             pgtype.UUID
	BranchID             pgtype.UUID
	ChildID              pgtype.UUID
	LocalDate            pgtype.Date
	MarkedAt             pgtype.Timestamptz
	MarkedByUserID       pgtype.UUID
	MarkedByMembershipID pgtype.UUID
}

func (q *Queries) AbsenceMarkersCreate(ctx context.Context, arg AbsenceMarkersCreateParams) (AbsenceMarker, error) {
	row := q.db.QueryRow(ctx, absenceMarkersCreate,
		arg.ID,
		arg.TenantID,
		arg.BranchID,
		arg.ChildID,
		arg.LocalDate,
		arg.MarkedAt,
		arg.MarkedByUserID,
		arg.MarkedByMembershipID,
	)
	var i AbsenceMarker
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BranchID,
		&i.ChildID,
		&i.LocalDate,
		&i.MarkedAt,
		&i.MarkedByUserID,
		&i.MarkedByMembershipID,
		&i.ClearedAt,
		&i.ClearedByUserID,
		&i.ClearedByMembershipID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const absenceMarkersFindActiveByChildDate = `-- name: AbsenceMarkersFindActiveByChildDate :one
SELECT id, tenant_id, branch_id, child_id, local_date, marked_at, marked_by_user_id, marked_by_membership_id, cleared_at, cleared_by_user_id, cleared_by_membership_id, created_at, updated_at FROM absence_markers
WHERE tenant_id = $1
  AND branch_id = $2
  AND child_id = $3
  AND local_date = $4
  AND cleared_at IS NULL
`

type AbsenceMarkersFindActiveByChildDateParams struct {
	TenantID  pgtype.UUID
	BranchID  pgtype.UUID
	ChildID   pgtype.UUID
	LocalDate pgtype.Date
}

func (q *Queries) AbsenceMarkersFindActiveByChildDate(ctx context.Context, arg AbsenceMarkersFindActiveByChildDateParams) (AbsenceMarker, error) {
	row := q.db.QueryRow(ctx, absenceMarkersFindActiveByChildDate,
		arg.TenantID,
		arg.BranchID,
		arg.ChildID,
		arg.LocalDate,
	)
	var i AbsenceMarker
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BranchID,
		&i.ChildID,
		&i.LocalDate,
		&i.MarkedAt,
		&i.MarkedByUserID,
		&i.MarkedByMembershipID,
		&i.ClearedAt,
		&i.ClearedByUserID,
		&i.ClearedByMembershipID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const absenceMarkersGetByID = `-- name: AbsenceMarkersGetByID :one
SELECT id, tenant_id, branch_id, child_id, local_date, marked_at, marked_by_user_id, marked_by_membership_id, cleared_at, cleared_by_user_id, cleared_by_membership_id, created_at, updated_at FROM absence_markers
WHERE tenant_id = $1
  AND branch_id = $2
  AND id = $3
`

type AbsenceMarkersGetByIDParams struct {
	TenantID pgtype.UUID
	BranchID pgtype.UUID
	ID       pgtype.UUID
}

func (q *Queries) AbsenceMarkersGetByID(ctx context.Context, arg AbsenceMarkersGetByIDParams) (AbsenceMarker, error) {
	row := q.db.QueryRow(ctx, absenceMarkersGetByID, arg.TenantID, arg.BranchID, arg.ID)
	var i AbsenceMarker
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BranchID,
		&i.ChildID,
		&i.LocalDate,
		&i.MarkedAt,
		&i.MarkedByUserID,
		&i.MarkedByMembershipID,
		&i.ClearedAt,
		&i.ClearedByUserID,
		&i.ClearedByMembershipID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const absenceMarkersHasAttendanceForChildDate = `-- name: AbsenceMarkersHasAttendanceForChildDate :one
SELECT EXISTS (
    SELECT 1 FROM attendance_sessions
    WHERE tenant_id = $1
      AND branch_id = $2
      AND child_id = $3
      AND check_in_local_date = $4
)
`

type AbsenceMarkersHasAttendanceForChildDateParams struct {
	TenantID         pgtype.UUID
	BranchID         pgtype.UUID
	ChildID          pgtype.UUID
	CheckInLocalDate pgtype.Date
}

func (q *Queries) AbsenceMarkersHasAttendanceForChildDate(ctx context.Context, arg AbsenceMarkersHasAttendanceForChildDateParams) (bool, error) {
	row := q.db.QueryRow(ctx, absenceMarkersHasAttendanceForChildDate,
		arg.TenantID,
		arg.BranchID,
		arg.ChildID,
		arg.CheckInLocalDate,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
