// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: academic_terms.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const academicTermsArchive = `-- name: AcademicTermsArchive :exec
UPDATE academic_terms
SET is_active = false, updated_at = now()
WHERE tenant_id = $1 AND branch_id = $2 AND id = $3
`

type AcademicTermsArchiveParams struct {
	TenantID pgtype.UUID
	BranchID pgtype.UUID
	ID       pgtype.UUID
}

func (q *Queries) AcademicTermsArchive(ctx context.Context, arg AcademicTermsArchiveParams) error {
	_, err := q.db.Exec(ctx, academicTermsArchive, arg.TenantID, arg.BranchID, arg.ID)
	return err
}

const academicTermsCheckActiveNameExists = `-- name: AcademicTermsCheckActiveNameExists :one
SELECT EXISTS (
    SELECT 1 FROM academic_terms
    WHERE tenant_id = $1 AND branch_id = $2 AND name = $3 AND is_active = true
      AND ($4::uuid IS NULL OR id != $4)
)
`

type AcademicTermsCheckActiveNameExistsParams struct {
	TenantID pgtype.UUID
	BranchID pgtype.UUID
	Name     string
	Column4  pgtype.UUID
}

func (q *Queries) AcademicTermsCheckActiveNameExists(ctx context.Context, arg AcademicTermsCheckActiveNameExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, academicTermsCheckActiveNameExists,
		arg.TenantID,
		arg.BranchID,
		arg.Name,
		arg.Column4,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const academicTermsCountByBranch = `-- name: AcademicTermsCountByBranch :one
SELECT COUNT(*)
FROM academic_terms
WHERE tenant_id = $1
  AND branch_id = $2
  AND (NOT $3::bool OR is_active = true)
`

type AcademicTermsCountByBranchParams struct {
	TenantID pgtype.UUID
	BranchID pgtype.UUID
	Column3  bool
}

func (q *Queries) AcademicTermsCountByBranch(ctx context.Context, arg AcademicTermsCountByBranchParams) (int64, error) {
	row := q.db.QueryRow(ctx, academicTermsCountByBranch, arg.TenantID, arg.BranchID, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const academicTermsCreate = `-- name: AcademicTermsCreate :exec
INSERT INTO academic_terms (id, tenant_id, branch_id, name, kind, start_date, end_date, is_active)
VALUES ($1, $2, $3, $4, $5, $6, $7, true)
`

type AcademicTermsCreateParams struct {
	ID        pgtype.UUID
	TenantID  pgtype.UUID
	BranchID  pgtype.UUID
	Name      string
	Kind      string
	StartDate pgtype.Date
	EndDate   pgtype.Date
}

func (q *Queries) AcademicTermsCreate(ctx context.Context, arg AcademicTermsCreateParams) error {
	_, err := q.db.Exec(ctx, academicTermsCreate,
		arg.ID,
		arg.TenantID,
		arg.BranchID,
		arg.Name,
		arg.Kind,
		arg.StartDate,
		arg.EndDate,
	)
	return err
}

const academicTermsGetByID = `-- name: AcademicTermsGetByID :one
SELECT id, tenant_id, branch_id, name, kind, start_date, end_date, is_active, created_at, updated_at
FROM academic_terms
WHERE tenant_id = $1
  AND branch_id = $2
  AND id = $3
`

type AcademicTermsGetByIDParams struct {
	TenantID pgtype.UUID
	BranchID pgtype.UUID
	ID       pgtype.UUID
}

func (q *Queries) AcademicTermsGetByID(ctx context.Context, arg AcademicTermsGetByIDParams) (AcademicTerm, error) {
	row := q.db.QueryRow(ctx, academicTermsGetByID, arg.TenantID, arg.BranchID, arg.ID)
	var i AcademicTerm
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BranchID,
		&i.Name,
		&i.Kind,
		&i.StartDate,
		&i.EndDate,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const academicTermsGetByIDForUpdate = `-- name: AcademicTermsGetByIDForUpdate :one
SELECT id, tenant_id, branch_id, name, kind, start_date, end_date, is_active, created_at, updated_at
FROM academic_terms
WHERE tenant_id = $1
  AND branch_id = $2
  AND id = $3
FOR UPDATE
`

type AcademicTermsGetByIDForUpdateParams struct {
	TenantID pgtype.UUID
	BranchID pgtype.UUID
	ID       pgtype.UUID
}

func (q *Queries) AcademicTermsGetByIDForUpdate(ctx context.Context, arg AcademicTermsGetByIDForUpdateParams) (AcademicTerm, error) {
	row := q.db.QueryRow(ctx, academicTermsGetByIDForUpdate, arg.TenantID, arg.BranchID, arg.ID)
	var i AcademicTerm
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BranchID,
		&i.Name,
		&i.Kind,
		&i.StartDate,
		&i.EndDate,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const academicTermsListActiveDateRanges = `-- name: AcademicTermsListActiveDateRanges :many
SELECT start_date, end_date
FROM academic_terms
WHERE tenant_id = $1
  AND branch_id = $2
  AND is_active = true
  AND end_date >= $3
  AND start_date <= $4
ORDER BY start_date ASC
`

type AcademicTermsListActiveDateRangesParams struct {
	TenantID  pgtype.UUID
	BranchID  pgtype.UUID
	EndDate   pgtype.Date
	StartDate pgtype.Date
}

type AcademicTermsListActiveDateRangesRow struct {
	StartDate pgtype.Date
	EndDate   pgtype.Date
}

func (q *Queries) AcademicTermsListActiveDateRanges(ctx context.Context, arg AcademicTermsListActiveDateRangesParams) ([]AcademicTermsListActiveDateRangesRow, error) {
	rows, err := q.db.Query(ctx, academicTermsListActiveDateRanges,
		arg.TenantID,
		arg.BranchID,
		arg.EndDate,
		arg.StartDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AcademicTermsListActiveDateRangesRow
	for rows.Next() {
		var i AcademicTermsListActiveDateRangesRow
		if err := rows.Scan(&i.StartDate, &i.EndDate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const academicTermsListByBranch = `-- name: AcademicTermsListByBranch :many
SELECT id, tenant_id, branch_id, name, kind, start_date, end_date, is_active, created_at, updated_at
FROM academic_terms
WHERE tenant_id = $1
  AND branch_id = $2
  AND (NOT $3::bool OR is_active = true)
ORDER BY start_date DESC, name ASC
`

type AcademicTermsListByBranchParams struct {
	TenantID pgtype.UUID
	BranchID pgtype.UUID
	Column3  bool
}

func (q *Queries) AcademicTermsListByBranch(ctx context.Context, arg AcademicTermsListByBranchParams) ([]AcademicTerm, error) {
	rows, err := q.db.Query(ctx, academicTermsListByBranch, arg.TenantID, arg.BranchID, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AcademicTerm
	for rows.Next() {
		var i AcademicTerm
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.BranchID,
			&i.Name,
			&i.Kind,
			&i.StartDate,
			&i.EndDate,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const academicTermsListByBranchPaginated = `-- name: AcademicTermsListByBranchPaginated :many
SELECT id, tenant_id, branch_id, name, kind, start_date, end_date, is_active, created_at, updated_at
FROM academic_terms
WHERE tenant_id = $1
  AND branch_id = $2
  AND (NOT $3::bool OR is_active = true)
ORDER BY start_date DESC, name ASC
LIMIT $5 OFFSET $4
`

type AcademicTermsListByBranchPaginatedParams struct {
	TenantID pgtype.UUID
	BranchID pgtype.UUID
	Column3  bool
	Offset   pgtype.Int4
	Limit    pgtype.Int4
}

func (q *Queries) AcademicTermsListByBranchPaginated(ctx context.Context, arg AcademicTermsListByBranchPaginatedParams) ([]AcademicTerm, error) {
	rows, err := q.db.Query(ctx, academicTermsListByBranchPaginated,
		arg.TenantID,
		arg.BranchID,
		arg.Column3,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AcademicTerm
	for rows.Next() {
		var i AcademicTerm
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.BranchID,
			&i.Name,
			&i.Kind,
			&i.StartDate,
			&i.EndDate,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const academicTermsUpdate = `-- name: AcademicTermsUpdate :execrows
UPDATE academic_terms
SET
    name = CASE WHEN $1::bool THEN $2 ELSE name END,
    kind = CASE WHEN $3::bool THEN $4 ELSE kind END,
    start_date = CASE WHEN $5::bool THEN $6 ELSE start_date END,
    end_date = CASE WHEN $7::bool THEN $8 ELSE end_date END,
    updated_at = now()
WHERE tenant_id = $9 AND branch_id = $10 AND id = $11
`

type AcademicTermsUpdateParams struct {
	SetName      bool
	Name         string
	SetKind      bool
	Kind         string
	SetStartDate bool
	StartDate    pgtype.Date
	SetEndDate   bool
	EndDate      pgtype.Date
	TenantID     pgtype.UUID
	BranchID     pgtype.UUID
	ID           pgtype.UUID
}

func (q *Queries) AcademicTermsUpdate(ctx context.Context, arg AcademicTermsUpdateParams) (int64, error) {
	result, err := q.db.Exec(ctx, academicTermsUpdate,
		arg.SetName,
		arg.Name,
		arg.SetKind,
		arg.Kind,
		arg.SetStartDate,
		arg.StartDate,
		arg.SetEndDate,
		arg.EndDate,
		arg.TenantID,
		arg.BranchID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
