// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ad_hoc_bookings.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adHocBookingsCancel = `-- name: AdHocBookingsCancel :exec
UPDATE ad_hoc_bookings
SET status = 'cancelled', updated_at = now()
WHERE tenant_id = $1 AND branch_id = $2 AND id = $3 AND status = 'active'
`

type AdHocBookingsCancelParams struct {
	TenantID pgtype.UUID
	BranchID pgtype.UUID
	ID       pgtype.UUID
}

func (q *Queries) AdHocBookingsCancel(ctx context.Context, arg AdHocBookingsCancelParams) error {
	_, err := q.db.Exec(ctx, adHocBookingsCancel, arg.TenantID, arg.BranchID, arg.ID)
	return err
}

const adHocBookingsCreate = `-- name: AdHocBookingsCreate :exec
INSERT INTO ad_hoc_bookings (id, tenant_id, branch_id, child_id, calendar_date, session_type_id, booked_by_membership_id, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, 'active')
`

type AdHocBookingsCreateParams struct {
	ID                   pgtype.UUID
	TenantID             pgtype.UUID
	BranchID             pgtype.UUID
	ChildID              pgtype.UUID
	CalendarDate         pgtype.Date
	SessionTypeID        pgtype.UUID
	BookedByMembershipID pgtype.UUID
}

func (q *Queries) AdHocBookingsCreate(ctx context.Context, arg AdHocBookingsCreateParams) error {
	_, err := q.db.Exec(ctx, adHocBookingsCreate,
		arg.ID,
		arg.TenantID,
		arg.BranchID,
		arg.ChildID,
		arg.CalendarDate,
		arg.SessionTypeID,
		arg.BookedByMembershipID,
	)
	return err
}

const adHocBookingsGetByID = `-- name: AdHocBookingsGetByID :one
SELECT id, tenant_id, branch_id, child_id, calendar_date, session_type_id, booked_by_membership_id, status, created_at, updated_at
FROM ad_hoc_bookings
WHERE tenant_id = $1
  AND branch_id = $2
  AND id = $3
`

type AdHocBookingsGetByIDParams struct {
	TenantID pgtype.UUID
	BranchID pgtype.UUID
	ID       pgtype.UUID
}

func (q *Queries) AdHocBookingsGetByID(ctx context.Context, arg AdHocBookingsGetByIDParams) (AdHocBooking, error) {
	row := q.db.QueryRow(ctx, adHocBookingsGetByID, arg.TenantID, arg.BranchID, arg.ID)
	var i AdHocBooking
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BranchID,
		&i.ChildID,
		&i.CalendarDate,
		&i.SessionTypeID,
		&i.BookedByMembershipID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adHocBookingsGetByIDForUpdate = `-- name: AdHocBookingsGetByIDForUpdate :one
SELECT id, tenant_id, branch_id, child_id, calendar_date, session_type_id, booked_by_membership_id, status, created_at, updated_at
FROM ad_hoc_bookings
WHERE tenant_id = $1
  AND branch_id = $2
  AND id = $3
FOR UPDATE
`

type AdHocBookingsGetByIDForUpdateParams struct {
	TenantID pgtype.UUID
	BranchID pgtype.UUID
	ID       pgtype.UUID
}

func (q *Queries) AdHocBookingsGetByIDForUpdate(ctx context.Context, arg AdHocBookingsGetByIDForUpdateParams) (AdHocBooking, error) {
	row := q.db.QueryRow(ctx, adHocBookingsGetByIDForUpdate, arg.TenantID, arg.BranchID, arg.ID)
	var i AdHocBooking
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BranchID,
		&i.ChildID,
		&i.CalendarDate,
		&i.SessionTypeID,
		&i.BookedByMembershipID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adHocBookingsListByBranch = `-- name: AdHocBookingsListByBranch :many
SELECT id, tenant_id, branch_id, child_id, calendar_date, session_type_id, booked_by_membership_id, status, created_at, updated_at
FROM ad_hoc_bookings
WHERE tenant_id = $1
  AND branch_id = $2
  AND ($3::uuid IS NULL OR child_id = $3)
  AND ($4::date IS NULL OR calendar_date >= $4)
  AND ($5::date IS NULL OR calendar_date <= $5)
  AND (NOT $6::bool OR status = 'active')
ORDER BY calendar_date ASC, created_at ASC
`

type AdHocBookingsListByBranchParams struct {
	TenantID pgtype.UUID
	BranchID pgtype.UUID
	Column3  pgtype.UUID
	Column4  pgtype.Date
	Column5  pgtype.Date
	Column6  bool
}

func (q *Queries) AdHocBookingsListByBranch(ctx context.Context, arg AdHocBookingsListByBranchParams) ([]AdHocBooking, error) {
	rows, err := q.db.Query(ctx, adHocBookingsListByBranch,
		arg.TenantID,
		arg.BranchID,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdHocBooking
	for rows.Next() {
		var i AdHocBooking
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.BranchID,
			&i.ChildID,
			&i.CalendarDate,
			&i.SessionTypeID,
			&i.BookedByMembershipID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adHocBookingsListByChildAndDateRange = `-- name: AdHocBookingsListByChildAndDateRange :many
SELECT id, tenant_id, branch_id, child_id, calendar_date, session_type_id, booked_by_membership_id, status, created_at, updated_at
FROM ad_hoc_bookings
WHERE tenant_id = $1
  AND branch_id = $2
  AND child_id = $3
  AND calendar_date >= $4
  AND calendar_date <= $5
  AND status = 'active'
ORDER BY calendar_date ASC
`

type AdHocBookingsListByChildAndDateRangeParams struct {
	TenantID pgtype.UUID
	BranchID pgtype.UUID
	ChildID  pgtype.UUID
	FromDate pgtype.Date
	ToDate   pgtype.Date
}

func (q *Queries) AdHocBookingsListByChildAndDateRange(ctx context.Context, arg AdHocBookingsListByChildAndDateRangeParams) ([]AdHocBooking, error) {
	rows, err := q.db.Query(ctx, adHocBookingsListByChildAndDateRange,
		arg.TenantID,
		arg.BranchID,
		arg.ChildID,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdHocBooking
	for rows.Next() {
		var i AdHocBooking
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.BranchID,
			&i.ChildID,
			&i.CalendarDate,
			&i.SessionTypeID,
			&i.BookedByMembershipID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
