// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attendance_register.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const attendanceRegisterSummary = `-- name: AttendanceRegisterSummary :many
SELECT
    'recurring' AS booking_type,
    b.room_id,
    COALESCE(r.name, '') AS room_name,
    d.dt::date AS register_date,
    COUNT(*) AS booking_count
FROM bookings b
JOIN rooms r ON r.id = b.room_id AND r.tenant_id = b.tenant_id AND r.branch_id = b.branch_id
CROSS JOIN generate_series($3::date, $4::date, '1 day') AS d(dt)
WHERE b.tenant_id = $1
  AND b.branch_id = $2
  AND b.status = 'active'
  AND b.effective_start_date <= d.dt
  AND (b.effective_end_date IS NULL OR b.effective_end_date >= d.dt)
  AND EXTRACT(DOW FROM d.dt)::int = ANY(b.days_of_week)
GROUP BY b.room_id, r.name, d.dt::date

UNION ALL

SELECT
    'ad_hoc' AS booking_type,
    NULL::uuid AS room_id,
    '' AS room_name,
    ah.calendar_date AS register_date,
    COUNT(*) AS booking_count
FROM ad_hoc_bookings ah
WHERE ah.tenant_id = $1
  AND ah.branch_id = $2
  AND ah.calendar_date >= $3
  AND ah.calendar_date <= $4
  AND ah.status = 'active'
GROUP BY ah.calendar_date

UNION ALL

SELECT
    'hourly' AS booking_type,
    NULL::uuid AS room_id,
    '' AS room_name,
    h.calendar_date AS register_date,
    COUNT(*) AS booking_count
FROM hourly_bookings h
WHERE h.tenant_id = $1
  AND h.branch_id = $2
  AND h.calendar_date >= $3
  AND h.calendar_date <= $4
  AND h.status = 'active'
GROUP BY h.calendar_date

ORDER BY register_date, room_name
`

type AttendanceRegisterSummaryParams struct {
	TenantID pgtype.UUID
	BranchID pgtype.UUID
	FromDate pgtype.Date
	ToDate   pgtype.Date
}

type AttendanceRegisterSummaryRow struct {
	BookingType  string
	RoomID       pgtype.UUID
	RoomName     string
	RegisterDate pgtype.Date
	BookingCount int64
}

func (q *Queries) AttendanceRegisterSummary(ctx context.Context, arg AttendanceRegisterSummaryParams) ([]AttendanceRegisterSummaryRow, error) {
	rows, err := q.db.Query(ctx, attendanceRegisterSummary,
		arg.TenantID,
		arg.BranchID,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AttendanceRegisterSummaryRow
	for rows.Next() {
		var i AttendanceRegisterSummaryRow
		if err := rows.Scan(
			&i.BookingType,
			&i.RoomID,
			&i.RoomName,
			&i.RegisterDate,
			&i.BookingCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
