// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch.go

package sqlc

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const bookingSessionEntriesCreateBatch = `-- name: BookingSessionEntriesCreateBatch :batchexec
INSERT INTO booking_session_entries (id, tenant_id, branch_id, booking_id, day_of_week, session_type_id)
VALUES ($1, $2, $3, $4, $5, $6)
`

type BookingSessionEntriesCreateBatchBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type BookingSessionEntriesCreateBatchParams struct {
	ID            pgtype.UUID
	TenantID      pgtype.UUID
	BranchID      pgtype.UUID
	BookingID     pgtype.UUID
	DayOfWeek     int32
	SessionTypeID pgtype.UUID
}

func (q *Queries) BookingSessionEntriesCreateBatch(ctx context.Context, arg []BookingSessionEntriesCreateBatchParams) *BookingSessionEntriesCreateBatchBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ID,
			a.TenantID,
			a.BranchID,
			a.BookingID,
			a.DayOfWeek,
			a.SessionTypeID,
		}
		batch.Queue(bookingSessionEntriesCreateBatch, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &BookingSessionEntriesCreateBatchBatchResults{br, len(arg), false}
}

func (b *BookingSessionEntriesCreateBatchBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *BookingSessionEntriesCreateBatchBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
