// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bookings.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bookingsCancel = `-- name: BookingsCancel :exec
UPDATE bookings
SET status = 'cancelled', updated_at = now()
WHERE tenant_id = $1 AND branch_id = $2 AND id = $3 AND status = 'active'
`

type BookingsCancelParams struct {
	TenantID pgtype.UUID
	BranchID pgtype.UUID
	ID       pgtype.UUID
}

func (q *Queries) BookingsCancel(ctx context.Context, arg BookingsCancelParams) error {
	_, err := q.db.Exec(ctx, bookingsCancel, arg.TenantID, arg.BranchID, arg.ID)
	return err
}

const bookingsCountByBranch = `-- name: BookingsCountByBranch :one
SELECT COUNT(*)
FROM bookings
WHERE tenant_id = $1
  AND branch_id = $2
  AND ($3::uuid IS NULL OR child_id = $3)
  AND ($4 = '' OR status = $4)
  AND ($5 = '' OR funding_type = $5)
  AND ($6::date IS NULL OR effective_start_date >= $6)
  AND ($7::date IS NULL OR (effective_end_date IS NULL OR effective_end_date >= $7))
  AND (NOT $8::bool OR status = 'active')
`

type BookingsCountByBranchParams struct {
	TenantID pgtype.UUID
	BranchID pgtype.UUID
	Column3  pgtype.UUID
	Column4  interface{}
	Column5  interface{}
	Column6  pgtype.Date
	Column7  pgtype.Date
	Column8  bool
}

func (q *Queries) BookingsCountByBranch(ctx context.Context, arg BookingsCountByBranchParams) (int64, error) {
	row := q.db.QueryRow(ctx, bookingsCountByBranch,
		arg.TenantID,
		arg.BranchID,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const bookingsCreate = `-- name: BookingsCreate :exec
INSERT INTO bookings (id, tenant_id, branch_id, child_id, session_template_id, days_of_week, effective_start_date, effective_end_date, funding_type, funding_hours_per_week, la_reference, session_entries, status, booked_by_membership_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, 'active', $13)
`

type BookingsCreateParams struct {
	ID                   pgtype.UUID
	TenantID             pgtype.UUID
	BranchID             pgtype.UUID
	ChildID              pgtype.UUID
	SessionTemplateID    pgtype.UUID
	DaysOfWeek           []int32
	EffectiveStartDate   pgtype.Date
	EffectiveEndDate     pgtype.Date
	FundingType          pgtype.Text
	FundingHoursPerWeek  pgtype.Numeric
	LaReference          pgtype.Text
	SessionEntries       []byte
	BookedByMembershipID pgtype.UUID
}

func (q *Queries) BookingsCreate(ctx context.Context, arg BookingsCreateParams) error {
	_, err := q.db.Exec(ctx, bookingsCreate,
		arg.ID,
		arg.TenantID,
		arg.BranchID,
		arg.ChildID,
		arg.SessionTemplateID,
		arg.DaysOfWeek,
		arg.EffectiveStartDate,
		arg.EffectiveEndDate,
		arg.FundingType,
		arg.FundingHoursPerWeek,
		arg.LaReference,
		arg.SessionEntries,
		arg.BookedByMembershipID,
	)
	return err
}

const bookingsGetByID = `-- name: BookingsGetByID :one
SELECT id, tenant_id, branch_id, child_id, session_template_id, days_of_week, effective_start_date, effective_end_date, funding_type, funding_hours_per_week, la_reference, session_entries, status, booked_by_membership_id, created_at, updated_at
FROM bookings
WHERE tenant_id = $1
  AND branch_id = $2
  AND id = $3
`

type BookingsGetByIDParams struct {
	TenantID pgtype.UUID
	BranchID pgtype.UUID
	ID       pgtype.UUID
}

type BookingsGetByIDRow struct {
	ID                   pgtype.UUID
	TenantID             pgtype.UUID
	BranchID             pgtype.UUID
	ChildID              pgtype.UUID
	SessionTemplateID    pgtype.UUID
	DaysOfWeek           []int32
	EffectiveStartDate   pgtype.Date
	EffectiveEndDate     pgtype.Date
	FundingType          pgtype.Text
	FundingHoursPerWeek  pgtype.Numeric
	LaReference          pgtype.Text
	SessionEntries       []byte
	Status               string
	BookedByMembershipID pgtype.UUID
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

func (q *Queries) BookingsGetByID(ctx context.Context, arg BookingsGetByIDParams) (BookingsGetByIDRow, error) {
	row := q.db.QueryRow(ctx, bookingsGetByID, arg.TenantID, arg.BranchID, arg.ID)
	var i BookingsGetByIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BranchID,
		&i.ChildID,
		&i.SessionTemplateID,
		&i.DaysOfWeek,
		&i.EffectiveStartDate,
		&i.EffectiveEndDate,
		&i.FundingType,
		&i.FundingHoursPerWeek,
		&i.LaReference,
		&i.SessionEntries,
		&i.Status,
		&i.BookedByMembershipID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const bookingsGetByIDForUpdate = `-- name: BookingsGetByIDForUpdate :one
SELECT id, tenant_id, branch_id, child_id, session_template_id, days_of_week, effective_start_date, effective_end_date, funding_type, funding_hours_per_week, la_reference, session_entries, status, booked_by_membership_id, created_at, updated_at
FROM bookings
WHERE tenant_id = $1
  AND branch_id = $2
  AND id = $3
FOR UPDATE
`

type BookingsGetByIDForUpdateParams struct {
	TenantID pgtype.UUID
	BranchID pgtype.UUID
	ID       pgtype.UUID
}

type BookingsGetByIDForUpdateRow struct {
	ID                   pgtype.UUID
	TenantID             pgtype.UUID
	BranchID             pgtype.UUID
	ChildID              pgtype.UUID
	SessionTemplateID    pgtype.UUID
	DaysOfWeek           []int32
	EffectiveStartDate   pgtype.Date
	EffectiveEndDate     pgtype.Date
	FundingType          pgtype.Text
	FundingHoursPerWeek  pgtype.Numeric
	LaReference          pgtype.Text
	SessionEntries       []byte
	Status               string
	BookedByMembershipID pgtype.UUID
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

func (q *Queries) BookingsGetByIDForUpdate(ctx context.Context, arg BookingsGetByIDForUpdateParams) (BookingsGetByIDForUpdateRow, error) {
	row := q.db.QueryRow(ctx, bookingsGetByIDForUpdate, arg.TenantID, arg.BranchID, arg.ID)
	var i BookingsGetByIDForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BranchID,
		&i.ChildID,
		&i.SessionTemplateID,
		&i.DaysOfWeek,
		&i.EffectiveStartDate,
		&i.EffectiveEndDate,
		&i.FundingType,
		&i.FundingHoursPerWeek,
		&i.LaReference,
		&i.SessionEntries,
		&i.Status,
		&i.BookedByMembershipID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const bookingsListByBranchPaginated = `-- name: BookingsListByBranchPaginated :many
SELECT id, tenant_id, branch_id, child_id, session_template_id, days_of_week, effective_start_date, effective_end_date, funding_type, funding_hours_per_week, la_reference, session_entries, status, booked_by_membership_id, created_at, updated_at
FROM bookings
WHERE tenant_id = $1
  AND branch_id = $2
  AND ($3::uuid IS NULL OR child_id = $3)
  AND ($4 = '' OR status = $4)
  AND ($5 = '' OR funding_type = $5)
  AND ($6::date IS NULL OR effective_start_date >= $6)
  AND ($7::date IS NULL OR (effective_end_date IS NULL OR effective_end_date >= $7))
  AND (NOT $8::bool OR status = 'active')
ORDER BY effective_start_date DESC, created_at DESC
LIMIT $10 OFFSET $9
`

type BookingsListByBranchPaginatedParams struct {
	TenantID pgtype.UUID
	BranchID pgtype.UUID
	Column3  pgtype.UUID
	Column4  interface{}
	Column5  interface{}
	Column6  pgtype.Date
	Column7  pgtype.Date
	Column8  bool
	Offset   pgtype.Int4
	Limit    pgtype.Int4
}

type BookingsListByBranchPaginatedRow struct {
	ID                   pgtype.UUID
	TenantID             pgtype.UUID
	BranchID             pgtype.UUID
	ChildID              pgtype.UUID
	SessionTemplateID    pgtype.UUID
	DaysOfWeek           []int32
	EffectiveStartDate   pgtype.Date
	EffectiveEndDate     pgtype.Date
	FundingType          pgtype.Text
	FundingHoursPerWeek  pgtype.Numeric
	LaReference          pgtype.Text
	SessionEntries       []byte
	Status               string
	BookedByMembershipID pgtype.UUID
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

func (q *Queries) BookingsListByBranchPaginated(ctx context.Context, arg BookingsListByBranchPaginatedParams) ([]BookingsListByBranchPaginatedRow, error) {
	rows, err := q.db.Query(ctx, bookingsListByBranchPaginated,
		arg.TenantID,
		arg.BranchID,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BookingsListByBranchPaginatedRow
	for rows.Next() {
		var i BookingsListByBranchPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.BranchID,
			&i.ChildID,
			&i.SessionTemplateID,
			&i.DaysOfWeek,
			&i.EffectiveStartDate,
			&i.EffectiveEndDate,
			&i.FundingType,
			&i.FundingHoursPerWeek,
			&i.LaReference,
			&i.SessionEntries,
			&i.Status,
			&i.BookedByMembershipID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const bookingsListByChildAndDateRange = `-- name: BookingsListByChildAndDateRange :many
SELECT id, tenant_id, branch_id, child_id, session_template_id, days_of_week, effective_start_date, effective_end_date, funding_type, funding_hours_per_week, la_reference, session_entries, status, booked_by_membership_id, created_at, updated_at
FROM bookings
WHERE tenant_id = $1
  AND branch_id = $2
  AND child_id = $3
  AND effective_start_date <= $4
  AND (effective_end_date IS NULL OR effective_end_date >= $5)
  AND status = 'active'
ORDER BY effective_start_date ASC
`

type BookingsListByChildAndDateRangeParams struct {
	TenantID pgtype.UUID
	BranchID pgtype.UUID
	ChildID  pgtype.UUID
	ToDate   pgtype.Date
	FromDate pgtype.Date
}

type BookingsListByChildAndDateRangeRow struct {
	ID                   pgtype.UUID
	TenantID             pgtype.UUID
	BranchID             pgtype.UUID
	ChildID              pgtype.UUID
	SessionTemplateID    pgtype.UUID
	DaysOfWeek           []int32
	EffectiveStartDate   pgtype.Date
	EffectiveEndDate     pgtype.Date
	FundingType          pgtype.Text
	FundingHoursPerWeek  pgtype.Numeric
	LaReference          pgtype.Text
	SessionEntries       []byte
	Status               string
	BookedByMembershipID pgtype.UUID
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

func (q *Queries) BookingsListByChildAndDateRange(ctx context.Context, arg BookingsListByChildAndDateRangeParams) ([]BookingsListByChildAndDateRangeRow, error) {
	rows, err := q.db.Query(ctx, bookingsListByChildAndDateRange,
		arg.TenantID,
		arg.BranchID,
		arg.ChildID,
		arg.ToDate,
		arg.FromDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BookingsListByChildAndDateRangeRow
	for rows.Next() {
		var i BookingsListByChildAndDateRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.BranchID,
			&i.ChildID,
			&i.SessionTemplateID,
			&i.DaysOfWeek,
			&i.EffectiveStartDate,
			&i.EffectiveEndDate,
			&i.FundingType,
			&i.FundingHoursPerWeek,
			&i.LaReference,
			&i.SessionEntries,
			&i.Status,
			&i.BookedByMembershipID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const bookingsPause = `-- name: BookingsPause :exec
UPDATE bookings
SET status = 'paused', updated_at = now()
WHERE tenant_id = $1 AND branch_id = $2 AND id = $3 AND status = 'active'
`

type BookingsPauseParams struct {
	TenantID pgtype.UUID
	BranchID pgtype.UUID
	ID       pgtype.UUID
}

func (q *Queries) BookingsPause(ctx context.Context, arg BookingsPauseParams) error {
	_, err := q.db.Exec(ctx, bookingsPause, arg.TenantID, arg.BranchID, arg.ID)
	return err
}

const bookingsRegisterForDate = `-- name: BookingsRegisterForDate :many
SELECT
    b.child_id,
    c.first_name AS child_first_name,
    c.last_name AS child_last_name,
    r.id AS room_id,
    r.name AS room_name,
    b.session_template_id,
    st.name AS session_template_name,
    b.effective_start_date,
    b.effective_end_date,
    att.id AS attendance_id,
    att.status AS attendance_status,
    att.check_in_at,
    att.check_out_at
FROM bookings b
JOIN children c ON c.id = b.child_id AND c.tenant_id = b.tenant_id AND c.branch_id = b.branch_id
JOIN child_room_assignments cra ON cra.child_id = c.id AND cra.tenant_id = c.tenant_id AND cra.branch_id = c.branch_id
    AND cra.start_date <= $3 AND (cra.end_date IS NULL OR cra.end_date >= $3)
JOIN rooms r ON r.id = cra.room_id AND r.tenant_id = cra.tenant_id AND r.branch_id = cra.branch_id
JOIN session_templates st ON st.id = b.session_template_id AND st.tenant_id = b.tenant_id AND st.branch_id = b.branch_id
LEFT JOIN attendance_sessions att ON att.child_id = b.child_id
    AND att.tenant_id = b.tenant_id
    AND att.branch_id = b.branch_id
    AND att.check_in_local_date = $3
WHERE b.tenant_id = $1
  AND b.branch_id = $2
  AND b.status = 'active'
  AND b.effective_start_date <= $3
  AND (b.effective_end_date IS NULL OR b.effective_end_date >= $3)
  AND $4 = ANY(b.days_of_week)

UNION ALL

SELECT
    ah.child_id,
    c.first_name AS child_first_name,
    c.last_name AS child_last_name,
    r.id AS room_id,
    r.name AS room_name,
    ah.session_type_id AS session_template_id,
    st.name AS session_template_name,
    ah.calendar_date AS effective_start_date,
    ah.calendar_date AS effective_end_date,
    att.id AS attendance_id,
    att.status AS attendance_status,
    att.check_in_at,
    att.check_out_at
FROM ad_hoc_bookings ah
JOIN children c ON c.id = ah.child_id AND c.tenant_id = ah.tenant_id AND c.branch_id = ah.branch_id
JOIN child_room_assignments cra ON cra.child_id = c.id AND cra.tenant_id = c.tenant_id AND cra.branch_id = c.branch_id
    AND cra.start_date <= $3 AND (cra.end_date IS NULL OR cra.end_date >= $3)
JOIN rooms r ON r.id = cra.room_id AND r.tenant_id = cra.tenant_id AND r.branch_id = cra.branch_id
JOIN session_types st ON st.id = ah.session_type_id AND st.tenant_id = ah.tenant_id AND st.branch_id = ah.branch_id
LEFT JOIN attendance_sessions att ON att.child_id = ah.child_id
    AND att.tenant_id = ah.tenant_id
    AND att.branch_id = ah.branch_id
    AND att.check_in_local_date = $3
WHERE ah.tenant_id = $1
  AND ah.branch_id = $2
  AND ah.calendar_date = $3
  AND ah.status = 'active'

UNION ALL

SELECT
    h.child_id,
    c.first_name AS child_first_name,
    c.last_name AS child_last_name,
    r.id AS room_id,
    r.name AS room_name,
    h.session_type_id AS session_template_id,
    st.name AS session_template_name,
    h.calendar_date AS effective_start_date,
    h.calendar_date AS effective_end_date,
    att.id AS attendance_id,
    att.status AS attendance_status,
    att.check_in_at,
    att.check_out_at
FROM hourly_bookings h
JOIN children c ON c.id = h.child_id AND c.tenant_id = h.tenant_id AND c.branch_id = h.branch_id
JOIN child_room_assignments cra ON cra.child_id = c.id AND cra.tenant_id = c.tenant_id AND cra.branch_id = c.branch_id
    AND cra.start_date <= $3 AND (cra.end_date IS NULL OR cra.end_date >= $3)
JOIN rooms r ON r.id = cra.room_id AND r.tenant_id = cra.tenant_id AND r.branch_id = cra.branch_id
JOIN session_types st ON st.id = h.session_type_id AND st.tenant_id = h.tenant_id AND st.branch_id = h.branch_id
LEFT JOIN attendance_sessions att ON att.child_id = h.child_id
    AND att.tenant_id = h.tenant_id
    AND att.branch_id = h.branch_id
    AND att.check_in_local_date = $3
WHERE h.tenant_id = $1
  AND h.branch_id = $2
  AND h.calendar_date = $3
  AND h.status = 'active'

ORDER BY child_last_name, child_first_name
`

type BookingsRegisterForDateParams struct {
	TenantID        pgtype.UUID
	BranchID        pgtype.UUID
	RegisterDate    pgtype.Date
	RegisterDateDow []int32
}

type BookingsRegisterForDateRow struct {
	ChildID             pgtype.UUID
	ChildFirstName      string
	ChildLastName       pgtype.Text
	RoomID              pgtype.UUID
	RoomName            string
	SessionTemplateID   pgtype.UUID
	SessionTemplateName string
	EffectiveStartDate  pgtype.Date
	EffectiveEndDate    pgtype.Date
	AttendanceID        pgtype.UUID
	AttendanceStatus    pgtype.Text
	CheckInAt           pgtype.Timestamptz
	CheckOutAt          pgtype.Timestamptz
}

func (q *Queries) BookingsRegisterForDate(ctx context.Context, arg BookingsRegisterForDateParams) ([]BookingsRegisterForDateRow, error) {
	rows, err := q.db.Query(ctx, bookingsRegisterForDate,
		arg.TenantID,
		arg.BranchID,
		arg.RegisterDate,
		arg.RegisterDateDow,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BookingsRegisterForDateRow
	for rows.Next() {
		var i BookingsRegisterForDateRow
		if err := rows.Scan(
			&i.ChildID,
			&i.ChildFirstName,
			&i.ChildLastName,
			&i.RoomID,
			&i.RoomName,
			&i.SessionTemplateID,
			&i.SessionTemplateName,
			&i.EffectiveStartDate,
			&i.EffectiveEndDate,
			&i.AttendanceID,
			&i.AttendanceStatus,
			&i.CheckInAt,
			&i.CheckOutAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const bookingsUnifiedListByBranch = `-- name: BookingsUnifiedListByBranch :many
SELECT
    'recurring' AS booking_type,
    b.id,
    b.tenant_id,
    b.branch_id,
    b.child_id,
    b.effective_start_date AS start_date,
    b.effective_end_date AS end_date,
    b.session_template_id,
    b.status,
    b.created_at,
    b.updated_at,
    c.first_name AS child_first_name,
    c.last_name AS child_last_name
FROM bookings b
JOIN children c ON c.id = b.child_id AND c.tenant_id = b.tenant_id AND c.branch_id = b.branch_id
WHERE b.tenant_id = $1
  AND b.branch_id = $2
  AND ($3::uuid IS NULL OR b.child_id = $3)
  AND ($4 = '' OR b.status = $4)
  AND ($5 = '' OR b.funding_type = $5)
  AND ($6::date IS NULL OR (b.effective_end_date IS NULL OR b.effective_end_date >= $6))
  AND ($7::date IS NULL OR b.effective_start_date <= $7)
  AND (NOT $8::bool OR b.status = 'active')

UNION ALL

SELECT
    'ad_hoc' AS booking_type,
    ah.id,
    ah.tenant_id,
    ah.branch_id,
    ah.child_id,
    ah.calendar_date AS start_date,
    ah.calendar_date AS end_date,
    ah.session_type_id AS session_template_id,
    ah.status,
    ah.created_at,
    ah.updated_at,
    c.first_name AS child_first_name,
    c.last_name AS child_last_name
FROM ad_hoc_bookings ah
JOIN children c ON c.id = ah.child_id AND c.tenant_id = ah.tenant_id AND c.branch_id = ah.branch_id
WHERE ah.tenant_id = $1
  AND ah.branch_id = $2
  AND ($3::uuid IS NULL OR ah.child_id = $3)
  AND ($6::date IS NULL OR ah.calendar_date >= $6)
  AND ($7::date IS NULL OR ah.calendar_date <= $7)
  AND (NOT $8::bool OR ah.status = 'active')

UNION ALL

SELECT
    'hourly' AS booking_type,
    h.id,
    h.tenant_id,
    h.branch_id,
    h.child_id,
    h.calendar_date AS start_date,
    h.calendar_date AS end_date,
    h.session_type_id AS session_template_id,
    h.status,
    h.created_at,
    h.updated_at,
    c.first_name AS child_first_name,
    c.last_name AS child_last_name
FROM hourly_bookings h
JOIN children c ON c.id = h.child_id AND c.tenant_id = h.tenant_id AND c.branch_id = h.branch_id
WHERE h.tenant_id = $1
  AND h.branch_id = $2
  AND ($3::uuid IS NULL OR h.child_id = $3)
  AND ($6::date IS NULL OR h.calendar_date >= $6)
  AND ($7::date IS NULL OR h.calendar_date <= $7)
  AND (NOT $8::bool OR h.status = 'active')

ORDER BY start_date DESC, created_at DESC
LIMIT $10 OFFSET $9
`

type BookingsUnifiedListByBranchParams struct {
	TenantID pgtype.UUID
	BranchID pgtype.UUID
	Column3  pgtype.UUID
	Column4  interface{}
	Column5  interface{}
	Column6  pgtype.Date
	Column7  pgtype.Date
	Column8  bool
	Offset   pgtype.Int4
	Limit    pgtype.Int4
}

type BookingsUnifiedListByBranchRow struct {
	BookingType       string
	ID                pgtype.UUID
	TenantID          pgtype.UUID
	BranchID          pgtype.UUID
	ChildID           pgtype.UUID
	StartDate         pgtype.Date
	EndDate           pgtype.Date
	SessionTemplateID pgtype.UUID
	Status            string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	ChildFirstName    string
	ChildLastName     pgtype.Text
}

func (q *Queries) BookingsUnifiedListByBranch(ctx context.Context, arg BookingsUnifiedListByBranchParams) ([]BookingsUnifiedListByBranchRow, error) {
	rows, err := q.db.Query(ctx, bookingsUnifiedListByBranch,
		arg.TenantID,
		arg.BranchID,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BookingsUnifiedListByBranchRow
	for rows.Next() {
		var i BookingsUnifiedListByBranchRow
		if err := rows.Scan(
			&i.BookingType,
			&i.ID,
			&i.TenantID,
			&i.BranchID,
			&i.ChildID,
			&i.StartDate,
			&i.EndDate,
			&i.SessionTemplateID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ChildFirstName,
			&i.ChildLastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const bookingsUpdate = `-- name: BookingsUpdate :exec
UPDATE bookings
SET days_of_week = $4,
    effective_start_date = $5,
    effective_end_date = $6,
    funding_type = $7,
    funding_hours_per_week = $8,
    la_reference = $9,
    updated_at = now()
WHERE tenant_id = $1
  AND branch_id = $2
  AND id = $3
`

type BookingsUpdateParams struct {
	TenantID            pgtype.UUID
	BranchID            pgtype.UUID
	ID                  pgtype.UUID
	DaysOfWeek          []int32
	EffectiveStartDate  pgtype.Date
	EffectiveEndDate    pgtype.Date
	FundingType         pgtype.Text
	FundingHoursPerWeek pgtype.Numeric
	LaReference         pgtype.Text
}

func (q *Queries) BookingsUpdate(ctx context.Context, arg BookingsUpdateParams) error {
	_, err := q.db.Exec(ctx, bookingsUpdate,
		arg.TenantID,
		arg.BranchID,
		arg.ID,
		arg.DaysOfWeek,
		arg.EffectiveStartDate,
		arg.EffectiveEndDate,
		arg.FundingType,
		arg.FundingHoursPerWeek,
		arg.LaReference,
	)
	return err
}
