// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: child_collection_settings.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const childCollectionSettingGetByChild = `-- name: ChildCollectionSettingGetByChild :one
SELECT id, tenant_id, branch_id, child_id,
       over_18_collection_acknowledged,
       collection_password, collection_password_updated_at,
       collection_password_updated_by_user_id, collection_password_updated_by_membership_id,
       created_at, updated_at, collection_password_hint
FROM child_collection_settings
WHERE tenant_id = $1 AND branch_id = $2 AND child_id = $3
`

type ChildCollectionSettingGetByChildParams struct {
	TenantID pgtype.UUID
	BranchID pgtype.UUID
	ChildID  pgtype.UUID
}

type ChildCollectionSettingGetByChildRow struct {
	ID                                      pgtype.UUID
	TenantID                                pgtype.UUID
	BranchID                                pgtype.UUID
	ChildID                                 pgtype.UUID
	Over18CollectionAcknowledged            bool
	CollectionPassword                      pgtype.Text
	CollectionPasswordUpdatedAt             pgtype.Timestamptz
	CollectionPasswordUpdatedByUserID       pgtype.UUID
	CollectionPasswordUpdatedByMembershipID pgtype.UUID
	CreatedAt                               pgtype.Timestamptz
	UpdatedAt                               pgtype.Timestamptz
	CollectionPasswordHint                  pgtype.Text
}

func (q *Queries) ChildCollectionSettingGetByChild(ctx context.Context, arg ChildCollectionSettingGetByChildParams) (ChildCollectionSettingGetByChildRow, error) {
	row := q.db.QueryRow(ctx, childCollectionSettingGetByChild, arg.TenantID, arg.BranchID, arg.ChildID)
	var i ChildCollectionSettingGetByChildRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BranchID,
		&i.ChildID,
		&i.Over18CollectionAcknowledged,
		&i.CollectionPassword,
		&i.CollectionPasswordUpdatedAt,
		&i.CollectionPasswordUpdatedByUserID,
		&i.CollectionPasswordUpdatedByMembershipID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CollectionPasswordHint,
	)
	return i, err
}

const childCollectionSettingSetPassword = `-- name: ChildCollectionSettingSetPassword :one
UPDATE child_collection_settings SET
    collection_password = $5,
    collection_password_hint = $6,
    collection_password_updated_at = $7,
    collection_password_updated_by_user_id = $8,
    collection_password_updated_by_membership_id = $9,
    updated_at = now()
WHERE tenant_id = $1 AND branch_id = $2 AND child_id = $3 AND id = $4
RETURNING id, tenant_id, branch_id, child_id,
          over_18_collection_acknowledged,
          collection_password, collection_password_updated_at,
          collection_password_updated_by_user_id, collection_password_updated_by_membership_id,
          created_at, updated_at, collection_password_hint
`

type ChildCollectionSettingSetPasswordParams struct {
	TenantID                                pgtype.UUID
	BranchID                                pgtype.UUID
	ChildID                                 pgtype.UUID
	ID                                      pgtype.UUID
	CollectionPassword                      pgtype.Text
	CollectionPasswordHint                  pgtype.Text
	CollectionPasswordUpdatedAt             pgtype.Timestamptz
	CollectionPasswordUpdatedByUserID       pgtype.UUID
	CollectionPasswordUpdatedByMembershipID pgtype.UUID
}

type ChildCollectionSettingSetPasswordRow struct {
	ID                                      pgtype.UUID
	TenantID                                pgtype.UUID
	BranchID                                pgtype.UUID
	ChildID                                 pgtype.UUID
	Over18CollectionAcknowledged            bool
	CollectionPassword                      pgtype.Text
	CollectionPasswordUpdatedAt             pgtype.Timestamptz
	CollectionPasswordUpdatedByUserID       pgtype.UUID
	CollectionPasswordUpdatedByMembershipID pgtype.UUID
	CreatedAt                               pgtype.Timestamptz
	UpdatedAt                               pgtype.Timestamptz
	CollectionPasswordHint                  pgtype.Text
}

func (q *Queries) ChildCollectionSettingSetPassword(ctx context.Context, arg ChildCollectionSettingSetPasswordParams) (ChildCollectionSettingSetPasswordRow, error) {
	row := q.db.QueryRow(ctx, childCollectionSettingSetPassword,
		arg.TenantID,
		arg.BranchID,
		arg.ChildID,
		arg.ID,
		arg.CollectionPassword,
		arg.CollectionPasswordHint,
		arg.CollectionPasswordUpdatedAt,
		arg.CollectionPasswordUpdatedByUserID,
		arg.CollectionPasswordUpdatedByMembershipID,
	)
	var i ChildCollectionSettingSetPasswordRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BranchID,
		&i.ChildID,
		&i.Over18CollectionAcknowledged,
		&i.CollectionPassword,
		&i.CollectionPasswordUpdatedAt,
		&i.CollectionPasswordUpdatedByUserID,
		&i.CollectionPasswordUpdatedByMembershipID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CollectionPasswordHint,
	)
	return i, err
}

const childCollectionSettingUpsert = `-- name: ChildCollectionSettingUpsert :one
INSERT INTO child_collection_settings (
    id, tenant_id, branch_id, child_id,
    over_18_collection_acknowledged,
    collection_password_hint
)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (child_id) DO UPDATE SET
    over_18_collection_acknowledged = EXCLUDED.over_18_collection_acknowledged,
    collection_password_hint = EXCLUDED.collection_password_hint,
    updated_at = now()
RETURNING id, tenant_id, branch_id, child_id,
          over_18_collection_acknowledged,
          collection_password, collection_password_updated_at,
          collection_password_updated_by_user_id, collection_password_updated_by_membership_id,
          created_at, updated_at, collection_password_hint
`

type ChildCollectionSettingUpsertParams struct {
	ID                           pgtype.UUID
	TenantID                     pgtype.UUID
	BranchID                     pgtype.UUID
	ChildID                      pgtype.UUID
	Over18CollectionAcknowledged bool
	CollectionPasswordHint       pgtype.Text
}

type ChildCollectionSettingUpsertRow struct {
	ID                                      pgtype.UUID
	TenantID                                pgtype.UUID
	BranchID                                pgtype.UUID
	ChildID                                 pgtype.UUID
	Over18CollectionAcknowledged            bool
	CollectionPassword                      pgtype.Text
	CollectionPasswordUpdatedAt             pgtype.Timestamptz
	CollectionPasswordUpdatedByUserID       pgtype.UUID
	CollectionPasswordUpdatedByMembershipID pgtype.UUID
	CreatedAt                               pgtype.Timestamptz
	UpdatedAt                               pgtype.Timestamptz
	CollectionPasswordHint                  pgtype.Text
}

func (q *Queries) ChildCollectionSettingUpsert(ctx context.Context, arg ChildCollectionSettingUpsertParams) (ChildCollectionSettingUpsertRow, error) {
	row := q.db.QueryRow(ctx, childCollectionSettingUpsert,
		arg.ID,
		arg.TenantID,
		arg.BranchID,
		arg.ChildID,
		arg.Over18CollectionAcknowledged,
		arg.CollectionPasswordHint,
	)
	var i ChildCollectionSettingUpsertRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BranchID,
		&i.ChildID,
		&i.Over18CollectionAcknowledged,
		&i.CollectionPassword,
		&i.CollectionPasswordUpdatedAt,
		&i.CollectionPasswordUpdatedByUserID,
		&i.CollectionPasswordUpdatedByMembershipID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CollectionPasswordHint,
	)
	return i, err
}
