// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: child_funding_records.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const childFundingRecordGetByChild = `-- name: ChildFundingRecordGetByChild :one
SELECT id, tenant_id, branch_id, child_id,
       funding_enabled, funding_type, funding_model,
       funded_hours_per_week, funding_start_date, funding_end_date,
       eligibility_code, eligibility_code_validated,
       evidence_received, benefits_status,
       benefit_universal_credit, benefit_income_support,
       benefit_jobseekers_allowance, benefit_esa_income_related,
       benefit_child_tax_credit, benefit_other_support,
       other_benefit_name,
       benefit_notes, manager_notes,
       created_at, updated_at
FROM child_funding_records
WHERE tenant_id = $1 AND branch_id = $2 AND child_id = $3
`

type ChildFundingRecordGetByChildParams struct {
	TenantID pgtype.UUID
	BranchID pgtype.UUID
	ChildID  pgtype.UUID
}

type ChildFundingRecordGetByChildRow struct {
	ID                         pgtype.UUID
	TenantID                   pgtype.UUID
	BranchID                   pgtype.UUID
	ChildID                    pgtype.UUID
	FundingEnabled             bool
	FundingType                string
	FundingModel               string
	FundedHoursPerWeek         pgtype.Numeric
	FundingStartDate           pgtype.Date
	FundingEndDate             pgtype.Date
	EligibilityCode            pgtype.Text
	EligibilityCodeValidated   bool
	EvidenceReceived           bool
	BenefitsStatus             string
	BenefitUniversalCredit     bool
	BenefitIncomeSupport       bool
	BenefitJobseekersAllowance bool
	BenefitEsaIncomeRelated    bool
	BenefitChildTaxCredit      bool
	BenefitOtherSupport        bool
	OtherBenefitName           pgtype.Text
	BenefitNotes               pgtype.Text
	ManagerNotes               pgtype.Text
	CreatedAt                  pgtype.Timestamptz
	UpdatedAt                  pgtype.Timestamptz
}

func (q *Queries) ChildFundingRecordGetByChild(ctx context.Context, arg ChildFundingRecordGetByChildParams) (ChildFundingRecordGetByChildRow, error) {
	row := q.db.QueryRow(ctx, childFundingRecordGetByChild, arg.TenantID, arg.BranchID, arg.ChildID)
	var i ChildFundingRecordGetByChildRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BranchID,
		&i.ChildID,
		&i.FundingEnabled,
		&i.FundingType,
		&i.FundingModel,
		&i.FundedHoursPerWeek,
		&i.FundingStartDate,
		&i.FundingEndDate,
		&i.EligibilityCode,
		&i.EligibilityCodeValidated,
		&i.EvidenceReceived,
		&i.BenefitsStatus,
		&i.BenefitUniversalCredit,
		&i.BenefitIncomeSupport,
		&i.BenefitJobseekersAllowance,
		&i.BenefitEsaIncomeRelated,
		&i.BenefitChildTaxCredit,
		&i.BenefitOtherSupport,
		&i.OtherBenefitName,
		&i.BenefitNotes,
		&i.ManagerNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const childFundingRecordUpsert = `-- name: ChildFundingRecordUpsert :one
INSERT INTO child_funding_records (
    id, tenant_id, branch_id, child_id,
    funding_enabled, funding_type, funding_model,
    funded_hours_per_week, funding_start_date, funding_end_date,
    eligibility_code, eligibility_code_validated,
    evidence_received, benefits_status,
    benefit_universal_credit, benefit_income_support,
    benefit_jobseekers_allowance, benefit_esa_income_related,
    benefit_child_tax_credit, benefit_other_support,
    other_benefit_name,
    benefit_notes, manager_notes
)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8::numeric, $9::date, $10::date,
    NULLIF($11, ''), $12,
    $13, $14,
    $15, $16,
    $17, $18,
    $19, $20,
    NULLIF($21, ''),
    NULLIF($22, ''), NULLIF($23, '')
)
ON CONFLICT (child_id) DO UPDATE SET
    funding_enabled = EXCLUDED.funding_enabled,
    funding_type = EXCLUDED.funding_type,
    funding_model = EXCLUDED.funding_model,
    funded_hours_per_week = EXCLUDED.funded_hours_per_week,
    funding_start_date = EXCLUDED.funding_start_date,
    funding_end_date = EXCLUDED.funding_end_date,
    eligibility_code = EXCLUDED.eligibility_code,
    eligibility_code_validated = EXCLUDED.eligibility_code_validated,
    evidence_received = EXCLUDED.evidence_received,
    benefits_status = EXCLUDED.benefits_status,
    benefit_universal_credit = EXCLUDED.benefit_universal_credit,
    benefit_income_support = EXCLUDED.benefit_income_support,
    benefit_jobseekers_allowance = EXCLUDED.benefit_jobseekers_allowance,
    benefit_esa_income_related = EXCLUDED.benefit_esa_income_related,
    benefit_child_tax_credit = EXCLUDED.benefit_child_tax_credit,
    benefit_other_support = EXCLUDED.benefit_other_support,
    other_benefit_name = EXCLUDED.other_benefit_name,
    benefit_notes = EXCLUDED.benefit_notes,
    manager_notes = EXCLUDED.manager_notes,
    updated_at = now()
RETURNING id, tenant_id, branch_id, child_id,
          funding_enabled, funding_type, funding_model,
          funded_hours_per_week, funding_start_date, funding_end_date,
          eligibility_code, eligibility_code_validated,
          evidence_received, benefits_status,
          benefit_universal_credit, benefit_income_support,
          benefit_jobseekers_allowance, benefit_esa_income_related,
          benefit_child_tax_credit, benefit_other_support,
          other_benefit_name,
          benefit_notes, manager_notes,
          created_at, updated_at
`

type ChildFundingRecordUpsertParams struct {
	ID                         pgtype.UUID
	TenantID                   pgtype.UUID
	BranchID                   pgtype.UUID
	ChildID                    pgtype.UUID
	FundingEnabled             bool
	FundingType                string
	FundingModel               string
	Column8                    pgtype.Numeric
	Column9                    pgtype.Date
	Column10                   pgtype.Date
	Column11                   interface{}
	EligibilityCodeValidated   bool
	EvidenceReceived           bool
	BenefitsStatus             string
	BenefitUniversalCredit     bool
	BenefitIncomeSupport       bool
	BenefitJobseekersAllowance bool
	BenefitEsaIncomeRelated    bool
	BenefitChildTaxCredit      bool
	BenefitOtherSupport        bool
	Column21                   interface{}
	Column22                   interface{}
	Column23                   interface{}
}

type ChildFundingRecordUpsertRow struct {
	ID                         pgtype.UUID
	TenantID                   pgtype.UUID
	BranchID                   pgtype.UUID
	ChildID                    pgtype.UUID
	FundingEnabled             bool
	FundingType                string
	FundingModel               string
	FundedHoursPerWeek         pgtype.Numeric
	FundingStartDate           pgtype.Date
	FundingEndDate             pgtype.Date
	EligibilityCode            pgtype.Text
	EligibilityCodeValidated   bool
	EvidenceReceived           bool
	BenefitsStatus             string
	BenefitUniversalCredit     bool
	BenefitIncomeSupport       bool
	BenefitJobseekersAllowance bool
	BenefitEsaIncomeRelated    bool
	BenefitChildTaxCredit      bool
	BenefitOtherSupport        bool
	OtherBenefitName           pgtype.Text
	BenefitNotes               pgtype.Text
	ManagerNotes               pgtype.Text
	CreatedAt                  pgtype.Timestamptz
	UpdatedAt                  pgtype.Timestamptz
}

func (q *Queries) ChildFundingRecordUpsert(ctx context.Context, arg ChildFundingRecordUpsertParams) (ChildFundingRecordUpsertRow, error) {
	row := q.db.QueryRow(ctx, childFundingRecordUpsert,
		arg.ID,
		arg.TenantID,
		arg.BranchID,
		arg.ChildID,
		arg.FundingEnabled,
		arg.FundingType,
		arg.FundingModel,
		arg.Column8,
		arg.Column9,
		arg.Column10,
		arg.Column11,
		arg.EligibilityCodeValidated,
		arg.EvidenceReceived,
		arg.BenefitsStatus,
		arg.BenefitUniversalCredit,
		arg.BenefitIncomeSupport,
		arg.BenefitJobseekersAllowance,
		arg.BenefitEsaIncomeRelated,
		arg.BenefitChildTaxCredit,
		arg.BenefitOtherSupport,
		arg.Column21,
		arg.Column22,
		arg.Column23,
	)
	var i ChildFundingRecordUpsertRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BranchID,
		&i.ChildID,
		&i.FundingEnabled,
		&i.FundingType,
		&i.FundingModel,
		&i.FundedHoursPerWeek,
		&i.FundingStartDate,
		&i.FundingEndDate,
		&i.EligibilityCode,
		&i.EligibilityCodeValidated,
		&i.EvidenceReceived,
		&i.BenefitsStatus,
		&i.BenefitUniversalCredit,
		&i.BenefitIncomeSupport,
		&i.BenefitJobseekersAllowance,
		&i.BenefitEsaIncomeRelated,
		&i.BenefitChildTaxCredit,
		&i.BenefitOtherSupport,
		&i.OtherBenefitName,
		&i.BenefitNotes,
		&i.ManagerNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
