// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_outbox.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countEmails = `-- name: CountEmails :one
SELECT COUNT(*)
FROM email_outbox
WHERE tenant_id = $1 AND branch_id = $2
  AND ($3::text IS NULL OR status = $3::text)
`

type CountEmailsParams struct {
	TenantID pgtype.UUID
	BranchID pgtype.UUID
	Status   pgtype.Text
}

func (q *Queries) CountEmails(ctx context.Context, arg CountEmailsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEmails, arg.TenantID, arg.BranchID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getEmailByID = `-- name: GetEmailByID :one
SELECT id, tenant_id, branch_id, idempotency_key, event_type,
    recipient, recipient_name, subject, template_name, template_version,
    payload_json, attachments, entity_id, status, attempts, max_attempts, next_retry_at,
    last_error, provider_message_id, created_at, sent_at, updated_at
FROM email_outbox
WHERE tenant_id = $1 AND branch_id = $2 AND id = $3
`

type GetEmailByIDParams struct {
	TenantID pgtype.UUID
	BranchID pgtype.UUID
	ID       pgtype.UUID
}

type GetEmailByIDRow struct {
	ID                pgtype.UUID
	TenantID          pgtype.UUID
	BranchID          pgtype.UUID
	IdempotencyKey    string
	EventType         string
	Recipient         string
	RecipientName     pgtype.Text
	Subject           string
	TemplateName      string
	TemplateVersion   int32
	PayloadJson       []byte
	Attachments       []byte
	EntityID          pgtype.Text
	Status            string
	Attempts          int32
	MaxAttempts       int32
	NextRetryAt       pgtype.Timestamptz
	LastError         pgtype.Text
	ProviderMessageID pgtype.Text
	CreatedAt         pgtype.Timestamptz
	SentAt            pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

func (q *Queries) GetEmailByID(ctx context.Context, arg GetEmailByIDParams) (GetEmailByIDRow, error) {
	row := q.db.QueryRow(ctx, getEmailByID, arg.TenantID, arg.BranchID, arg.ID)
	var i GetEmailByIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BranchID,
		&i.IdempotencyKey,
		&i.EventType,
		&i.Recipient,
		&i.RecipientName,
		&i.Subject,
		&i.TemplateName,
		&i.TemplateVersion,
		&i.PayloadJson,
		&i.Attachments,
		&i.EntityID,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.NextRetryAt,
		&i.LastError,
		&i.ProviderMessageID,
		&i.CreatedAt,
		&i.SentAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmailStats = `-- name: GetEmailStats :many
SELECT status, COUNT(*)::integer AS count
FROM email_outbox
WHERE tenant_id = $1 AND branch_id = $2
GROUP BY status
`

type GetEmailStatsParams struct {
	TenantID pgtype.UUID
	BranchID pgtype.UUID
}

type GetEmailStatsRow struct {
	Status string
	Count  int32
}

func (q *Queries) GetEmailStats(ctx context.Context, arg GetEmailStatsParams) ([]GetEmailStatsRow, error) {
	rows, err := q.db.Query(ctx, getEmailStats, arg.TenantID, arg.BranchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEmailStatsRow
	for rows.Next() {
		var i GetEmailStatsRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingEmails = `-- name: GetPendingEmails :many
SELECT id, tenant_id, branch_id, idempotency_key, event_type,
    recipient, recipient_name, subject, template_name, template_version,
    payload_json, attachments, entity_id, status, attempts, max_attempts, next_retry_at,
    last_error, provider_message_id, created_at, sent_at, updated_at
FROM email_outbox
WHERE status = 'pending'
  AND next_retry_at <= now()
ORDER BY next_retry_at ASC
FOR UPDATE SKIP LOCKED
LIMIT $1
`

type GetPendingEmailsRow struct {
	ID                pgtype.UUID
	TenantID          pgtype.UUID
	BranchID          pgtype.UUID
	IdempotencyKey    string
	EventType         string
	Recipient         string
	RecipientName     pgtype.Text
	Subject           string
	TemplateName      string
	TemplateVersion   int32
	PayloadJson       []byte
	Attachments       []byte
	EntityID          pgtype.Text
	Status            string
	Attempts          int32
	MaxAttempts       int32
	NextRetryAt       pgtype.Timestamptz
	LastError         pgtype.Text
	ProviderMessageID pgtype.Text
	CreatedAt         pgtype.Timestamptz
	SentAt            pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

func (q *Queries) GetPendingEmails(ctx context.Context, limit int32) ([]GetPendingEmailsRow, error) {
	rows, err := q.db.Query(ctx, getPendingEmails, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPendingEmailsRow
	for rows.Next() {
		var i GetPendingEmailsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.BranchID,
			&i.IdempotencyKey,
			&i.EventType,
			&i.Recipient,
			&i.RecipientName,
			&i.Subject,
			&i.TemplateName,
			&i.TemplateVersion,
			&i.PayloadJson,
			&i.Attachments,
			&i.EntityID,
			&i.Status,
			&i.Attempts,
			&i.MaxAttempts,
			&i.NextRetryAt,
			&i.LastError,
			&i.ProviderMessageID,
			&i.CreatedAt,
			&i.SentAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertEmailOutbox = `-- name: InsertEmailOutbox :one
INSERT INTO email_outbox (
    id, tenant_id, branch_id, idempotency_key, event_type,
    recipient, recipient_name, subject, template_name, template_version,
    payload_json, attachments, entity_id, status, max_attempts
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    $11, $12, $13, 'pending', $14
)
RETURNING id, tenant_id, branch_id, idempotency_key, event_type,
    recipient, recipient_name, subject, template_name, template_version,
    payload_json, attachments, entity_id, status, attempts, max_attempts, next_retry_at,
    last_error, provider_message_id, created_at, sent_at, updated_at
`

type InsertEmailOutboxParams struct {
	ID              pgtype.UUID
	TenantID        pgtype.UUID
	BranchID        pgtype.UUID
	IdempotencyKey  string
	EventType       string
	Recipient       string
	RecipientName   pgtype.Text
	Subject         string
	TemplateName    string
	TemplateVersion int32
	PayloadJson     []byte
	Attachments     []byte
	EntityID        pgtype.Text
	MaxAttempts     int32
}

type InsertEmailOutboxRow struct {
	ID                pgtype.UUID
	TenantID          pgtype.UUID
	BranchID          pgtype.UUID
	IdempotencyKey    string
	EventType         string
	Recipient         string
	RecipientName     pgtype.Text
	Subject           string
	TemplateName      string
	TemplateVersion   int32
	PayloadJson       []byte
	Attachments       []byte
	EntityID          pgtype.Text
	Status            string
	Attempts          int32
	MaxAttempts       int32
	NextRetryAt       pgtype.Timestamptz
	LastError         pgtype.Text
	ProviderMessageID pgtype.Text
	CreatedAt         pgtype.Timestamptz
	SentAt            pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

func (q *Queries) InsertEmailOutbox(ctx context.Context, arg InsertEmailOutboxParams) (InsertEmailOutboxRow, error) {
	row := q.db.QueryRow(ctx, insertEmailOutbox,
		arg.ID,
		arg.TenantID,
		arg.BranchID,
		arg.IdempotencyKey,
		arg.EventType,
		arg.Recipient,
		arg.RecipientName,
		arg.Subject,
		arg.TemplateName,
		arg.TemplateVersion,
		arg.PayloadJson,
		arg.Attachments,
		arg.EntityID,
		arg.MaxAttempts,
	)
	var i InsertEmailOutboxRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BranchID,
		&i.IdempotencyKey,
		&i.EventType,
		&i.Recipient,
		&i.RecipientName,
		&i.Subject,
		&i.TemplateName,
		&i.TemplateVersion,
		&i.PayloadJson,
		&i.Attachments,
		&i.EntityID,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.NextRetryAt,
		&i.LastError,
		&i.ProviderMessageID,
		&i.CreatedAt,
		&i.SentAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEmails = `-- name: ListEmails :many
SELECT id, tenant_id, branch_id, idempotency_key, event_type,
    recipient, recipient_name, subject, template_name, template_version,
    payload_json, attachments, entity_id, status, attempts, max_attempts, next_retry_at,
    last_error, provider_message_id, created_at, sent_at, updated_at
FROM email_outbox
WHERE tenant_id = $1 AND branch_id = $2
  AND ($3::text IS NULL OR status = $3::text)
ORDER BY created_at DESC
LIMIT $5 OFFSET $4
`

type ListEmailsParams struct {
	TenantID pgtype.UUID
	BranchID pgtype.UUID
	Status   pgtype.Text
	Offset   pgtype.Int4
	Limit    pgtype.Int4
}

type ListEmailsRow struct {
	ID                pgtype.UUID
	TenantID          pgtype.UUID
	BranchID          pgtype.UUID
	IdempotencyKey    string
	EventType         string
	Recipient         string
	RecipientName     pgtype.Text
	Subject           string
	TemplateName      string
	TemplateVersion   int32
	PayloadJson       []byte
	Attachments       []byte
	EntityID          pgtype.Text
	Status            string
	Attempts          int32
	MaxAttempts       int32
	NextRetryAt       pgtype.Timestamptz
	LastError         pgtype.Text
	ProviderMessageID pgtype.Text
	CreatedAt         pgtype.Timestamptz
	SentAt            pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

func (q *Queries) ListEmails(ctx context.Context, arg ListEmailsParams) ([]ListEmailsRow, error) {
	rows, err := q.db.Query(ctx, listEmails,
		arg.TenantID,
		arg.BranchID,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEmailsRow
	for rows.Next() {
		var i ListEmailsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.BranchID,
			&i.IdempotencyKey,
			&i.EventType,
			&i.Recipient,
			&i.RecipientName,
			&i.Subject,
			&i.TemplateName,
			&i.TemplateVersion,
			&i.PayloadJson,
			&i.Attachments,
			&i.EntityID,
			&i.Status,
			&i.Attempts,
			&i.MaxAttempts,
			&i.NextRetryAt,
			&i.LastError,
			&i.ProviderMessageID,
			&i.CreatedAt,
			&i.SentAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetEmailToPending = `-- name: ResetEmailToPending :exec
UPDATE email_outbox
SET status = 'pending',
    attempts = 0,
    next_retry_at = now(),
    last_error = NULL
WHERE id = $1 AND status = 'dead_letter'
`

func (q *Queries) ResetEmailToPending(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, resetEmailToPending, id)
	return err
}

const updateEmailStatus = `-- name: UpdateEmailStatus :exec
UPDATE email_outbox
SET status = $2,
    attempts = $3,
    next_retry_at = $4,
    last_error = $5,
    provider_message_id = $6,
    sent_at = CASE WHEN $2 = 'sent' THEN now() ELSE sent_at END,
    updated_at = now()
WHERE id = $1
`

type UpdateEmailStatusParams struct {
	ID                pgtype.UUID
	Status            string
	Attempts          int32
	NextRetryAt       pgtype.Timestamptz
	LastError         pgtype.Text
	ProviderMessageID pgtype.Text
}

func (q *Queries) UpdateEmailStatus(ctx context.Context, arg UpdateEmailStatusParams) error {
	_, err := q.db.Exec(ctx, updateEmailStatus,
		arg.ID,
		arg.Status,
		arg.Attempts,
		arg.NextRetryAt,
		arg.LastError,
		arg.ProviderMessageID,
	)
	return err
}
