// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: manager_invites.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const inviteAccept = `-- name: InviteAccept :exec
UPDATE manager_invites
SET accepted_at = now(),
    accepted_user_id = $2,
    accepted_membership_id = $3,
    updated_at = now()
WHERE id = $1
  AND accepted_at IS NULL
  AND revoked_at IS NULL
`

type InviteAcceptParams struct {
	ID                   pgtype.UUID
	AcceptedUserID       pgtype.UUID
	AcceptedMembershipID pgtype.UUID
}

func (q *Queries) InviteAccept(ctx context.Context, arg InviteAcceptParams) error {
	_, err := q.db.Exec(ctx, inviteAccept, arg.ID, arg.AcceptedUserID, arg.AcceptedMembershipID)
	return err
}

const inviteAcquireEmailScopeLock = `-- name: InviteAcquireEmailScopeLock :execrows
SELECT pg_advisory_xact_lock(hashtextextended($1, 0))
`

func (q *Queries) InviteAcquireEmailScopeLock(ctx context.Context, hashtextextended string) (int64, error) {
	result, err := q.db.Exec(ctx, inviteAcquireEmailScopeLock, hashtextextended)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const inviteCreate = `-- name: InviteCreate :exec
INSERT INTO manager_invites (
    id, tenant_id, branch_id, email, email_normalized, role,
    token_hash, expires_at,
    created_by_user_id, created_by_membership_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InviteCreateParams struct {
	ID                    pgtype.UUID
	TenantID              pgtype.UUID
	BranchID              pgtype.UUID
	Email                 string
	EmailNormalized       string
	Role                  string
	TokenHash             string
	ExpiresAt             pgtype.Timestamptz
	CreatedByUserID       pgtype.UUID
	CreatedByMembershipID pgtype.UUID
}

func (q *Queries) InviteCreate(ctx context.Context, arg InviteCreateParams) error {
	_, err := q.db.Exec(ctx, inviteCreate,
		arg.ID,
		arg.TenantID,
		arg.BranchID,
		arg.Email,
		arg.EmailNormalized,
		arg.Role,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.CreatedByUserID,
		arg.CreatedByMembershipID,
	)
	return err
}

const inviteCreateMembership = `-- name: InviteCreateMembership :exec
INSERT INTO memberships (id, tenant_id, branch_id, user_id, role, is_active)
VALUES ($1, $2, $3, $4, $5, true)
`

type InviteCreateMembershipParams struct {
	ID       pgtype.UUID
	TenantID pgtype.UUID
	BranchID pgtype.UUID
	UserID   pgtype.UUID
	Role     string
}

func (q *Queries) InviteCreateMembership(ctx context.Context, arg InviteCreateMembershipParams) error {
	_, err := q.db.Exec(ctx, inviteCreateMembership,
		arg.ID,
		arg.TenantID,
		arg.BranchID,
		arg.UserID,
		arg.Role,
	)
	return err
}

const inviteCreateUser = `-- name: InviteCreateUser :execrows
INSERT INTO users (id, email, email_normalized, password_hash, is_active)
VALUES ($1, $2, $3, $4, true)
`

type InviteCreateUserParams struct {
	ID              pgtype.UUID
	Email           string
	EmailNormalized string
	PasswordHash    string
}

func (q *Queries) InviteCreateUser(ctx context.Context, arg InviteCreateUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, inviteCreateUser,
		arg.ID,
		arg.Email,
		arg.EmailNormalized,
		arg.PasswordHash,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const inviteFindLivePendingByEmailForUpdate = `-- name: InviteFindLivePendingByEmailForUpdate :one
SELECT id, tenant_id, branch_id, email, email_normalized, role, token_hash, expires_at,
       accepted_at, accepted_user_id, accepted_membership_id,
       revoked_at, revoked_by_user_id, revoked_by_membership_id,
       created_by_user_id, created_by_membership_id,
       resent_at, resent_by_user_id, resent_by_membership_id,
       send_count, created_at, updated_at
FROM manager_invites
WHERE tenant_id = $1
  AND branch_id = $2
  AND email_normalized = $3
  AND accepted_at IS NULL
  AND revoked_at IS NULL
  AND expires_at > now()
FOR UPDATE
`

type InviteFindLivePendingByEmailForUpdateParams struct {
	TenantID        pgtype.UUID
	BranchID        pgtype.UUID
	EmailNormalized string
}

func (q *Queries) InviteFindLivePendingByEmailForUpdate(ctx context.Context, arg InviteFindLivePendingByEmailForUpdateParams) (ManagerInvite, error) {
	row := q.db.QueryRow(ctx, inviteFindLivePendingByEmailForUpdate, arg.TenantID, arg.BranchID, arg.EmailNormalized)
	var i ManagerInvite
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BranchID,
		&i.Email,
		&i.EmailNormalized,
		&i.Role,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedUserID,
		&i.AcceptedMembershipID,
		&i.RevokedAt,
		&i.RevokedByUserID,
		&i.RevokedByMembershipID,
		&i.CreatedByUserID,
		&i.CreatedByMembershipID,
		&i.ResentAt,
		&i.ResentByUserID,
		&i.ResentByMembershipID,
		&i.SendCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const inviteFindUserByEmailNormalized = `-- name: InviteFindUserByEmailNormalized :one
SELECT id
FROM users
WHERE email_normalized = $1
LIMIT 1
`

func (q *Queries) InviteFindUserByEmailNormalized(ctx context.Context, emailNormalized string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, inviteFindUserByEmailNormalized, emailNormalized)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const inviteGetByIDForUpdate = `-- name: InviteGetByIDForUpdate :one
SELECT id, tenant_id, branch_id, email, email_normalized, role, token_hash, expires_at,
       accepted_at, accepted_user_id, accepted_membership_id,
       revoked_at, revoked_by_user_id, revoked_by_membership_id,
       created_by_user_id, created_by_membership_id,
       resent_at, resent_by_user_id, resent_by_membership_id,
       send_count, created_at, updated_at
FROM manager_invites
WHERE id = $1
  AND tenant_id = $2
  AND branch_id = $3
FOR UPDATE
`

type InviteGetByIDForUpdateParams struct {
	ID       pgtype.UUID
	TenantID pgtype.UUID
	BranchID pgtype.UUID
}

func (q *Queries) InviteGetByIDForUpdate(ctx context.Context, arg InviteGetByIDForUpdateParams) (ManagerInvite, error) {
	row := q.db.QueryRow(ctx, inviteGetByIDForUpdate, arg.ID, arg.TenantID, arg.BranchID)
	var i ManagerInvite
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BranchID,
		&i.Email,
		&i.EmailNormalized,
		&i.Role,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedUserID,
		&i.AcceptedMembershipID,
		&i.RevokedAt,
		&i.RevokedByUserID,
		&i.RevokedByMembershipID,
		&i.CreatedByUserID,
		&i.CreatedByMembershipID,
		&i.ResentAt,
		&i.ResentByUserID,
		&i.ResentByMembershipID,
		&i.SendCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const inviteGetByTokenHashForUpdate = `-- name: InviteGetByTokenHashForUpdate :one
SELECT id, tenant_id, branch_id, email, email_normalized, role, token_hash, expires_at,
       accepted_at, accepted_user_id, accepted_membership_id,
       revoked_at, revoked_by_user_id, revoked_by_membership_id,
       created_by_user_id, created_by_membership_id,
       resent_at, resent_by_user_id, resent_by_membership_id,
       send_count, created_at, updated_at
FROM manager_invites
WHERE token_hash = $1
FOR UPDATE
`

func (q *Queries) InviteGetByTokenHashForUpdate(ctx context.Context, tokenHash string) (ManagerInvite, error) {
	row := q.db.QueryRow(ctx, inviteGetByTokenHashForUpdate, tokenHash)
	var i ManagerInvite
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BranchID,
		&i.Email,
		&i.EmailNormalized,
		&i.Role,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedUserID,
		&i.AcceptedMembershipID,
		&i.RevokedAt,
		&i.RevokedByUserID,
		&i.RevokedByMembershipID,
		&i.CreatedByUserID,
		&i.CreatedByMembershipID,
		&i.ResentAt,
		&i.ResentByUserID,
		&i.ResentByMembershipID,
		&i.SendCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const inviteListAccepted = `-- name: InviteListAccepted :many
SELECT id, tenant_id, branch_id, email, email_normalized, role, token_hash, expires_at,
       accepted_at, accepted_user_id, accepted_membership_id,
       revoked_at, revoked_by_user_id, revoked_by_membership_id,
       created_by_user_id, created_by_membership_id,
       resent_at, resent_by_user_id, resent_by_membership_id,
       send_count, created_at, updated_at
FROM manager_invites
WHERE tenant_id = $1
  AND branch_id = $2
  AND accepted_at IS NOT NULL
ORDER BY created_at DESC
`

type InviteListAcceptedParams struct {
	TenantID pgtype.UUID
	BranchID pgtype.UUID
}

func (q *Queries) InviteListAccepted(ctx context.Context, arg InviteListAcceptedParams) ([]ManagerInvite, error) {
	rows, err := q.db.Query(ctx, inviteListAccepted, arg.TenantID, arg.BranchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ManagerInvite
	for rows.Next() {
		var i ManagerInvite
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.BranchID,
			&i.Email,
			&i.EmailNormalized,
			&i.Role,
			&i.TokenHash,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.AcceptedUserID,
			&i.AcceptedMembershipID,
			&i.RevokedAt,
			&i.RevokedByUserID,
			&i.RevokedByMembershipID,
			&i.CreatedByUserID,
			&i.CreatedByMembershipID,
			&i.ResentAt,
			&i.ResentByUserID,
			&i.ResentByMembershipID,
			&i.SendCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const inviteListAll = `-- name: InviteListAll :many
SELECT id, tenant_id, branch_id, email, email_normalized, role, token_hash, expires_at,
       accepted_at, accepted_user_id, accepted_membership_id,
       revoked_at, revoked_by_user_id, revoked_by_membership_id,
       created_by_user_id, created_by_membership_id,
       resent_at, resent_by_user_id, resent_by_membership_id,
       send_count, created_at, updated_at
FROM manager_invites
WHERE tenant_id = $1
  AND branch_id = $2
ORDER BY created_at DESC
`

type InviteListAllParams struct {
	TenantID pgtype.UUID
	BranchID pgtype.UUID
}

func (q *Queries) InviteListAll(ctx context.Context, arg InviteListAllParams) ([]ManagerInvite, error) {
	rows, err := q.db.Query(ctx, inviteListAll, arg.TenantID, arg.BranchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ManagerInvite
	for rows.Next() {
		var i ManagerInvite
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.BranchID,
			&i.Email,
			&i.EmailNormalized,
			&i.Role,
			&i.TokenHash,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.AcceptedUserID,
			&i.AcceptedMembershipID,
			&i.RevokedAt,
			&i.RevokedByUserID,
			&i.RevokedByMembershipID,
			&i.CreatedByUserID,
			&i.CreatedByMembershipID,
			&i.ResentAt,
			&i.ResentByUserID,
			&i.ResentByMembershipID,
			&i.SendCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const inviteListExpired = `-- name: InviteListExpired :many
SELECT id, tenant_id, branch_id, email, email_normalized, role, token_hash, expires_at,
       accepted_at, accepted_user_id, accepted_membership_id,
       revoked_at, revoked_by_user_id, revoked_by_membership_id,
       created_by_user_id, created_by_membership_id,
       resent_at, resent_by_user_id, resent_by_membership_id,
       send_count, created_at, updated_at
FROM manager_invites
WHERE tenant_id = $1
  AND branch_id = $2
  AND accepted_at IS NULL
  AND revoked_at IS NULL
  AND expires_at <= now()
ORDER BY created_at DESC
`

type InviteListExpiredParams struct {
	TenantID pgtype.UUID
	BranchID pgtype.UUID
}

func (q *Queries) InviteListExpired(ctx context.Context, arg InviteListExpiredParams) ([]ManagerInvite, error) {
	rows, err := q.db.Query(ctx, inviteListExpired, arg.TenantID, arg.BranchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ManagerInvite
	for rows.Next() {
		var i ManagerInvite
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.BranchID,
			&i.Email,
			&i.EmailNormalized,
			&i.Role,
			&i.TokenHash,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.AcceptedUserID,
			&i.AcceptedMembershipID,
			&i.RevokedAt,
			&i.RevokedByUserID,
			&i.RevokedByMembershipID,
			&i.CreatedByUserID,
			&i.CreatedByMembershipID,
			&i.ResentAt,
			&i.ResentByUserID,
			&i.ResentByMembershipID,
			&i.SendCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const inviteListPending = `-- name: InviteListPending :many
SELECT id, tenant_id, branch_id, email, email_normalized, role, token_hash, expires_at,
       accepted_at, accepted_user_id, accepted_membership_id,
       revoked_at, revoked_by_user_id, revoked_by_membership_id,
       created_by_user_id, created_by_membership_id,
       resent_at, resent_by_user_id, resent_by_membership_id,
       send_count, created_at, updated_at
FROM manager_invites
WHERE tenant_id = $1
  AND branch_id = $2
  AND accepted_at IS NULL
  AND revoked_at IS NULL
  AND expires_at > now()
ORDER BY created_at DESC
`

type InviteListPendingParams struct {
	TenantID pgtype.UUID
	BranchID pgtype.UUID
}

func (q *Queries) InviteListPending(ctx context.Context, arg InviteListPendingParams) ([]ManagerInvite, error) {
	rows, err := q.db.Query(ctx, inviteListPending, arg.TenantID, arg.BranchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ManagerInvite
	for rows.Next() {
		var i ManagerInvite
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.BranchID,
			&i.Email,
			&i.EmailNormalized,
			&i.Role,
			&i.TokenHash,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.AcceptedUserID,
			&i.AcceptedMembershipID,
			&i.RevokedAt,
			&i.RevokedByUserID,
			&i.RevokedByMembershipID,
			&i.CreatedByUserID,
			&i.CreatedByMembershipID,
			&i.ResentAt,
			&i.ResentByUserID,
			&i.ResentByMembershipID,
			&i.SendCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const inviteListRevoked = `-- name: InviteListRevoked :many
SELECT id, tenant_id, branch_id, email, email_normalized, role, token_hash, expires_at,
       accepted_at, accepted_user_id, accepted_membership_id,
       revoked_at, revoked_by_user_id, revoked_by_membership_id,
       created_by_user_id, created_by_membership_id,
       resent_at, resent_by_user_id, resent_by_membership_id,
       send_count, created_at, updated_at
FROM manager_invites
WHERE tenant_id = $1
  AND branch_id = $2
  AND revoked_at IS NOT NULL
ORDER BY created_at DESC
`

type InviteListRevokedParams struct {
	TenantID pgtype.UUID
	BranchID pgtype.UUID
}

func (q *Queries) InviteListRevoked(ctx context.Context, arg InviteListRevokedParams) ([]ManagerInvite, error) {
	rows, err := q.db.Query(ctx, inviteListRevoked, arg.TenantID, arg.BranchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ManagerInvite
	for rows.Next() {
		var i ManagerInvite
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.BranchID,
			&i.Email,
			&i.EmailNormalized,
			&i.Role,
			&i.TokenHash,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.AcceptedUserID,
			&i.AcceptedMembershipID,
			&i.RevokedAt,
			&i.RevokedByUserID,
			&i.RevokedByMembershipID,
			&i.CreatedByUserID,
			&i.CreatedByMembershipID,
			&i.ResentAt,
			&i.ResentByUserID,
			&i.ResentByMembershipID,
			&i.SendCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const inviteRefreshPending = `-- name: InviteRefreshPending :exec
UPDATE manager_invites
SET token_hash = $2,
    expires_at = $3,
    resent_at = now(),
    resent_by_user_id = $4,
    resent_by_membership_id = $5,
    send_count = send_count + 1,
    updated_at = now()
WHERE id = $1
`

type InviteRefreshPendingParams struct {
	ID                   pgtype.UUID
	TokenHash            string
	ExpiresAt            pgtype.Timestamptz
	ResentByUserID       pgtype.UUID
	ResentByMembershipID pgtype.UUID
}

func (q *Queries) InviteRefreshPending(ctx context.Context, arg InviteRefreshPendingParams) error {
	_, err := q.db.Exec(ctx, inviteRefreshPending,
		arg.ID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.ResentByUserID,
		arg.ResentByMembershipID,
	)
	return err
}

const inviteRevoke = `-- name: InviteRevoke :exec
UPDATE manager_invites
SET revoked_at = now(),
    revoked_by_user_id = $2,
    revoked_by_membership_id = $3,
    updated_at = now()
WHERE id = $1
  AND accepted_at IS NULL
  AND revoked_at IS NULL
`

type InviteRevokeParams struct {
	ID                    pgtype.UUID
	RevokedByUserID       pgtype.UUID
	RevokedByMembershipID pgtype.UUID
}

func (q *Queries) InviteRevoke(ctx context.Context, arg InviteRevokeParams) error {
	_, err := q.db.Exec(ctx, inviteRevoke, arg.ID, arg.RevokedByUserID, arg.RevokedByMembershipID)
	return err
}
