// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AttendanceEvent struct {
	ID                     pgtype.UUID
	TenantID               pgtype.UUID
	BranchID               pgtype.UUID
	ChildID                pgtype.UUID
	SessionID              pgtype.UUID
	EventType              string
	OccurredAt             pgtype.Timestamptz
	LocalDate              pgtype.Date
	RecordedByUserID       pgtype.UUID
	RecordedByMembershipID pgtype.UUID
	RequestID              pgtype.Text
	ReasonCode             pgtype.Text
	ReasonNote             pgtype.Text
	Details                []byte
	CreatedAt              pgtype.Timestamptz
}

type AttendanceSession struct {
	ID                 pgtype.UUID
	TenantID           pgtype.UUID
	BranchID           pgtype.UUID
	ChildID            pgtype.UUID
	Status             string
	CheckInAt          pgtype.Timestamptz
	CheckOutAt         pgtype.Timestamptz
	CheckInLocalDate   pgtype.Date
	CheckOutLocalDate  pgtype.Date
	CheckInEventID     pgtype.UUID
	CheckOutEventID    pgtype.UUID
	CorrectedByEventID pgtype.UUID
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type AuditLog struct {
	ID                pgtype.UUID
	TenantID          pgtype.UUID
	BranchID          pgtype.UUID
	ActorUserID       pgtype.UUID
	ActionType        string
	ActionEntityType  string
	ActionEntityID    pgtype.UUID
	Reason            pgtype.Text
	Details           []byte
	CreatedAt         pgtype.Timestamptz
	RequestID         pgtype.Text
	ActorMembershipID pgtype.UUID
	ReasonCode        interface{}
	ReasonNote        pgtype.Text
}

type Branch struct {
	ID        pgtype.UUID
	TenantID  pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Child struct {
	ID                  pgtype.UUID
	TenantID            pgtype.UUID
	BranchID            pgtype.UUID
	FullName            string
	DateOfBirth         pgtype.Date
	StartDate           pgtype.Date
	EndDate             pgtype.Date
	CoreHourlyRateMinor int32
	IsActive            bool
	LeftAt              pgtype.Timestamptz
	Notes               pgtype.Text
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	LeftReasonCode      interface{}
	LeftReasonNote      pgtype.Text
}

type FundingProfile struct {
	ID                     pgtype.UUID
	TenantID               pgtype.UUID
	BranchID               pgtype.UUID
	ChildID                pgtype.UUID
	BillingMonth           pgtype.Date
	FundedAllowanceMinutes int32
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
}

type Guardian struct {
	ID                     pgtype.UUID
	TenantID               pgtype.UUID
	BranchID               pgtype.UUID
	FullName               string
	Email                  pgtype.Text
	Phone                  pgtype.Text
	Notes                  pgtype.Text
	IsActive               bool
	DeactivatedAt          pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	DeactivationReasonCode interface{}
	DeactivationReasonNote pgtype.Text
}

type GuardianChildLink struct {
	ID              pgtype.UUID
	TenantID        pgtype.UUID
	BranchID        pgtype.UUID
	GuardianID      pgtype.UUID
	ChildID         pgtype.UUID
	EndedAt         pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	EndedReasonCode interface{}
	EndedReasonNote pgtype.Text
}

type ManagerInvite struct {
	ID                    pgtype.UUID
	TenantID              pgtype.UUID
	BranchID              pgtype.UUID
	Email                 string
	EmailNormalized       string
	Role                  string
	TokenHash             string
	ExpiresAt             pgtype.Timestamptz
	AcceptedAt            pgtype.Timestamptz
	AcceptedUserID        pgtype.UUID
	AcceptedMembershipID  pgtype.UUID
	RevokedAt             pgtype.Timestamptz
	RevokedByUserID       pgtype.UUID
	RevokedByMembershipID pgtype.UUID
	CreatedByUserID       pgtype.UUID
	CreatedByMembershipID pgtype.UUID
	ResentAt              pgtype.Timestamptz
	ResentByUserID        pgtype.UUID
	ResentByMembershipID  pgtype.UUID
	SendCount             int32
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

type Membership struct {
	ID        pgtype.UUID
	TenantID  pgtype.UUID
	BranchID  pgtype.UUID
	UserID    pgtype.UUID
	Role      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	IsActive  bool
	EndedAt   pgtype.Timestamptz
}

type ParentMembershipGuardian struct {
	ID              pgtype.UUID
	TenantID        pgtype.UUID
	BranchID        pgtype.UUID
	MembershipID    pgtype.UUID
	GuardianID      pgtype.UUID
	EndedAt         pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	EndedReasonCode interface{}
	EndedReasonNote pgtype.Text
}

type PasswordResetToken struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	TokenHash    string
	ExpiresAt    pgtype.Timestamptz
	UsedAt       pgtype.Timestamptz
	SupersededAt pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type RefreshToken struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	TokenHash    string
	ExpiresAt    pgtype.Timestamptz
	RevokedAt    pgtype.Timestamptz
	UserAgent    pgtype.Text
	IpAddress    pgtype.Text
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	MembershipID pgtype.UUID
}

type Tenant struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type User struct {
	ID              pgtype.UUID
	Email           string
	EmailNormalized string
	PasswordHash    string
	IsActive        bool
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}
