// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AbsenceMarker struct {
	ID                    pgtype.UUID
	TenantID              pgtype.UUID
	BranchID              pgtype.UUID
	ChildID               pgtype.UUID
	LocalDate             pgtype.Date
	MarkedAt              pgtype.Timestamptz
	MarkedByUserID        pgtype.UUID
	MarkedByMembershipID  pgtype.UUID
	ClearedAt             pgtype.Timestamptz
	ClearedByUserID       pgtype.UUID
	ClearedByMembershipID pgtype.UUID
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

type AttendanceEvent struct {
	ID                     pgtype.UUID
	TenantID               pgtype.UUID
	BranchID               pgtype.UUID
	ChildID                pgtype.UUID
	SessionID              pgtype.UUID
	EventType              string
	OccurredAt             pgtype.Timestamptz
	LocalDate              pgtype.Date
	RecordedByUserID       pgtype.UUID
	RecordedByMembershipID pgtype.UUID
	RequestID              pgtype.Text
	ReasonCode             pgtype.Text
	ReasonNote             pgtype.Text
	Details                []byte
	CreatedAt              pgtype.Timestamptz
}

type AttendanceSession struct {
	ID                 pgtype.UUID
	TenantID           pgtype.UUID
	BranchID           pgtype.UUID
	ChildID            pgtype.UUID
	Status             string
	CheckInAt          pgtype.Timestamptz
	CheckOutAt         pgtype.Timestamptz
	CheckInLocalDate   pgtype.Date
	CheckOutLocalDate  pgtype.Date
	CheckInEventID     pgtype.UUID
	CheckOutEventID    pgtype.UUID
	CorrectedByEventID pgtype.UUID
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type AuditLog struct {
	ID                pgtype.UUID
	TenantID          pgtype.UUID
	BranchID          pgtype.UUID
	ActorUserID       pgtype.UUID
	ActionType        string
	ActionEntityType  string
	ActionEntityID    pgtype.UUID
	Reason            pgtype.Text
	Details           []byte
	CreatedAt         pgtype.Timestamptz
	RequestID         pgtype.Text
	ActorMembershipID pgtype.UUID
	ReasonCode        interface{}
	ReasonNote        pgtype.Text
}

type Branch struct {
	ID        pgtype.UUID
	TenantID  pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	IsActive  bool
}

type Child struct {
	ID                  pgtype.UUID
	TenantID            pgtype.UUID
	BranchID            pgtype.UUID
	FullName            string
	DateOfBirth         pgtype.Date
	StartDate           pgtype.Date
	EndDate             pgtype.Date
	CoreHourlyRateMinor int32
	IsActive            bool
	LeftAt              pgtype.Timestamptz
	Notes               pgtype.Text
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	LeftReasonCode      interface{}
	LeftReasonNote      pgtype.Text
}

type FundingProfile struct {
	ID                     pgtype.UUID
	TenantID               pgtype.UUID
	BranchID               pgtype.UUID
	ChildID                pgtype.UUID
	BillingMonth           pgtype.Date
	FundedAllowanceMinutes int32
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
}

type Guardian struct {
	ID                     pgtype.UUID
	TenantID               pgtype.UUID
	BranchID               pgtype.UUID
	FullName               string
	Email                  pgtype.Text
	Phone                  pgtype.Text
	Notes                  pgtype.Text
	IsActive               bool
	DeactivatedAt          pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	DeactivationReasonCode interface{}
	DeactivationReasonNote pgtype.Text
}

type GuardianChildLink struct {
	ID              pgtype.UUID
	TenantID        pgtype.UUID
	BranchID        pgtype.UUID
	GuardianID      pgtype.UUID
	ChildID         pgtype.UUID
	EndedAt         pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	EndedReasonCode interface{}
	EndedReasonNote pgtype.Text
}

type Invoice struct {
	ID                     pgtype.UUID
	TenantID               pgtype.UUID
	BranchID               pgtype.UUID
	ChildID                pgtype.UUID
	BillingMonth           pgtype.Date
	InvoiceKind            string
	Status                 string
	InvoiceNumber          pgtype.Text
	IssuedSequence         pgtype.Int4
	GeneratedRunID         pgtype.UUID
	IssuedRunID            pgtype.UUID
	IssuedAt               pgtype.Timestamptz
	IssuedByUserID         pgtype.UUID
	IssuedByMembershipID   pgtype.UUID
	LockedAt               pgtype.Timestamptz
	DueAt                  pgtype.Timestamptz
	CurrencyCode           string
	SubtotalMinor          int32
	FundedDeductionMinor   int32
	TotalDueMinor          int32
	AmountPaidMinor        int32
	PaidAt                 pgtype.Timestamptz
	PaymentFailedAt        pgtype.Timestamptz
	PaymentStatusUpdatedAt pgtype.Timestamptz
	AdjustsInvoiceID       pgtype.UUID
	AdjustmentReasonCode   pgtype.Text
	AdjustmentReasonNote   pgtype.Text
	PeriodStartDate        pgtype.Date
	PeriodEndDate          pgtype.Date
	CalculationDetails     []byte
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
}

type InvoiceLine struct {
	ID                     pgtype.UUID
	TenantID               pgtype.UUID
	BranchID               pgtype.UUID
	InvoiceID              pgtype.UUID
	LineKind               string
	Description            string
	SortOrder              int32
	QuantityMinutes        pgtype.Int4
	UnitAmountMinor        pgtype.Int4
	LineAmountMinor        int32
	RawAttendedMinutes     pgtype.Int4
	RoundedAttendedMinutes pgtype.Int4
	FundedAllowanceMinutes pgtype.Int4
	FundedDeductionMinutes pgtype.Int4
	CoreBillableMinutes    pgtype.Int4
	SessionCount           pgtype.Int4
	Details                []byte
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
}

type InvoiceNumberSequence struct {
	TenantID     pgtype.UUID
	BranchID     pgtype.UUID
	BillingYear  int32
	BillingMonth int32
	NextSequence int32
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type InvoiceRun struct {
	ID                      pgtype.UUID
	TenantID                pgtype.UUID
	BranchID                pgtype.UUID
	BillingMonth            pgtype.Date
	RunType                 string
	Status                  string
	StartedAt               pgtype.Timestamptz
	CompletedAt             pgtype.Timestamptz
	RequestedByUserID       pgtype.UUID
	RequestedByMembershipID pgtype.UUID
	RequestID               pgtype.Text
	EligibleCount           int32
	SuccessCount            int32
	BlockedCount            int32
	FailedCount             int32
	Details                 []byte
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
}

type ManagerInvite struct {
	ID                    pgtype.UUID
	TenantID              pgtype.UUID
	BranchID              pgtype.UUID
	Email                 string
	EmailNormalized       string
	Role                  string
	TokenHash             string
	ExpiresAt             pgtype.Timestamptz
	AcceptedAt            pgtype.Timestamptz
	AcceptedUserID        pgtype.UUID
	AcceptedMembershipID  pgtype.UUID
	RevokedAt             pgtype.Timestamptz
	RevokedByUserID       pgtype.UUID
	RevokedByMembershipID pgtype.UUID
	CreatedByUserID       pgtype.UUID
	CreatedByMembershipID pgtype.UUID
	ResentAt              pgtype.Timestamptz
	ResentByUserID        pgtype.UUID
	ResentByMembershipID  pgtype.UUID
	SendCount             int32
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

type Membership struct {
	ID        pgtype.UUID
	TenantID  pgtype.UUID
	BranchID  pgtype.UUID
	UserID    pgtype.UUID
	Role      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	IsActive  bool
	EndedAt   pgtype.Timestamptz
}

type ParentMembershipGuardian struct {
	ID              pgtype.UUID
	TenantID        pgtype.UUID
	BranchID        pgtype.UUID
	MembershipID    pgtype.UUID
	GuardianID      pgtype.UUID
	EndedAt         pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	EndedReasonCode interface{}
	EndedReasonNote pgtype.Text
}

type PasswordResetToken struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	TokenHash    string
	ExpiresAt    pgtype.Timestamptz
	UsedAt       pgtype.Timestamptz
	SupersededAt pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type PaymentAttempt struct {
	ID                      pgtype.UUID
	TenantID                pgtype.UUID
	BranchID                pgtype.UUID
	InvoiceID               pgtype.UUID
	InitiatedByUserID       pgtype.UUID
	InitiatedByMembershipID pgtype.UUID
	RequestID               pgtype.Text
	Status                  string
	AmountMinor             int32
	CurrencyCode            string
	StripeCheckoutSessionID pgtype.Text
	StripeCheckoutUrl       pgtype.Text
	StripePaymentIntentID   pgtype.Text
	StripeExpiresAt         pgtype.Timestamptz
	ProviderErrorCode       pgtype.Text
	ProviderErrorMessage    pgtype.Text
	FailureReason           pgtype.Text
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
}

type PaymentReconciliationRecord struct {
	ID                      pgtype.UUID
	TenantID                pgtype.UUID
	BranchID                pgtype.UUID
	InvoiceID               pgtype.UUID
	PaymentAttemptID        pgtype.UUID
	StripeWebhookEventID    pgtype.UUID
	StripeEventID           string
	StripeEventType         string
	StripeCheckoutSessionID string
	StripePaymentIntentID   pgtype.Text
	Outcome                 string
	ReasonCode              string
	PreviousInvoiceStatus   pgtype.Text
	NewInvoiceStatus        pgtype.Text
	AttemptPreviousStatus   pgtype.Text
	AttemptNewStatus        pgtype.Text
	AmountMinor             pgtype.Int4
	CurrencyCode            pgtype.Text
	Details                 []byte
	CreatedAt               pgtype.Timestamptz
}

type RefreshToken struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	TokenHash    string
	ExpiresAt    pgtype.Timestamptz
	RevokedAt    pgtype.Timestamptz
	UserAgent    pgtype.Text
	IpAddress    pgtype.Text
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	MembershipID pgtype.UUID
}

type StripeWebhookEvent struct {
	ID                pgtype.UUID
	StripeEventID     string
	EventType         string
	Livemode          bool
	ApiVersion        pgtype.Text
	ProviderCreatedAt pgtype.Timestamptz
	ReceivedAt        pgtype.Timestamptz
	ProcessedAt       pgtype.Timestamptz
	ProcessingStatus  string
	ProcessingReason  pgtype.Text
	RequestID         pgtype.Text
	RawPayload        []byte
	ErrorMessage      pgtype.Text
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type Tenant struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type User struct {
	ID              pgtype.UUID
	Email           string
	EmailNormalized string
	PasswordHash    string
	IsActive        bool
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}
