// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: owner.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const ownerCountActiveChildrenByBranches = `-- name: OwnerCountActiveChildrenByBranches :many

SELECT branch_id, COUNT(*)::int AS count
FROM children
WHERE tenant_id = $1
  AND branch_id = ANY($2::uuid[])
  AND is_active = true
GROUP BY branch_id
`

type OwnerCountActiveChildrenByBranchesParams struct {
	TenantID pgtype.UUID
	Column2  []pgtype.UUID
}

type OwnerCountActiveChildrenByBranchesRow struct {
	BranchID pgtype.UUID
	Count    int32
}

// ── Children ──────────────────────────────────────────────────────────────────
func (q *Queries) OwnerCountActiveChildrenByBranches(ctx context.Context, arg OwnerCountActiveChildrenByBranchesParams) ([]OwnerCountActiveChildrenByBranchesRow, error) {
	rows, err := q.db.Query(ctx, ownerCountActiveChildrenByBranches, arg.TenantID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OwnerCountActiveChildrenByBranchesRow
	for rows.Next() {
		var i OwnerCountActiveChildrenByBranchesRow
		if err := rows.Scan(&i.BranchID, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ownerCountActiveManagersByBranches = `-- name: OwnerCountActiveManagersByBranches :many

SELECT branch_id, COUNT(*)::int AS count
FROM memberships
WHERE tenant_id = $1
  AND branch_id = ANY($2::uuid[])
  AND role = 'manager'
  AND is_active = true
  AND ended_at IS NULL
GROUP BY branch_id
`

type OwnerCountActiveManagersByBranchesParams struct {
	TenantID pgtype.UUID
	Column2  []pgtype.UUID
}

type OwnerCountActiveManagersByBranchesRow struct {
	BranchID pgtype.UUID
	Count    int32
}

// ── Manager access status ────────────────────────────────────────────────────
func (q *Queries) OwnerCountActiveManagersByBranches(ctx context.Context, arg OwnerCountActiveManagersByBranchesParams) ([]OwnerCountActiveManagersByBranchesRow, error) {
	rows, err := q.db.Query(ctx, ownerCountActiveManagersByBranches, arg.TenantID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OwnerCountActiveManagersByBranchesRow
	for rows.Next() {
		var i OwnerCountActiveManagersByBranchesRow
		if err := rows.Scan(&i.BranchID, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ownerCountAttendanceTodayByBranches = `-- name: OwnerCountAttendanceTodayByBranches :many

SELECT branch_id,
       COUNT(DISTINCT child_id)::int AS checked_in_count
FROM attendance_sessions
WHERE tenant_id = $1
  AND branch_id = ANY($2::uuid[])
  AND status = 'open'
  AND check_in_local_date = $3
GROUP BY branch_id
`

type OwnerCountAttendanceTodayByBranchesParams struct {
	TenantID         pgtype.UUID
	Column2          []pgtype.UUID
	CheckInLocalDate pgtype.Date
}

type OwnerCountAttendanceTodayByBranchesRow struct {
	BranchID       pgtype.UUID
	CheckedInCount int32
}

// ── Attendance today ──────────────────────────────────────────────────────────
func (q *Queries) OwnerCountAttendanceTodayByBranches(ctx context.Context, arg OwnerCountAttendanceTodayByBranchesParams) ([]OwnerCountAttendanceTodayByBranchesRow, error) {
	rows, err := q.db.Query(ctx, ownerCountAttendanceTodayByBranches, arg.TenantID, arg.Column2, arg.CheckInLocalDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OwnerCountAttendanceTodayByBranchesRow
	for rows.Next() {
		var i OwnerCountAttendanceTodayByBranchesRow
		if err := rows.Scan(&i.BranchID, &i.CheckedInCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ownerCountIncompleteAttendanceByBranches = `-- name: OwnerCountIncompleteAttendanceByBranches :many
SELECT branch_id, COUNT(*)::int AS count
FROM attendance_sessions
WHERE tenant_id = $1
  AND branch_id = ANY($2::uuid[])
  AND status = 'open'
  AND check_in_local_date >= $3
  AND check_in_local_date < $4
GROUP BY branch_id
`

type OwnerCountIncompleteAttendanceByBranchesParams struct {
	TenantID           pgtype.UUID
	Column2            []pgtype.UUID
	CheckInLocalDate   pgtype.Date
	CheckInLocalDate_2 pgtype.Date
}

type OwnerCountIncompleteAttendanceByBranchesRow struct {
	BranchID pgtype.UUID
	Count    int32
}

func (q *Queries) OwnerCountIncompleteAttendanceByBranches(ctx context.Context, arg OwnerCountIncompleteAttendanceByBranchesParams) ([]OwnerCountIncompleteAttendanceByBranchesRow, error) {
	rows, err := q.db.Query(ctx, ownerCountIncompleteAttendanceByBranches,
		arg.TenantID,
		arg.Column2,
		arg.CheckInLocalDate,
		arg.CheckInLocalDate_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OwnerCountIncompleteAttendanceByBranchesRow
	for rows.Next() {
		var i OwnerCountIncompleteAttendanceByBranchesRow
		if err := rows.Scan(&i.BranchID, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ownerCountPendingManagerInvitesByBranches = `-- name: OwnerCountPendingManagerInvitesByBranches :many
SELECT branch_id, COUNT(*)::int AS count
FROM manager_invites
WHERE tenant_id = $1
  AND branch_id = ANY($2::uuid[])
  AND role = 'manager'
  AND accepted_at IS NULL
  AND revoked_at IS NULL
  AND expires_at > now()
GROUP BY branch_id
`

type OwnerCountPendingManagerInvitesByBranchesParams struct {
	TenantID pgtype.UUID
	Column2  []pgtype.UUID
}

type OwnerCountPendingManagerInvitesByBranchesRow struct {
	BranchID pgtype.UUID
	Count    int32
}

func (q *Queries) OwnerCountPendingManagerInvitesByBranches(ctx context.Context, arg OwnerCountPendingManagerInvitesByBranchesParams) ([]OwnerCountPendingManagerInvitesByBranchesRow, error) {
	rows, err := q.db.Query(ctx, ownerCountPendingManagerInvitesByBranches, arg.TenantID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OwnerCountPendingManagerInvitesByBranchesRow
	for rows.Next() {
		var i OwnerCountPendingManagerInvitesByBranchesRow
		if err := rows.Scan(&i.BranchID, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ownerCreateManagerInvite = `-- name: OwnerCreateManagerInvite :exec
INSERT INTO manager_invites (
    id, tenant_id, branch_id, email, email_normalized, role,
    token_hash, expires_at,
    created_by_user_id, created_by_membership_id
) VALUES ($1, $2, $3, $4, $5, 'manager', $6, $7, $8, $9)
`

type OwnerCreateManagerInviteParams struct {
	ID                    pgtype.UUID
	TenantID              pgtype.UUID
	BranchID              pgtype.UUID
	Email                 string
	EmailNormalized       string
	TokenHash             string
	ExpiresAt             pgtype.Timestamptz
	CreatedByUserID       pgtype.UUID
	CreatedByMembershipID pgtype.UUID
}

func (q *Queries) OwnerCreateManagerInvite(ctx context.Context, arg OwnerCreateManagerInviteParams) error {
	_, err := q.db.Exec(ctx, ownerCreateManagerInvite,
		arg.ID,
		arg.TenantID,
		arg.BranchID,
		arg.Email,
		arg.EmailNormalized,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.CreatedByUserID,
		arg.CreatedByMembershipID,
	)
	return err
}

const ownerCreateManagerMembership = `-- name: OwnerCreateManagerMembership :exec
INSERT INTO memberships (id, tenant_id, branch_id, user_id, role, is_active)
VALUES ($1, $2, $3, $4, 'manager', true)
`

type OwnerCreateManagerMembershipParams struct {
	ID       pgtype.UUID
	TenantID pgtype.UUID
	BranchID pgtype.UUID
	UserID   pgtype.UUID
}

func (q *Queries) OwnerCreateManagerMembership(ctx context.Context, arg OwnerCreateManagerMembershipParams) error {
	_, err := q.db.Exec(ctx, ownerCreateManagerMembership,
		arg.ID,
		arg.TenantID,
		arg.BranchID,
		arg.UserID,
	)
	return err
}

const ownerDeactivateManagerMembership = `-- name: OwnerDeactivateManagerMembership :execrows
UPDATE memberships
SET is_active = false,
    ended_at = now(),
    updated_at = now()
WHERE id = $1 AND tenant_id = $2 AND role = 'manager' AND is_active = true
`

type OwnerDeactivateManagerMembershipParams struct {
	ID       pgtype.UUID
	TenantID pgtype.UUID
}

func (q *Queries) OwnerDeactivateManagerMembership(ctx context.Context, arg OwnerDeactivateManagerMembershipParams) (int64, error) {
	result, err := q.db.Exec(ctx, ownerDeactivateManagerMembership, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const ownerFindActiveUserByEmail = `-- name: OwnerFindActiveUserByEmail :one

SELECT id, email, is_active
FROM users
WHERE email_normalized = $1 AND is_active = true
`

type OwnerFindActiveUserByEmailRow struct {
	ID       pgtype.UUID
	Email    string
	IsActive bool
}

// ── User lookup ───────────────────────────────────────────────────────────────
func (q *Queries) OwnerFindActiveUserByEmail(ctx context.Context, emailNormalized string) (OwnerFindActiveUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, ownerFindActiveUserByEmail, emailNormalized)
	var i OwnerFindActiveUserByEmailRow
	err := row.Scan(&i.ID, &i.Email, &i.IsActive)
	return i, err
}

const ownerFindManagerMembershipForUser = `-- name: OwnerFindManagerMembershipForUser :one

SELECT id, tenant_id, branch_id, user_id, role, is_active, ended_at
FROM memberships
WHERE tenant_id = $1
  AND branch_id = $2
  AND user_id = $3
  AND role = 'manager'
`

type OwnerFindManagerMembershipForUserParams struct {
	TenantID pgtype.UUID
	BranchID pgtype.UUID
	UserID   pgtype.UUID
}

type OwnerFindManagerMembershipForUserRow struct {
	ID       pgtype.UUID
	TenantID pgtype.UUID
	BranchID pgtype.UUID
	UserID   pgtype.UUID
	Role     string
	IsActive bool
	EndedAt  pgtype.Timestamptz
}

// ── Manager membership queries ────────────────────────────────────────────────
func (q *Queries) OwnerFindManagerMembershipForUser(ctx context.Context, arg OwnerFindManagerMembershipForUserParams) (OwnerFindManagerMembershipForUserRow, error) {
	row := q.db.QueryRow(ctx, ownerFindManagerMembershipForUser, arg.TenantID, arg.BranchID, arg.UserID)
	var i OwnerFindManagerMembershipForUserRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BranchID,
		&i.UserID,
		&i.Role,
		&i.IsActive,
		&i.EndedAt,
	)
	return i, err
}

const ownerFindPendingManagerInvite = `-- name: OwnerFindPendingManagerInvite :one

SELECT id, email, email_normalized, expires_at, send_count, created_at
FROM manager_invites
WHERE tenant_id = $1
  AND branch_id = $2
  AND email_normalized = $3
  AND role = 'manager'
  AND accepted_at IS NULL
  AND revoked_at IS NULL
  AND expires_at > now()
`

type OwnerFindPendingManagerInviteParams struct {
	TenantID        pgtype.UUID
	BranchID        pgtype.UUID
	EmailNormalized string
}

type OwnerFindPendingManagerInviteRow struct {
	ID              pgtype.UUID
	Email           string
	EmailNormalized string
	ExpiresAt       pgtype.Timestamptz
	SendCount       int32
	CreatedAt       pgtype.Timestamptz
}

// ── Manager invite queries ────────────────────────────────────────────────────
func (q *Queries) OwnerFindPendingManagerInvite(ctx context.Context, arg OwnerFindPendingManagerInviteParams) (OwnerFindPendingManagerInviteRow, error) {
	row := q.db.QueryRow(ctx, ownerFindPendingManagerInvite, arg.TenantID, arg.BranchID, arg.EmailNormalized)
	var i OwnerFindPendingManagerInviteRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailNormalized,
		&i.ExpiresAt,
		&i.SendCount,
		&i.CreatedAt,
	)
	return i, err
}

const ownerGetActiveSite = `-- name: OwnerGetActiveSite :one
SELECT id, name, core_hourly_rate_minor
FROM branches
WHERE tenant_id = $1 AND id = $2 AND is_active = true
`

type OwnerGetActiveSiteParams struct {
	TenantID pgtype.UUID
	ID       pgtype.UUID
}

type OwnerGetActiveSiteRow struct {
	ID                  pgtype.UUID
	Name                string
	CoreHourlyRateMinor pgtype.Int4
}

func (q *Queries) OwnerGetActiveSite(ctx context.Context, arg OwnerGetActiveSiteParams) (OwnerGetActiveSiteRow, error) {
	row := q.db.QueryRow(ctx, ownerGetActiveSite, arg.TenantID, arg.ID)
	var i OwnerGetActiveSiteRow
	err := row.Scan(&i.ID, &i.Name, &i.CoreHourlyRateMinor)
	return i, err
}

const ownerGetActiveSites = `-- name: OwnerGetActiveSites :many


SELECT id, name, core_hourly_rate_minor
FROM branches
WHERE tenant_id = $1 AND is_active = true
ORDER BY name
`

type OwnerGetActiveSitesRow struct {
	ID                  pgtype.UUID
	Name                string
	CoreHourlyRateMinor pgtype.Int4
}

// Owner module queries: site summaries and manager-access administration.
// All aggregate queries return counts only; no named records or operational identifiers.
// ── Site lookups ──────────────────────────────────────────────────────────────
func (q *Queries) OwnerGetActiveSites(ctx context.Context, tenantID pgtype.UUID) ([]OwnerGetActiveSitesRow, error) {
	rows, err := q.db.Query(ctx, ownerGetActiveSites, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OwnerGetActiveSitesRow
	for rows.Next() {
		var i OwnerGetActiveSitesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.CoreHourlyRateMinor); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ownerGetFundingReadinessByBranches = `-- name: OwnerGetFundingReadinessByBranches :many

SELECT c.branch_id,
       COUNT(*)::int AS included_child_count,
       COUNT(*) FILTER (WHERE fp.id IS NULL)::int AS missing_profile_count,
       COUNT(*) FILTER (WHERE fp.funded_allowance_minutes = 0)::int AS explicit_zero_count,
       COUNT(*) FILTER (WHERE fp.funded_allowance_minutes > 0 AND fp.funded_allowance_minutes < 60)::int AS under_one_hour_count,
       COUNT(*) FILTER (WHERE fp.funded_allowance_minutes > 9600)::int AS above_160_hours_count
FROM children c
LEFT JOIN funding_profiles fp
  ON fp.tenant_id = c.tenant_id
  AND fp.branch_id = c.branch_id
  AND fp.child_id = c.id
  AND fp.billing_month = $3
WHERE c.tenant_id = $1
  AND c.branch_id = ANY($2::uuid[])
  AND c.is_active = true
  AND c.start_date < ($3 + INTERVAL '1 month')::date
  AND (c.end_date IS NULL OR c.end_date >= $3)
GROUP BY c.branch_id
`

type OwnerGetFundingReadinessByBranchesParams struct {
	TenantID     pgtype.UUID
	Column2      []pgtype.UUID
	BillingMonth pgtype.Date
}

type OwnerGetFundingReadinessByBranchesRow struct {
	BranchID            pgtype.UUID
	IncludedChildCount  int32
	MissingProfileCount int32
	ExplicitZeroCount   int32
	UnderOneHourCount   int32
	Above160HoursCount  int32
}

// ── Funding readiness ─────────────────────────────────────────────────────────
func (q *Queries) OwnerGetFundingReadinessByBranches(ctx context.Context, arg OwnerGetFundingReadinessByBranchesParams) ([]OwnerGetFundingReadinessByBranchesRow, error) {
	rows, err := q.db.Query(ctx, ownerGetFundingReadinessByBranches, arg.TenantID, arg.Column2, arg.BillingMonth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OwnerGetFundingReadinessByBranchesRow
	for rows.Next() {
		var i OwnerGetFundingReadinessByBranchesRow
		if err := rows.Scan(
			&i.BranchID,
			&i.IncludedChildCount,
			&i.MissingProfileCount,
			&i.ExplicitZeroCount,
			&i.UnderOneHourCount,
			&i.Above160HoursCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ownerGetInvoicePaymentHealthByBranches = `-- name: OwnerGetInvoicePaymentHealthByBranches :many

SELECT branch_id,
       currency_code,
       COUNT(*) FILTER (WHERE status = 'draft')::int AS draft_count,
       COUNT(*) FILTER (WHERE status = 'issued')::int AS issued_count,
       COUNT(*) FILTER (WHERE status = 'overdue')::int AS overdue_count,
       COUNT(*) FILTER (WHERE status = 'payment_failed')::int AS payment_failed_count,
       COUNT(*) FILTER (WHERE status = 'paid')::int AS paid_count,
       COALESCE(SUM(total_due_minor) FILTER (WHERE status IN ('issued', 'overdue')), 0)::bigint AS total_issued_minor,
       COALESCE(SUM(amount_paid_minor) FILTER (WHERE status = 'paid'), 0)::bigint AS total_paid_minor,
       COALESCE(SUM(total_due_minor - amount_paid_minor) FILTER (WHERE status IN ('issued', 'overdue')), 0)::bigint AS outstanding_minor,
       COALESCE(SUM(total_due_minor - amount_paid_minor) FILTER (WHERE status = 'overdue'), 0)::bigint AS overdue_outstanding_minor
FROM invoices
WHERE tenant_id = $1
  AND branch_id = ANY($2::uuid[])
  AND billing_month = $3
GROUP BY branch_id, currency_code
`

type OwnerGetInvoicePaymentHealthByBranchesParams struct {
	TenantID     pgtype.UUID
	Column2      []pgtype.UUID
	BillingMonth pgtype.Date
}

type OwnerGetInvoicePaymentHealthByBranchesRow struct {
	BranchID                pgtype.UUID
	CurrencyCode            string
	DraftCount              int32
	IssuedCount             int32
	OverdueCount            int32
	PaymentFailedCount      int32
	PaidCount               int32
	TotalIssuedMinor        int64
	TotalPaidMinor          int64
	OutstandingMinor        int64
	OverdueOutstandingMinor int64
}

// ── Invoice / payment health ──────────────────────────────────────────────────
func (q *Queries) OwnerGetInvoicePaymentHealthByBranches(ctx context.Context, arg OwnerGetInvoicePaymentHealthByBranchesParams) ([]OwnerGetInvoicePaymentHealthByBranchesRow, error) {
	rows, err := q.db.Query(ctx, ownerGetInvoicePaymentHealthByBranches, arg.TenantID, arg.Column2, arg.BillingMonth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OwnerGetInvoicePaymentHealthByBranchesRow
	for rows.Next() {
		var i OwnerGetInvoicePaymentHealthByBranchesRow
		if err := rows.Scan(
			&i.BranchID,
			&i.CurrencyCode,
			&i.DraftCount,
			&i.IssuedCount,
			&i.OverdueCount,
			&i.PaymentFailedCount,
			&i.PaidCount,
			&i.TotalIssuedMinor,
			&i.TotalPaidMinor,
			&i.OutstandingMinor,
			&i.OverdueOutstandingMinor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ownerListManagerAccess = `-- name: OwnerListManagerAccess :many

SELECT m.id AS membership_id,
       m.user_id,
       u.email,
       m.is_active,
       m.ended_at
FROM memberships m
JOIN users u ON u.id = m.user_id
WHERE m.tenant_id = $1
  AND m.branch_id = $2
  AND m.role = 'manager'
  AND (
      $3 = 'all'
      OR ($3 = 'active' AND m.is_active = true AND m.ended_at IS NULL)
      OR ($3 = 'inactive' AND m.is_active = false)
  )
ORDER BY u.email
`

type OwnerListManagerAccessParams struct {
	TenantID     pgtype.UUID
	BranchID     pgtype.UUID
	StatusFilter interface{}
}

type OwnerListManagerAccessRow struct {
	MembershipID pgtype.UUID
	UserID       pgtype.UUID
	Email        string
	IsActive     bool
	EndedAt      pgtype.Timestamptz
}

// ── Manager access listing ────────────────────────────────────────────────────
func (q *Queries) OwnerListManagerAccess(ctx context.Context, arg OwnerListManagerAccessParams) ([]OwnerListManagerAccessRow, error) {
	rows, err := q.db.Query(ctx, ownerListManagerAccess, arg.TenantID, arg.BranchID, arg.StatusFilter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OwnerListManagerAccessRow
	for rows.Next() {
		var i OwnerListManagerAccessRow
		if err := rows.Scan(
			&i.MembershipID,
			&i.UserID,
			&i.Email,
			&i.IsActive,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ownerReactivateManagerMembership = `-- name: OwnerReactivateManagerMembership :exec
UPDATE memberships
SET is_active = true,
    ended_at = NULL,
    updated_at = now()
WHERE id = $1 AND tenant_id = $2 AND role = 'manager'
`

type OwnerReactivateManagerMembershipParams struct {
	ID       pgtype.UUID
	TenantID pgtype.UUID
}

func (q *Queries) OwnerReactivateManagerMembership(ctx context.Context, arg OwnerReactivateManagerMembershipParams) error {
	_, err := q.db.Exec(ctx, ownerReactivateManagerMembership, arg.ID, arg.TenantID)
	return err
}

const ownerRefreshManagerInvite = `-- name: OwnerRefreshManagerInvite :exec
UPDATE manager_invites
SET token_hash = $2,
    expires_at = $3,
    resent_at = now(),
    resent_by_user_id = $4,
    resent_by_membership_id = $5,
    send_count = send_count + 1,
    updated_at = now()
WHERE id = $1
`

type OwnerRefreshManagerInviteParams struct {
	ID                   pgtype.UUID
	TokenHash            string
	ExpiresAt            pgtype.Timestamptz
	ResentByUserID       pgtype.UUID
	ResentByMembershipID pgtype.UUID
}

func (q *Queries) OwnerRefreshManagerInvite(ctx context.Context, arg OwnerRefreshManagerInviteParams) error {
	_, err := q.db.Exec(ctx, ownerRefreshManagerInvite,
		arg.ID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.ResentByUserID,
		arg.ResentByMembershipID,
	)
	return err
}

const ownerRevokeRefreshTokensByMembership = `-- name: OwnerRevokeRefreshTokensByMembership :exec

UPDATE refresh_tokens
SET revoked_at = now(), updated_at = now()
WHERE membership_id = $1 AND revoked_at IS NULL
`

// ── Refresh token revocation ──────────────────────────────────────────────────
func (q *Queries) OwnerRevokeRefreshTokensByMembership(ctx context.Context, membershipID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, ownerRevokeRefreshTokensByMembership, membershipID)
	return err
}
