// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: parent_membership_children.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const parentChildMappingsCreate = `-- name: ParentChildMappingsCreate :exec
INSERT INTO parent_membership_children (id, tenant_id, branch_id, membership_id, child_id)
VALUES ($1, $2, $3, $4, $5)
`

type ParentChildMappingsCreateParams struct {
	ID           pgtype.UUID
	TenantID     pgtype.UUID
	BranchID     pgtype.UUID
	MembershipID pgtype.UUID
	ChildID      pgtype.UUID
}

func (q *Queries) ParentChildMappingsCreate(ctx context.Context, arg ParentChildMappingsCreateParams) error {
	_, err := q.db.Exec(ctx, parentChildMappingsCreate,
		arg.ID,
		arg.TenantID,
		arg.BranchID,
		arg.MembershipID,
		arg.ChildID,
	)
	return err
}

const parentChildMappingsEnd = `-- name: ParentChildMappingsEnd :exec
UPDATE parent_membership_children
SET ended_at = now(),
    ended_reason_code = $1,
    ended_reason_note = NULLIF($2, ''),
    updated_at = now()
WHERE tenant_id = $3
  AND branch_id = $4
  AND id = $5
  AND ended_at IS NULL
`

type ParentChildMappingsEndParams struct {
	EndedReasonCode NullLifecycleReasonCode
	Column2         interface{}
	TenantID        pgtype.UUID
	BranchID        pgtype.UUID
	ID              pgtype.UUID
}

func (q *Queries) ParentChildMappingsEnd(ctx context.Context, arg ParentChildMappingsEndParams) error {
	_, err := q.db.Exec(ctx, parentChildMappingsEnd,
		arg.EndedReasonCode,
		arg.Column2,
		arg.TenantID,
		arg.BranchID,
		arg.ID,
	)
	return err
}

const parentChildMappingsFindActiveByPair = `-- name: ParentChildMappingsFindActiveByPair :one
SELECT id, membership_id, child_id, ended_at,
       COALESCE(ended_reason_code::text, '') AS ended_reason_code,
       ended_reason_note, created_at, updated_at
FROM parent_membership_children
WHERE tenant_id = $1
  AND branch_id = $2
  AND membership_id = $3
  AND child_id = $4
  AND ended_at IS NULL
LIMIT 1
`

type ParentChildMappingsFindActiveByPairParams struct {
	TenantID     pgtype.UUID
	BranchID     pgtype.UUID
	MembershipID pgtype.UUID
	ChildID      pgtype.UUID
}

type ParentChildMappingsFindActiveByPairRow struct {
	ID              pgtype.UUID
	MembershipID    pgtype.UUID
	ChildID         pgtype.UUID
	EndedAt         pgtype.Timestamptz
	EndedReasonCode interface{}
	EndedReasonNote pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) ParentChildMappingsFindActiveByPair(ctx context.Context, arg ParentChildMappingsFindActiveByPairParams) (ParentChildMappingsFindActiveByPairRow, error) {
	row := q.db.QueryRow(ctx, parentChildMappingsFindActiveByPair,
		arg.TenantID,
		arg.BranchID,
		arg.MembershipID,
		arg.ChildID,
	)
	var i ParentChildMappingsFindActiveByPairRow
	err := row.Scan(
		&i.ID,
		&i.MembershipID,
		&i.ChildID,
		&i.EndedAt,
		&i.EndedReasonCode,
		&i.EndedReasonNote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const parentChildMappingsGetByIDForUpdate = `-- name: ParentChildMappingsGetByIDForUpdate :one
SELECT id, membership_id, child_id, ended_at,
       COALESCE(ended_reason_code::text, '') AS ended_reason_code,
       ended_reason_note, created_at, updated_at
FROM parent_membership_children
WHERE tenant_id = $1
  AND branch_id = $2
  AND id = $3
FOR UPDATE
`

type ParentChildMappingsGetByIDForUpdateParams struct {
	TenantID pgtype.UUID
	BranchID pgtype.UUID
	ID       pgtype.UUID
}

type ParentChildMappingsGetByIDForUpdateRow struct {
	ID              pgtype.UUID
	MembershipID    pgtype.UUID
	ChildID         pgtype.UUID
	EndedAt         pgtype.Timestamptz
	EndedReasonCode interface{}
	EndedReasonNote pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) ParentChildMappingsGetByIDForUpdate(ctx context.Context, arg ParentChildMappingsGetByIDForUpdateParams) (ParentChildMappingsGetByIDForUpdateRow, error) {
	row := q.db.QueryRow(ctx, parentChildMappingsGetByIDForUpdate, arg.TenantID, arg.BranchID, arg.ID)
	var i ParentChildMappingsGetByIDForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.MembershipID,
		&i.ChildID,
		&i.EndedAt,
		&i.EndedReasonCode,
		&i.EndedReasonNote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const parentChildMappingsGetMembershipForScope = `-- name: ParentChildMappingsGetMembershipForScope :one
SELECT id, role, is_active
FROM memberships
WHERE tenant_id = $1
  AND branch_id = $2
  AND id = $3
`

type ParentChildMappingsGetMembershipForScopeParams struct {
	TenantID pgtype.UUID
	BranchID pgtype.UUID
	ID       pgtype.UUID
}

type ParentChildMappingsGetMembershipForScopeRow struct {
	ID       pgtype.UUID
	Role     string
	IsActive bool
}

func (q *Queries) ParentChildMappingsGetMembershipForScope(ctx context.Context, arg ParentChildMappingsGetMembershipForScopeParams) (ParentChildMappingsGetMembershipForScopeRow, error) {
	row := q.db.QueryRow(ctx, parentChildMappingsGetMembershipForScope, arg.TenantID, arg.BranchID, arg.ID)
	var i ParentChildMappingsGetMembershipForScopeRow
	err := row.Scan(&i.ID, &i.Role, &i.IsActive)
	return i, err
}

const parentChildMappingsListActiveByMembership = `-- name: ParentChildMappingsListActiveByMembership :many
SELECT id, membership_id, child_id, ended_at,
       COALESCE(ended_reason_code::text, '') AS ended_reason_code,
       ended_reason_note, created_at, updated_at
FROM parent_membership_children
WHERE tenant_id = $1
  AND branch_id = $2
  AND membership_id = $3
  AND ended_at IS NULL
ORDER BY created_at ASC
`

type ParentChildMappingsListActiveByMembershipParams struct {
	TenantID     pgtype.UUID
	BranchID     pgtype.UUID
	MembershipID pgtype.UUID
}

type ParentChildMappingsListActiveByMembershipRow struct {
	ID              pgtype.UUID
	MembershipID    pgtype.UUID
	ChildID         pgtype.UUID
	EndedAt         pgtype.Timestamptz
	EndedReasonCode interface{}
	EndedReasonNote pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) ParentChildMappingsListActiveByMembership(ctx context.Context, arg ParentChildMappingsListActiveByMembershipParams) ([]ParentChildMappingsListActiveByMembershipRow, error) {
	rows, err := q.db.Query(ctx, parentChildMappingsListActiveByMembership, arg.TenantID, arg.BranchID, arg.MembershipID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ParentChildMappingsListActiveByMembershipRow
	for rows.Next() {
		var i ParentChildMappingsListActiveByMembershipRow
		if err := rows.Scan(
			&i.ID,
			&i.MembershipID,
			&i.ChildID,
			&i.EndedAt,
			&i.EndedReasonCode,
			&i.EndedReasonNote,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
