// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment_links.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPaymentLink = `-- name: CreatePaymentLink :exec
INSERT INTO payment_links (
    id,
    tenant_id,
    branch_id,
    invoice_id,
    stripe_payment_link_id,
    stripe_payment_link_url,
    amount_minor,
    currency_code,
    created_by_user_id,
    created_by_membership_id,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
`

type CreatePaymentLinkParams struct {
	ID                    pgtype.UUID
	TenantID              pgtype.UUID
	BranchID              pgtype.UUID
	InvoiceID             pgtype.UUID
	StripePaymentLinkID   string
	StripePaymentLinkUrl  string
	AmountMinor           int32
	CurrencyCode          string
	CreatedByUserID       pgtype.UUID
	CreatedByMembershipID pgtype.UUID
	Status                string
}

func (q *Queries) CreatePaymentLink(ctx context.Context, arg CreatePaymentLinkParams) error {
	_, err := q.db.Exec(ctx, createPaymentLink,
		arg.ID,
		arg.TenantID,
		arg.BranchID,
		arg.InvoiceID,
		arg.StripePaymentLinkID,
		arg.StripePaymentLinkUrl,
		arg.AmountMinor,
		arg.CurrencyCode,
		arg.CreatedByUserID,
		arg.CreatedByMembershipID,
		arg.Status,
	)
	return err
}

const getActivePaymentLinkForInvoice = `-- name: GetActivePaymentLinkForInvoice :one
SELECT
    id,
    tenant_id,
    branch_id,
    invoice_id,
    stripe_payment_link_id,
    stripe_payment_link_url,
    amount_minor,
    currency_code,
    created_by_user_id,
    created_by_membership_id,
    status,
    created_at,
    updated_at
FROM payment_links
WHERE tenant_id = $1
  AND branch_id = $2
  AND invoice_id = $3
  AND status = 'active'
LIMIT 1
`

type GetActivePaymentLinkForInvoiceParams struct {
	TenantID  pgtype.UUID
	BranchID  pgtype.UUID
	InvoiceID pgtype.UUID
}

func (q *Queries) GetActivePaymentLinkForInvoice(ctx context.Context, arg GetActivePaymentLinkForInvoiceParams) (PaymentLink, error) {
	row := q.db.QueryRow(ctx, getActivePaymentLinkForInvoice, arg.TenantID, arg.BranchID, arg.InvoiceID)
	var i PaymentLink
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BranchID,
		&i.InvoiceID,
		&i.StripePaymentLinkID,
		&i.StripePaymentLinkUrl,
		&i.AmountMinor,
		&i.CurrencyCode,
		&i.CreatedByUserID,
		&i.CreatedByMembershipID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
