// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: registration_profiles.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const registrationProfileChildGet = `-- name: RegistrationProfileChildGet :one
SELECT
    c.id,
    c.first_name,
    c.middle_name,
    c.last_name,
    c.date_of_birth
FROM children c
WHERE c.tenant_id = $1
  AND c.branch_id = $2
  AND c.id = $3
`

type RegistrationProfileChildGetParams struct {
	TenantID pgtype.UUID
	BranchID pgtype.UUID
	ID       pgtype.UUID
}

type RegistrationProfileChildGetRow struct {
	ID          pgtype.UUID
	FirstName   string
	MiddleName  pgtype.Text
	LastName    pgtype.Text
	DateOfBirth pgtype.Date
}

func (q *Queries) RegistrationProfileChildGet(ctx context.Context, arg RegistrationProfileChildGetParams) (RegistrationProfileChildGetRow, error) {
	row := q.db.QueryRow(ctx, registrationProfileChildGet, arg.TenantID, arg.BranchID, arg.ID)
	var i RegistrationProfileChildGetRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.MiddleName,
		&i.LastName,
		&i.DateOfBirth,
	)
	return i, err
}

const registrationProfileCreate = `-- name: RegistrationProfileCreate :one
INSERT INTO child_registration_profiles (
    id, tenant_id, branch_id, child_id,
    sex, religion, ethnic_origin, first_language, other_languages,
    home_address, home_postcode, home_telephone,
    disability_status, disability_notes, access_requirements,
    medical_conditions_status, medical_conditions_notes,
    prescribed_medication_status, medication_notes,
    immunisation_status, immunisation_country, illness_diagnosis_history,
    dietary_requirements_status, dietary_requirements_notes, dietary_side_effects,
    doctor_name, doctor_address, doctor_phone,
    health_visitor_name, health_visitor_address, health_visitor_phone,
    social_services_status, social_services_notes,
    social_worker_name, social_worker_phone, social_worker_email,
    concern_walking, concern_speech_language, concern_hearing, concern_sight,
    concern_emotional_wellbeing, concern_behaviour, professional_referrals,
    parental_responsibility_notes,
    over18_collection_acknowledged,
    benefits_contribute_to_fees, working_tax_credit,
    college_uni_paid_to_parent, college_uni_paid_to_nursery,
    funding_3yo_term_time, funding_2yo_term_time, funding_support_notes,
    routine_care_notes,
    gdpr_declared_by_name, gdpr_declared_at, gdpr_declaration_date,
    demographics_home_reviewed, medical_dietary_reviewed, health_contacts_reviewed,
    social_development_reviewed, parent_responsibility_reviewed,
    emergency_collection_reviewed, funding_support_reviewed, routine_care_reviewed
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8, $9,
    $10, $11, $12,
    $13, $14, $15,
    $16, $17,
    $18, $19,
    $20, $21, $22,
    $23, $24, $25,
    $26, $27, $28,
    $29, $30, $31,
    $32, $33,
    $34, $35, $36,
    $37, $38, $39, $40,
    $41, $42, $43,
    $44,
    $45,
    $46, $47,
    $48, $49,
    $50, $51, $52,
    $53,
    $54, $55, $56,
    $57, $58, $59,
    $60, $61,
    $62, $63, $64
)
RETURNING
    id, tenant_id, branch_id, child_id,
    sex, religion, ethnic_origin, first_language, other_languages,
    home_address, home_postcode, home_telephone,
    disability_status::text, disability_notes, access_requirements,
    medical_conditions_status::text, medical_conditions_notes,
    prescribed_medication_status::text, medication_notes,
    immunisation_status::text, immunisation_country, illness_diagnosis_history,
    dietary_requirements_status::text, dietary_requirements_notes, dietary_side_effects,
    doctor_name, doctor_address, doctor_phone,
    health_visitor_name, health_visitor_address, health_visitor_phone,
    social_services_status::text, social_services_notes,
    social_worker_name, social_worker_phone, social_worker_email,
    concern_walking::text, concern_speech_language::text, concern_hearing::text, concern_sight::text,
    concern_emotional_wellbeing::text, concern_behaviour::text, professional_referrals,
    parental_responsibility_notes,
    over18_collection_acknowledged,
    FALSE AS collection_password_is_set,
    NULL::timestamptz AS collection_password_updated_at,
    NULL::uuid AS collection_password_updated_by_user_id,
    NULL::uuid AS collection_password_updated_by_membership_id,
    benefits_contribute_to_fees::text, working_tax_credit::text,
    college_uni_paid_to_parent::text, college_uni_paid_to_nursery::text,
    funding_3yo_term_time::text, funding_2yo_term_time::text, funding_support_notes,
    routine_care_notes,
    gdpr_declared_by_name, gdpr_declared_at, gdpr_declaration_date,
    demographics_home_reviewed, medical_dietary_reviewed, health_contacts_reviewed,
    social_development_reviewed, parent_responsibility_reviewed,
    emergency_collection_reviewed, funding_support_reviewed, routine_care_reviewed,
    created_at, updated_at
`

type RegistrationProfileCreateParams struct {
	ID                           pgtype.UUID
	TenantID                     pgtype.UUID
	BranchID                     pgtype.UUID
	ChildID                      pgtype.UUID
	Sex                          pgtype.Text
	Religion                     pgtype.Text
	EthnicOrigin                 pgtype.Text
	FirstLanguage                pgtype.Text
	OtherLanguages               pgtype.Text
	HomeAddress                  []byte
	HomePostcode                 pgtype.Text
	HomeTelephone                pgtype.Text
	DisabilityStatus             RegistrationYesNoUnknown
	DisabilityNotes              pgtype.Text
	AccessRequirements           pgtype.Text
	MedicalConditionsStatus      RegistrationYesNoUnknown
	MedicalConditionsNotes       pgtype.Text
	PrescribedMedicationStatus   RegistrationYesNoUnknown
	MedicationNotes              pgtype.Text
	ImmunisationStatus           RegistrationImmunisationStatus
	ImmunisationCountry          pgtype.Text
	IllnessDiagnosisHistory      pgtype.Text
	DietaryRequirementsStatus    RegistrationYesNoUnknown
	DietaryRequirementsNotes     pgtype.Text
	DietarySideEffects           pgtype.Text
	DoctorName                   pgtype.Text
	DoctorAddress                pgtype.Text
	DoctorPhone                  pgtype.Text
	HealthVisitorName            pgtype.Text
	HealthVisitorAddress         pgtype.Text
	HealthVisitorPhone           pgtype.Text
	SocialServicesStatus         RegistrationYesNoUnknown
	SocialServicesNotes          pgtype.Text
	SocialWorkerName             pgtype.Text
	SocialWorkerPhone            pgtype.Text
	SocialWorkerEmail            pgtype.Text
	ConcernWalking               RegistrationYesNoUnknown
	ConcernSpeechLanguage        RegistrationYesNoUnknown
	ConcernHearing               RegistrationYesNoUnknown
	ConcernSight                 RegistrationYesNoUnknown
	ConcernEmotionalWellbeing    RegistrationYesNoUnknown
	ConcernBehaviour             RegistrationYesNoUnknown
	ProfessionalReferrals        []byte
	ParentalResponsibilityNotes  pgtype.Text
	Over18CollectionAcknowledged bool
	BenefitsContributeToFees     RegistrationYesNoUnknown
	WorkingTaxCredit             RegistrationYesNoUnknown
	CollegeUniPaidToParent       RegistrationYesNoUnknown
	CollegeUniPaidToNursery      RegistrationYesNoUnknown
	Funding3yoTermTime           RegistrationYesNoUnknown
	Funding2yoTermTime           RegistrationYesNoUnknown
	FundingSupportNotes          pgtype.Text
	RoutineCareNotes             pgtype.Text
	GdprDeclaredByName           pgtype.Text
	GdprDeclaredAt               pgtype.Timestamptz
	GdprDeclarationDate          pgtype.Date
	DemographicsHomeReviewed     bool
	MedicalDietaryReviewed       bool
	HealthContactsReviewed       bool
	SocialDevelopmentReviewed    bool
	ParentResponsibilityReviewed bool
	EmergencyCollectionReviewed  bool
	FundingSupportReviewed       bool
	RoutineCareReviewed          bool
}

type RegistrationProfileCreateRow struct {
	ID                                      pgtype.UUID
	TenantID                                pgtype.UUID
	BranchID                                pgtype.UUID
	ChildID                                 pgtype.UUID
	Sex                                     pgtype.Text
	Religion                                pgtype.Text
	EthnicOrigin                            pgtype.Text
	FirstLanguage                           pgtype.Text
	OtherLanguages                          pgtype.Text
	HomeAddress                             []byte
	HomePostcode                            pgtype.Text
	HomeTelephone                           pgtype.Text
	DisabilityStatus                        string
	DisabilityNotes                         pgtype.Text
	AccessRequirements                      pgtype.Text
	MedicalConditionsStatus                 string
	MedicalConditionsNotes                  pgtype.Text
	PrescribedMedicationStatus              string
	MedicationNotes                         pgtype.Text
	ImmunisationStatus                      string
	ImmunisationCountry                     pgtype.Text
	IllnessDiagnosisHistory                 pgtype.Text
	DietaryRequirementsStatus               string
	DietaryRequirementsNotes                pgtype.Text
	DietarySideEffects                      pgtype.Text
	DoctorName                              pgtype.Text
	DoctorAddress                           pgtype.Text
	DoctorPhone                             pgtype.Text
	HealthVisitorName                       pgtype.Text
	HealthVisitorAddress                    pgtype.Text
	HealthVisitorPhone                      pgtype.Text
	SocialServicesStatus                    string
	SocialServicesNotes                     pgtype.Text
	SocialWorkerName                        pgtype.Text
	SocialWorkerPhone                       pgtype.Text
	SocialWorkerEmail                       pgtype.Text
	ConcernWalking                          string
	ConcernSpeechLanguage                   string
	ConcernHearing                          string
	ConcernSight                            string
	ConcernEmotionalWellbeing               string
	ConcernBehaviour                        string
	ProfessionalReferrals                   []byte
	ParentalResponsibilityNotes             pgtype.Text
	Over18CollectionAcknowledged            bool
	CollectionPasswordIsSet                 bool
	CollectionPasswordUpdatedAt             pgtype.Timestamptz
	CollectionPasswordUpdatedByUserID       pgtype.UUID
	CollectionPasswordUpdatedByMembershipID pgtype.UUID
	BenefitsContributeToFees                string
	WorkingTaxCredit                        string
	CollegeUniPaidToParent                  string
	CollegeUniPaidToNursery                 string
	Funding3yoTermTime                      string
	Funding2yoTermTime                      string
	FundingSupportNotes                     pgtype.Text
	RoutineCareNotes                        pgtype.Text
	GdprDeclaredByName                      pgtype.Text
	GdprDeclaredAt                          pgtype.Timestamptz
	GdprDeclarationDate                     pgtype.Date
	DemographicsHomeReviewed                bool
	MedicalDietaryReviewed                  bool
	HealthContactsReviewed                  bool
	SocialDevelopmentReviewed               bool
	ParentResponsibilityReviewed            bool
	EmergencyCollectionReviewed             bool
	FundingSupportReviewed                  bool
	RoutineCareReviewed                     bool
	CreatedAt                               pgtype.Timestamptz
	UpdatedAt                               pgtype.Timestamptz
}

func (q *Queries) RegistrationProfileCreate(ctx context.Context, arg RegistrationProfileCreateParams) (RegistrationProfileCreateRow, error) {
	row := q.db.QueryRow(ctx, registrationProfileCreate,
		arg.ID,
		arg.TenantID,
		arg.BranchID,
		arg.ChildID,
		arg.Sex,
		arg.Religion,
		arg.EthnicOrigin,
		arg.FirstLanguage,
		arg.OtherLanguages,
		arg.HomeAddress,
		arg.HomePostcode,
		arg.HomeTelephone,
		arg.DisabilityStatus,
		arg.DisabilityNotes,
		arg.AccessRequirements,
		arg.MedicalConditionsStatus,
		arg.MedicalConditionsNotes,
		arg.PrescribedMedicationStatus,
		arg.MedicationNotes,
		arg.ImmunisationStatus,
		arg.ImmunisationCountry,
		arg.IllnessDiagnosisHistory,
		arg.DietaryRequirementsStatus,
		arg.DietaryRequirementsNotes,
		arg.DietarySideEffects,
		arg.DoctorName,
		arg.DoctorAddress,
		arg.DoctorPhone,
		arg.HealthVisitorName,
		arg.HealthVisitorAddress,
		arg.HealthVisitorPhone,
		arg.SocialServicesStatus,
		arg.SocialServicesNotes,
		arg.SocialWorkerName,
		arg.SocialWorkerPhone,
		arg.SocialWorkerEmail,
		arg.ConcernWalking,
		arg.ConcernSpeechLanguage,
		arg.ConcernHearing,
		arg.ConcernSight,
		arg.ConcernEmotionalWellbeing,
		arg.ConcernBehaviour,
		arg.ProfessionalReferrals,
		arg.ParentalResponsibilityNotes,
		arg.Over18CollectionAcknowledged,
		arg.BenefitsContributeToFees,
		arg.WorkingTaxCredit,
		arg.CollegeUniPaidToParent,
		arg.CollegeUniPaidToNursery,
		arg.Funding3yoTermTime,
		arg.Funding2yoTermTime,
		arg.FundingSupportNotes,
		arg.RoutineCareNotes,
		arg.GdprDeclaredByName,
		arg.GdprDeclaredAt,
		arg.GdprDeclarationDate,
		arg.DemographicsHomeReviewed,
		arg.MedicalDietaryReviewed,
		arg.HealthContactsReviewed,
		arg.SocialDevelopmentReviewed,
		arg.ParentResponsibilityReviewed,
		arg.EmergencyCollectionReviewed,
		arg.FundingSupportReviewed,
		arg.RoutineCareReviewed,
	)
	var i RegistrationProfileCreateRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BranchID,
		&i.ChildID,
		&i.Sex,
		&i.Religion,
		&i.EthnicOrigin,
		&i.FirstLanguage,
		&i.OtherLanguages,
		&i.HomeAddress,
		&i.HomePostcode,
		&i.HomeTelephone,
		&i.DisabilityStatus,
		&i.DisabilityNotes,
		&i.AccessRequirements,
		&i.MedicalConditionsStatus,
		&i.MedicalConditionsNotes,
		&i.PrescribedMedicationStatus,
		&i.MedicationNotes,
		&i.ImmunisationStatus,
		&i.ImmunisationCountry,
		&i.IllnessDiagnosisHistory,
		&i.DietaryRequirementsStatus,
		&i.DietaryRequirementsNotes,
		&i.DietarySideEffects,
		&i.DoctorName,
		&i.DoctorAddress,
		&i.DoctorPhone,
		&i.HealthVisitorName,
		&i.HealthVisitorAddress,
		&i.HealthVisitorPhone,
		&i.SocialServicesStatus,
		&i.SocialServicesNotes,
		&i.SocialWorkerName,
		&i.SocialWorkerPhone,
		&i.SocialWorkerEmail,
		&i.ConcernWalking,
		&i.ConcernSpeechLanguage,
		&i.ConcernHearing,
		&i.ConcernSight,
		&i.ConcernEmotionalWellbeing,
		&i.ConcernBehaviour,
		&i.ProfessionalReferrals,
		&i.ParentalResponsibilityNotes,
		&i.Over18CollectionAcknowledged,
		&i.CollectionPasswordIsSet,
		&i.CollectionPasswordUpdatedAt,
		&i.CollectionPasswordUpdatedByUserID,
		&i.CollectionPasswordUpdatedByMembershipID,
		&i.BenefitsContributeToFees,
		&i.WorkingTaxCredit,
		&i.CollegeUniPaidToParent,
		&i.CollegeUniPaidToNursery,
		&i.Funding3yoTermTime,
		&i.Funding2yoTermTime,
		&i.FundingSupportNotes,
		&i.RoutineCareNotes,
		&i.GdprDeclaredByName,
		&i.GdprDeclaredAt,
		&i.GdprDeclarationDate,
		&i.DemographicsHomeReviewed,
		&i.MedicalDietaryReviewed,
		&i.HealthContactsReviewed,
		&i.SocialDevelopmentReviewed,
		&i.ParentResponsibilityReviewed,
		&i.EmergencyCollectionReviewed,
		&i.FundingSupportReviewed,
		&i.RoutineCareReviewed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const registrationProfileCreateContact = `-- name: RegistrationProfileCreateContact :one
INSERT INTO child_registration_contacts (
    id, tenant_id, branch_id, profile_id, child_id,
    contact_type, sort_order, full_name, relationship_to_child,
    address, telephone, email, work_address, has_parental_responsibility
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9,
    $10, $11, $12, $13, $14
)
RETURNING
    id, tenant_id, branch_id, profile_id, child_id,
    contact_type::text, sort_order, full_name, relationship_to_child,
    address, telephone, email, work_address, has_parental_responsibility,
    created_at, updated_at
`

type RegistrationProfileCreateContactParams struct {
	ID                        pgtype.UUID
	TenantID                  pgtype.UUID
	BranchID                  pgtype.UUID
	ProfileID                 pgtype.UUID
	ChildID                   pgtype.UUID
	ContactType               RegistrationContactType
	SortOrder                 int32
	FullName                  string
	RelationshipToChild       pgtype.Text
	Address                   []byte
	Telephone                 pgtype.Text
	Email                     pgtype.Text
	WorkAddress               []byte
	HasParentalResponsibility pgtype.Bool
}

type RegistrationProfileCreateContactRow struct {
	ID                        pgtype.UUID
	TenantID                  pgtype.UUID
	BranchID                  pgtype.UUID
	ProfileID                 pgtype.UUID
	ChildID                   pgtype.UUID
	ContactType               string
	SortOrder                 int32
	FullName                  string
	RelationshipToChild       pgtype.Text
	Address                   []byte
	Telephone                 pgtype.Text
	Email                     pgtype.Text
	WorkAddress               []byte
	HasParentalResponsibility pgtype.Bool
	CreatedAt                 pgtype.Timestamptz
	UpdatedAt                 pgtype.Timestamptz
}

func (q *Queries) RegistrationProfileCreateContact(ctx context.Context, arg RegistrationProfileCreateContactParams) (RegistrationProfileCreateContactRow, error) {
	row := q.db.QueryRow(ctx, registrationProfileCreateContact,
		arg.ID,
		arg.TenantID,
		arg.BranchID,
		arg.ProfileID,
		arg.ChildID,
		arg.ContactType,
		arg.SortOrder,
		arg.FullName,
		arg.RelationshipToChild,
		arg.Address,
		arg.Telephone,
		arg.Email,
		arg.WorkAddress,
		arg.HasParentalResponsibility,
	)
	var i RegistrationProfileCreateContactRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BranchID,
		&i.ProfileID,
		&i.ChildID,
		&i.ContactType,
		&i.SortOrder,
		&i.FullName,
		&i.RelationshipToChild,
		&i.Address,
		&i.Telephone,
		&i.Email,
		&i.WorkAddress,
		&i.HasParentalResponsibility,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const registrationProfileDeleteContactsByTypes = `-- name: RegistrationProfileDeleteContactsByTypes :exec
DELETE FROM child_registration_contacts
WHERE tenant_id = $1
  AND branch_id = $2
  AND profile_id = $3
  AND contact_type::text = ANY($4::text[])
`

type RegistrationProfileDeleteContactsByTypesParams struct {
	TenantID     pgtype.UUID
	BranchID     pgtype.UUID
	ProfileID    pgtype.UUID
	ContactTypes []string
}

func (q *Queries) RegistrationProfileDeleteContactsByTypes(ctx context.Context, arg RegistrationProfileDeleteContactsByTypesParams) error {
	_, err := q.db.Exec(ctx, registrationProfileDeleteContactsByTypes,
		arg.TenantID,
		arg.BranchID,
		arg.ProfileID,
		arg.ContactTypes,
	)
	return err
}

const registrationProfileGetByChild = `-- name: RegistrationProfileGetByChild :one
SELECT
    crp.id,
    crp.tenant_id,
    crp.branch_id,
    crp.child_id,
    c.first_name AS child_first_name,
    c.middle_name AS child_middle_name,
    c.last_name AS child_last_name,
    c.date_of_birth AS child_date_of_birth,
    crp.sex,
    crp.religion,
    crp.ethnic_origin,
    crp.first_language,
    crp.other_languages,
    crp.home_address,
    crp.home_postcode,
    crp.home_telephone,
    crp.disability_status::text,
    crp.disability_notes,
    crp.access_requirements,
    crp.medical_conditions_status::text,
    crp.medical_conditions_notes,
    crp.prescribed_medication_status::text,
    crp.medication_notes,
    crp.immunisation_status::text,
    crp.immunisation_country,
    crp.illness_diagnosis_history,
    crp.dietary_requirements_status::text,
    crp.dietary_requirements_notes,
    crp.dietary_side_effects,
    crp.doctor_name,
    crp.doctor_address,
    crp.doctor_phone,
    crp.health_visitor_name,
    crp.health_visitor_address,
    crp.health_visitor_phone,
    crp.social_services_status::text,
    crp.social_services_notes,
    crp.social_worker_name,
    crp.social_worker_phone,
    crp.social_worker_email,
    crp.concern_walking::text,
    crp.concern_speech_language::text,
    crp.concern_hearing::text,
    crp.concern_sight::text,
    crp.concern_emotional_wellbeing::text,
    crp.concern_behaviour::text,
    crp.professional_referrals,
    crp.parental_responsibility_notes,
    crp.over18_collection_acknowledged,
    crp.collection_password_hash IS NOT NULL AND crp.collection_password_hash <> '' AS collection_password_is_set,
    crp.collection_password_updated_at,
    crp.collection_password_updated_by_user_id,
    crp.collection_password_updated_by_membership_id,
    crp.benefits_contribute_to_fees::text,
    crp.working_tax_credit::text,
    crp.college_uni_paid_to_parent::text,
    crp.college_uni_paid_to_nursery::text,
    crp.funding_3yo_term_time::text,
    crp.funding_2yo_term_time::text,
    crp.funding_support_notes,
    crp.routine_care_notes,
    crp.gdpr_declared_by_name,
    crp.gdpr_declared_at,
    crp.gdpr_declaration_date,
    crp.demographics_home_reviewed,
    crp.medical_dietary_reviewed,
    crp.health_contacts_reviewed,
    crp.social_development_reviewed,
    crp.parent_responsibility_reviewed,
    crp.emergency_collection_reviewed,
    crp.funding_support_reviewed,
    crp.routine_care_reviewed,
    crp.created_at,
    crp.updated_at
FROM child_registration_profiles crp
JOIN children c ON c.tenant_id = crp.tenant_id AND c.branch_id = crp.branch_id AND c.id = crp.child_id
WHERE crp.tenant_id = $1
  AND crp.branch_id = $2
  AND crp.child_id = $3
`

type RegistrationProfileGetByChildParams struct {
	TenantID pgtype.UUID
	BranchID pgtype.UUID
	ChildID  pgtype.UUID
}

type RegistrationProfileGetByChildRow struct {
	ID                                      pgtype.UUID
	TenantID                                pgtype.UUID
	BranchID                                pgtype.UUID
	ChildID                                 pgtype.UUID
	ChildFirstName                          string
	ChildMiddleName                         pgtype.Text
	ChildLastName                           pgtype.Text
	ChildDateOfBirth                        pgtype.Date
	Sex                                     pgtype.Text
	Religion                                pgtype.Text
	EthnicOrigin                            pgtype.Text
	FirstLanguage                           pgtype.Text
	OtherLanguages                          pgtype.Text
	HomeAddress                             []byte
	HomePostcode                            pgtype.Text
	HomeTelephone                           pgtype.Text
	CrpDisabilityStatus                     string
	DisabilityNotes                         pgtype.Text
	AccessRequirements                      pgtype.Text
	CrpMedicalConditionsStatus              string
	MedicalConditionsNotes                  pgtype.Text
	CrpPrescribedMedicationStatus           string
	MedicationNotes                         pgtype.Text
	CrpImmunisationStatus                   string
	ImmunisationCountry                     pgtype.Text
	IllnessDiagnosisHistory                 pgtype.Text
	CrpDietaryRequirementsStatus            string
	DietaryRequirementsNotes                pgtype.Text
	DietarySideEffects                      pgtype.Text
	DoctorName                              pgtype.Text
	DoctorAddress                           pgtype.Text
	DoctorPhone                             pgtype.Text
	HealthVisitorName                       pgtype.Text
	HealthVisitorAddress                    pgtype.Text
	HealthVisitorPhone                      pgtype.Text
	CrpSocialServicesStatus                 string
	SocialServicesNotes                     pgtype.Text
	SocialWorkerName                        pgtype.Text
	SocialWorkerPhone                       pgtype.Text
	SocialWorkerEmail                       pgtype.Text
	CrpConcernWalking                       string
	CrpConcernSpeechLanguage                string
	CrpConcernHearing                       string
	CrpConcernSight                         string
	CrpConcernEmotionalWellbeing            string
	CrpConcernBehaviour                     string
	ProfessionalReferrals                   []byte
	ParentalResponsibilityNotes             pgtype.Text
	Over18CollectionAcknowledged            bool
	CollectionPasswordIsSet                 pgtype.Bool
	CollectionPasswordUpdatedAt             pgtype.Timestamptz
	CollectionPasswordUpdatedByUserID       pgtype.UUID
	CollectionPasswordUpdatedByMembershipID pgtype.UUID
	CrpBenefitsContributeToFees             string
	CrpWorkingTaxCredit                     string
	CrpCollegeUniPaidToParent               string
	CrpCollegeUniPaidToNursery              string
	CrpFunding3yoTermTime                   string
	CrpFunding2yoTermTime                   string
	FundingSupportNotes                     pgtype.Text
	RoutineCareNotes                        pgtype.Text
	GdprDeclaredByName                      pgtype.Text
	GdprDeclaredAt                          pgtype.Timestamptz
	GdprDeclarationDate                     pgtype.Date
	DemographicsHomeReviewed                bool
	MedicalDietaryReviewed                  bool
	HealthContactsReviewed                  bool
	SocialDevelopmentReviewed               bool
	ParentResponsibilityReviewed            bool
	EmergencyCollectionReviewed             bool
	FundingSupportReviewed                  bool
	RoutineCareReviewed                     bool
	CreatedAt                               pgtype.Timestamptz
	UpdatedAt                               pgtype.Timestamptz
}

func (q *Queries) RegistrationProfileGetByChild(ctx context.Context, arg RegistrationProfileGetByChildParams) (RegistrationProfileGetByChildRow, error) {
	row := q.db.QueryRow(ctx, registrationProfileGetByChild, arg.TenantID, arg.BranchID, arg.ChildID)
	var i RegistrationProfileGetByChildRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BranchID,
		&i.ChildID,
		&i.ChildFirstName,
		&i.ChildMiddleName,
		&i.ChildLastName,
		&i.ChildDateOfBirth,
		&i.Sex,
		&i.Religion,
		&i.EthnicOrigin,
		&i.FirstLanguage,
		&i.OtherLanguages,
		&i.HomeAddress,
		&i.HomePostcode,
		&i.HomeTelephone,
		&i.CrpDisabilityStatus,
		&i.DisabilityNotes,
		&i.AccessRequirements,
		&i.CrpMedicalConditionsStatus,
		&i.MedicalConditionsNotes,
		&i.CrpPrescribedMedicationStatus,
		&i.MedicationNotes,
		&i.CrpImmunisationStatus,
		&i.ImmunisationCountry,
		&i.IllnessDiagnosisHistory,
		&i.CrpDietaryRequirementsStatus,
		&i.DietaryRequirementsNotes,
		&i.DietarySideEffects,
		&i.DoctorName,
		&i.DoctorAddress,
		&i.DoctorPhone,
		&i.HealthVisitorName,
		&i.HealthVisitorAddress,
		&i.HealthVisitorPhone,
		&i.CrpSocialServicesStatus,
		&i.SocialServicesNotes,
		&i.SocialWorkerName,
		&i.SocialWorkerPhone,
		&i.SocialWorkerEmail,
		&i.CrpConcernWalking,
		&i.CrpConcernSpeechLanguage,
		&i.CrpConcernHearing,
		&i.CrpConcernSight,
		&i.CrpConcernEmotionalWellbeing,
		&i.CrpConcernBehaviour,
		&i.ProfessionalReferrals,
		&i.ParentalResponsibilityNotes,
		&i.Over18CollectionAcknowledged,
		&i.CollectionPasswordIsSet,
		&i.CollectionPasswordUpdatedAt,
		&i.CollectionPasswordUpdatedByUserID,
		&i.CollectionPasswordUpdatedByMembershipID,
		&i.CrpBenefitsContributeToFees,
		&i.CrpWorkingTaxCredit,
		&i.CrpCollegeUniPaidToParent,
		&i.CrpCollegeUniPaidToNursery,
		&i.CrpFunding3yoTermTime,
		&i.CrpFunding2yoTermTime,
		&i.FundingSupportNotes,
		&i.RoutineCareNotes,
		&i.GdprDeclaredByName,
		&i.GdprDeclaredAt,
		&i.GdprDeclarationDate,
		&i.DemographicsHomeReviewed,
		&i.MedicalDietaryReviewed,
		&i.HealthContactsReviewed,
		&i.SocialDevelopmentReviewed,
		&i.ParentResponsibilityReviewed,
		&i.EmergencyCollectionReviewed,
		&i.FundingSupportReviewed,
		&i.RoutineCareReviewed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const registrationProfileGetForUpdateByChild = `-- name: RegistrationProfileGetForUpdateByChild :one
SELECT
    crp.id,
    crp.tenant_id,
    crp.branch_id,
    crp.child_id,
    c.first_name AS child_first_name,
    c.middle_name AS child_middle_name,
    c.last_name AS child_last_name,
    c.date_of_birth AS child_date_of_birth,
    crp.sex,
    crp.religion,
    crp.ethnic_origin,
    crp.first_language,
    crp.other_languages,
    crp.home_address,
    crp.home_postcode,
    crp.home_telephone,
    crp.disability_status::text,
    crp.disability_notes,
    crp.access_requirements,
    crp.medical_conditions_status::text,
    crp.medical_conditions_notes,
    crp.prescribed_medication_status::text,
    crp.medication_notes,
    crp.immunisation_status::text,
    crp.immunisation_country,
    crp.illness_diagnosis_history,
    crp.dietary_requirements_status::text,
    crp.dietary_requirements_notes,
    crp.dietary_side_effects,
    crp.doctor_name,
    crp.doctor_address,
    crp.doctor_phone,
    crp.health_visitor_name,
    crp.health_visitor_address,
    crp.health_visitor_phone,
    crp.social_services_status::text,
    crp.social_services_notes,
    crp.social_worker_name,
    crp.social_worker_phone,
    crp.social_worker_email,
    crp.concern_walking::text,
    crp.concern_speech_language::text,
    crp.concern_hearing::text,
    crp.concern_sight::text,
    crp.concern_emotional_wellbeing::text,
    crp.concern_behaviour::text,
    crp.professional_referrals,
    crp.parental_responsibility_notes,
    crp.over18_collection_acknowledged,
    crp.collection_password_hash IS NOT NULL AND crp.collection_password_hash <> '' AS collection_password_is_set,
    crp.collection_password_updated_at,
    crp.collection_password_updated_by_user_id,
    crp.collection_password_updated_by_membership_id,
    crp.benefits_contribute_to_fees::text,
    crp.working_tax_credit::text,
    crp.college_uni_paid_to_parent::text,
    crp.college_uni_paid_to_nursery::text,
    crp.funding_3yo_term_time::text,
    crp.funding_2yo_term_time::text,
    crp.funding_support_notes,
    crp.routine_care_notes,
    crp.gdpr_declared_by_name,
    crp.gdpr_declared_at,
    crp.gdpr_declaration_date,
    crp.demographics_home_reviewed,
    crp.medical_dietary_reviewed,
    crp.health_contacts_reviewed,
    crp.social_development_reviewed,
    crp.parent_responsibility_reviewed,
    crp.emergency_collection_reviewed,
    crp.funding_support_reviewed,
    crp.routine_care_reviewed,
    crp.created_at,
    crp.updated_at
FROM child_registration_profiles crp
JOIN children c ON c.tenant_id = crp.tenant_id AND c.branch_id = crp.branch_id AND c.id = crp.child_id
WHERE crp.tenant_id = $1
  AND crp.branch_id = $2
  AND crp.child_id = $3
FOR UPDATE OF crp
`

type RegistrationProfileGetForUpdateByChildParams struct {
	TenantID pgtype.UUID
	BranchID pgtype.UUID
	ChildID  pgtype.UUID
}

type RegistrationProfileGetForUpdateByChildRow struct {
	ID                                      pgtype.UUID
	TenantID                                pgtype.UUID
	BranchID                                pgtype.UUID
	ChildID                                 pgtype.UUID
	ChildFirstName                          string
	ChildMiddleName                         pgtype.Text
	ChildLastName                           pgtype.Text
	ChildDateOfBirth                        pgtype.Date
	Sex                                     pgtype.Text
	Religion                                pgtype.Text
	EthnicOrigin                            pgtype.Text
	FirstLanguage                           pgtype.Text
	OtherLanguages                          pgtype.Text
	HomeAddress                             []byte
	HomePostcode                            pgtype.Text
	HomeTelephone                           pgtype.Text
	CrpDisabilityStatus                     string
	DisabilityNotes                         pgtype.Text
	AccessRequirements                      pgtype.Text
	CrpMedicalConditionsStatus              string
	MedicalConditionsNotes                  pgtype.Text
	CrpPrescribedMedicationStatus           string
	MedicationNotes                         pgtype.Text
	CrpImmunisationStatus                   string
	ImmunisationCountry                     pgtype.Text
	IllnessDiagnosisHistory                 pgtype.Text
	CrpDietaryRequirementsStatus            string
	DietaryRequirementsNotes                pgtype.Text
	DietarySideEffects                      pgtype.Text
	DoctorName                              pgtype.Text
	DoctorAddress                           pgtype.Text
	DoctorPhone                             pgtype.Text
	HealthVisitorName                       pgtype.Text
	HealthVisitorAddress                    pgtype.Text
	HealthVisitorPhone                      pgtype.Text
	CrpSocialServicesStatus                 string
	SocialServicesNotes                     pgtype.Text
	SocialWorkerName                        pgtype.Text
	SocialWorkerPhone                       pgtype.Text
	SocialWorkerEmail                       pgtype.Text
	CrpConcernWalking                       string
	CrpConcernSpeechLanguage                string
	CrpConcernHearing                       string
	CrpConcernSight                         string
	CrpConcernEmotionalWellbeing            string
	CrpConcernBehaviour                     string
	ProfessionalReferrals                   []byte
	ParentalResponsibilityNotes             pgtype.Text
	Over18CollectionAcknowledged            bool
	CollectionPasswordIsSet                 pgtype.Bool
	CollectionPasswordUpdatedAt             pgtype.Timestamptz
	CollectionPasswordUpdatedByUserID       pgtype.UUID
	CollectionPasswordUpdatedByMembershipID pgtype.UUID
	CrpBenefitsContributeToFees             string
	CrpWorkingTaxCredit                     string
	CrpCollegeUniPaidToParent               string
	CrpCollegeUniPaidToNursery              string
	CrpFunding3yoTermTime                   string
	CrpFunding2yoTermTime                   string
	FundingSupportNotes                     pgtype.Text
	RoutineCareNotes                        pgtype.Text
	GdprDeclaredByName                      pgtype.Text
	GdprDeclaredAt                          pgtype.Timestamptz
	GdprDeclarationDate                     pgtype.Date
	DemographicsHomeReviewed                bool
	MedicalDietaryReviewed                  bool
	HealthContactsReviewed                  bool
	SocialDevelopmentReviewed               bool
	ParentResponsibilityReviewed            bool
	EmergencyCollectionReviewed             bool
	FundingSupportReviewed                  bool
	RoutineCareReviewed                     bool
	CreatedAt                               pgtype.Timestamptz
	UpdatedAt                               pgtype.Timestamptz
}

func (q *Queries) RegistrationProfileGetForUpdateByChild(ctx context.Context, arg RegistrationProfileGetForUpdateByChildParams) (RegistrationProfileGetForUpdateByChildRow, error) {
	row := q.db.QueryRow(ctx, registrationProfileGetForUpdateByChild, arg.TenantID, arg.BranchID, arg.ChildID)
	var i RegistrationProfileGetForUpdateByChildRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BranchID,
		&i.ChildID,
		&i.ChildFirstName,
		&i.ChildMiddleName,
		&i.ChildLastName,
		&i.ChildDateOfBirth,
		&i.Sex,
		&i.Religion,
		&i.EthnicOrigin,
		&i.FirstLanguage,
		&i.OtherLanguages,
		&i.HomeAddress,
		&i.HomePostcode,
		&i.HomeTelephone,
		&i.CrpDisabilityStatus,
		&i.DisabilityNotes,
		&i.AccessRequirements,
		&i.CrpMedicalConditionsStatus,
		&i.MedicalConditionsNotes,
		&i.CrpPrescribedMedicationStatus,
		&i.MedicationNotes,
		&i.CrpImmunisationStatus,
		&i.ImmunisationCountry,
		&i.IllnessDiagnosisHistory,
		&i.CrpDietaryRequirementsStatus,
		&i.DietaryRequirementsNotes,
		&i.DietarySideEffects,
		&i.DoctorName,
		&i.DoctorAddress,
		&i.DoctorPhone,
		&i.HealthVisitorName,
		&i.HealthVisitorAddress,
		&i.HealthVisitorPhone,
		&i.CrpSocialServicesStatus,
		&i.SocialServicesNotes,
		&i.SocialWorkerName,
		&i.SocialWorkerPhone,
		&i.SocialWorkerEmail,
		&i.CrpConcernWalking,
		&i.CrpConcernSpeechLanguage,
		&i.CrpConcernHearing,
		&i.CrpConcernSight,
		&i.CrpConcernEmotionalWellbeing,
		&i.CrpConcernBehaviour,
		&i.ProfessionalReferrals,
		&i.ParentalResponsibilityNotes,
		&i.Over18CollectionAcknowledged,
		&i.CollectionPasswordIsSet,
		&i.CollectionPasswordUpdatedAt,
		&i.CollectionPasswordUpdatedByUserID,
		&i.CollectionPasswordUpdatedByMembershipID,
		&i.CrpBenefitsContributeToFees,
		&i.CrpWorkingTaxCredit,
		&i.CrpCollegeUniPaidToParent,
		&i.CrpCollegeUniPaidToNursery,
		&i.CrpFunding3yoTermTime,
		&i.CrpFunding2yoTermTime,
		&i.FundingSupportNotes,
		&i.RoutineCareNotes,
		&i.GdprDeclaredByName,
		&i.GdprDeclaredAt,
		&i.GdprDeclarationDate,
		&i.DemographicsHomeReviewed,
		&i.MedicalDietaryReviewed,
		&i.HealthContactsReviewed,
		&i.SocialDevelopmentReviewed,
		&i.ParentResponsibilityReviewed,
		&i.EmergencyCollectionReviewed,
		&i.FundingSupportReviewed,
		&i.RoutineCareReviewed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const registrationProfileListContacts = `-- name: RegistrationProfileListContacts :many
SELECT
    crc.id,
    crc.tenant_id,
    crc.branch_id,
    crc.profile_id,
    crc.child_id,
    crc.contact_type::text,
    crc.sort_order,
    crc.full_name,
    crc.relationship_to_child,
    crc.address,
    crc.telephone,
    crc.email,
    crc.work_address,
    crc.has_parental_responsibility,
    crc.created_at,
    crc.updated_at
FROM child_registration_contacts crc
WHERE crc.tenant_id = $1
  AND crc.branch_id = $2
  AND crc.profile_id = $3
ORDER BY crc.contact_type, crc.sort_order
`

type RegistrationProfileListContactsParams struct {
	TenantID  pgtype.UUID
	BranchID  pgtype.UUID
	ProfileID pgtype.UUID
}

type RegistrationProfileListContactsRow struct {
	ID                        pgtype.UUID
	TenantID                  pgtype.UUID
	BranchID                  pgtype.UUID
	ProfileID                 pgtype.UUID
	ChildID                   pgtype.UUID
	CrcContactType            string
	SortOrder                 int32
	FullName                  string
	RelationshipToChild       pgtype.Text
	Address                   []byte
	Telephone                 pgtype.Text
	Email                     pgtype.Text
	WorkAddress               []byte
	HasParentalResponsibility pgtype.Bool
	CreatedAt                 pgtype.Timestamptz
	UpdatedAt                 pgtype.Timestamptz
}

func (q *Queries) RegistrationProfileListContacts(ctx context.Context, arg RegistrationProfileListContactsParams) ([]RegistrationProfileListContactsRow, error) {
	rows, err := q.db.Query(ctx, registrationProfileListContacts, arg.TenantID, arg.BranchID, arg.ProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RegistrationProfileListContactsRow
	for rows.Next() {
		var i RegistrationProfileListContactsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.BranchID,
			&i.ProfileID,
			&i.ChildID,
			&i.CrcContactType,
			&i.SortOrder,
			&i.FullName,
			&i.RelationshipToChild,
			&i.Address,
			&i.Telephone,
			&i.Email,
			&i.WorkAddress,
			&i.HasParentalResponsibility,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registrationProfileSetCollectionPassword = `-- name: RegistrationProfileSetCollectionPassword :one
UPDATE child_registration_profiles
SET
    collection_password_hash = $4,
    collection_password_updated_at = $5,
    collection_password_updated_by_user_id = $6,
    collection_password_updated_by_membership_id = $7,
    updated_at = now()
WHERE tenant_id = $1
  AND branch_id = $2
  AND child_id = $3
RETURNING
    id, tenant_id, branch_id, child_id,
    sex, religion, ethnic_origin, first_language, other_languages,
    home_address, home_postcode, home_telephone,
    disability_status::text, disability_notes, access_requirements,
    medical_conditions_status::text, medical_conditions_notes,
    prescribed_medication_status::text, medication_notes,
    immunisation_status::text, immunisation_country, illness_diagnosis_history,
    dietary_requirements_status::text, dietary_requirements_notes, dietary_side_effects,
    doctor_name, doctor_address, doctor_phone,
    health_visitor_name, health_visitor_address, health_visitor_phone,
    social_services_status::text, social_services_notes,
    social_worker_name, social_worker_phone, social_worker_email,
    concern_walking::text, concern_speech_language::text, concern_hearing::text, concern_sight::text,
    concern_emotional_wellbeing::text, concern_behaviour::text, professional_referrals,
    parental_responsibility_notes,
    over18_collection_acknowledged,
    collection_password_hash IS NOT NULL AND child_registration_profiles.collection_password_hash <> '' AS collection_password_is_set,
    collection_password_updated_at, collection_password_updated_by_user_id, collection_password_updated_by_membership_id,
    benefits_contribute_to_fees::text, working_tax_credit::text,
    college_uni_paid_to_parent::text, college_uni_paid_to_nursery::text,
    funding_3yo_term_time::text, funding_2yo_term_time::text, funding_support_notes,
    routine_care_notes,
    gdpr_declared_by_name, gdpr_declared_at, gdpr_declaration_date,
    demographics_home_reviewed, medical_dietary_reviewed, health_contacts_reviewed,
    social_development_reviewed, parent_responsibility_reviewed,
    emergency_collection_reviewed, funding_support_reviewed, routine_care_reviewed,
    created_at, updated_at
`

type RegistrationProfileSetCollectionPasswordParams struct {
	TenantID                                pgtype.UUID
	BranchID                                pgtype.UUID
	ChildID                                 pgtype.UUID
	CollectionPasswordHash                  pgtype.Text
	CollectionPasswordUpdatedAt             pgtype.Timestamptz
	CollectionPasswordUpdatedByUserID       pgtype.UUID
	CollectionPasswordUpdatedByMembershipID pgtype.UUID
}

type RegistrationProfileSetCollectionPasswordRow struct {
	ID                                      pgtype.UUID
	TenantID                                pgtype.UUID
	BranchID                                pgtype.UUID
	ChildID                                 pgtype.UUID
	Sex                                     pgtype.Text
	Religion                                pgtype.Text
	EthnicOrigin                            pgtype.Text
	FirstLanguage                           pgtype.Text
	OtherLanguages                          pgtype.Text
	HomeAddress                             []byte
	HomePostcode                            pgtype.Text
	HomeTelephone                           pgtype.Text
	DisabilityStatus                        string
	DisabilityNotes                         pgtype.Text
	AccessRequirements                      pgtype.Text
	MedicalConditionsStatus                 string
	MedicalConditionsNotes                  pgtype.Text
	PrescribedMedicationStatus              string
	MedicationNotes                         pgtype.Text
	ImmunisationStatus                      string
	ImmunisationCountry                     pgtype.Text
	IllnessDiagnosisHistory                 pgtype.Text
	DietaryRequirementsStatus               string
	DietaryRequirementsNotes                pgtype.Text
	DietarySideEffects                      pgtype.Text
	DoctorName                              pgtype.Text
	DoctorAddress                           pgtype.Text
	DoctorPhone                             pgtype.Text
	HealthVisitorName                       pgtype.Text
	HealthVisitorAddress                    pgtype.Text
	HealthVisitorPhone                      pgtype.Text
	SocialServicesStatus                    string
	SocialServicesNotes                     pgtype.Text
	SocialWorkerName                        pgtype.Text
	SocialWorkerPhone                       pgtype.Text
	SocialWorkerEmail                       pgtype.Text
	ConcernWalking                          string
	ConcernSpeechLanguage                   string
	ConcernHearing                          string
	ConcernSight                            string
	ConcernEmotionalWellbeing               string
	ConcernBehaviour                        string
	ProfessionalReferrals                   []byte
	ParentalResponsibilityNotes             pgtype.Text
	Over18CollectionAcknowledged            bool
	CollectionPasswordIsSet                 pgtype.Bool
	CollectionPasswordUpdatedAt             pgtype.Timestamptz
	CollectionPasswordUpdatedByUserID       pgtype.UUID
	CollectionPasswordUpdatedByMembershipID pgtype.UUID
	BenefitsContributeToFees                string
	WorkingTaxCredit                        string
	CollegeUniPaidToParent                  string
	CollegeUniPaidToNursery                 string
	Funding3yoTermTime                      string
	Funding2yoTermTime                      string
	FundingSupportNotes                     pgtype.Text
	RoutineCareNotes                        pgtype.Text
	GdprDeclaredByName                      pgtype.Text
	GdprDeclaredAt                          pgtype.Timestamptz
	GdprDeclarationDate                     pgtype.Date
	DemographicsHomeReviewed                bool
	MedicalDietaryReviewed                  bool
	HealthContactsReviewed                  bool
	SocialDevelopmentReviewed               bool
	ParentResponsibilityReviewed            bool
	EmergencyCollectionReviewed             bool
	FundingSupportReviewed                  bool
	RoutineCareReviewed                     bool
	CreatedAt                               pgtype.Timestamptz
	UpdatedAt                               pgtype.Timestamptz
}

func (q *Queries) RegistrationProfileSetCollectionPassword(ctx context.Context, arg RegistrationProfileSetCollectionPasswordParams) (RegistrationProfileSetCollectionPasswordRow, error) {
	row := q.db.QueryRow(ctx, registrationProfileSetCollectionPassword,
		arg.TenantID,
		arg.BranchID,
		arg.ChildID,
		arg.CollectionPasswordHash,
		arg.CollectionPasswordUpdatedAt,
		arg.CollectionPasswordUpdatedByUserID,
		arg.CollectionPasswordUpdatedByMembershipID,
	)
	var i RegistrationProfileSetCollectionPasswordRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BranchID,
		&i.ChildID,
		&i.Sex,
		&i.Religion,
		&i.EthnicOrigin,
		&i.FirstLanguage,
		&i.OtherLanguages,
		&i.HomeAddress,
		&i.HomePostcode,
		&i.HomeTelephone,
		&i.DisabilityStatus,
		&i.DisabilityNotes,
		&i.AccessRequirements,
		&i.MedicalConditionsStatus,
		&i.MedicalConditionsNotes,
		&i.PrescribedMedicationStatus,
		&i.MedicationNotes,
		&i.ImmunisationStatus,
		&i.ImmunisationCountry,
		&i.IllnessDiagnosisHistory,
		&i.DietaryRequirementsStatus,
		&i.DietaryRequirementsNotes,
		&i.DietarySideEffects,
		&i.DoctorName,
		&i.DoctorAddress,
		&i.DoctorPhone,
		&i.HealthVisitorName,
		&i.HealthVisitorAddress,
		&i.HealthVisitorPhone,
		&i.SocialServicesStatus,
		&i.SocialServicesNotes,
		&i.SocialWorkerName,
		&i.SocialWorkerPhone,
		&i.SocialWorkerEmail,
		&i.ConcernWalking,
		&i.ConcernSpeechLanguage,
		&i.ConcernHearing,
		&i.ConcernSight,
		&i.ConcernEmotionalWellbeing,
		&i.ConcernBehaviour,
		&i.ProfessionalReferrals,
		&i.ParentalResponsibilityNotes,
		&i.Over18CollectionAcknowledged,
		&i.CollectionPasswordIsSet,
		&i.CollectionPasswordUpdatedAt,
		&i.CollectionPasswordUpdatedByUserID,
		&i.CollectionPasswordUpdatedByMembershipID,
		&i.BenefitsContributeToFees,
		&i.WorkingTaxCredit,
		&i.CollegeUniPaidToParent,
		&i.CollegeUniPaidToNursery,
		&i.Funding3yoTermTime,
		&i.Funding2yoTermTime,
		&i.FundingSupportNotes,
		&i.RoutineCareNotes,
		&i.GdprDeclaredByName,
		&i.GdprDeclaredAt,
		&i.GdprDeclarationDate,
		&i.DemographicsHomeReviewed,
		&i.MedicalDietaryReviewed,
		&i.HealthContactsReviewed,
		&i.SocialDevelopmentReviewed,
		&i.ParentResponsibilityReviewed,
		&i.EmergencyCollectionReviewed,
		&i.FundingSupportReviewed,
		&i.RoutineCareReviewed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const registrationProfileUpdate = `-- name: RegistrationProfileUpdate :one
UPDATE child_registration_profiles crp
SET
    sex = $4,
    religion = $5,
    ethnic_origin = $6,
    first_language = $7,
    other_languages = $8,
    home_address = $9,
    home_postcode = $10,
    home_telephone = $11,
    disability_status = $12,
    disability_notes = $13,
    access_requirements = $14,
    medical_conditions_status = $15,
    medical_conditions_notes = $16,
    prescribed_medication_status = $17,
    medication_notes = $18,
    immunisation_status = $19,
    immunisation_country = $20,
    illness_diagnosis_history = $21,
    dietary_requirements_status = $22,
    dietary_requirements_notes = $23,
    dietary_side_effects = $24,
    doctor_name = $25,
    doctor_address = $26,
    doctor_phone = $27,
    health_visitor_name = $28,
    health_visitor_address = $29,
    health_visitor_phone = $30,
    social_services_status = $31,
    social_services_notes = $32,
    social_worker_name = $33,
    social_worker_phone = $34,
    social_worker_email = $35,
    concern_walking = $36,
    concern_speech_language = $37,
    concern_hearing = $38,
    concern_sight = $39,
    concern_emotional_wellbeing = $40,
    concern_behaviour = $41,
    professional_referrals = $42,
    parental_responsibility_notes = $43,
    over18_collection_acknowledged = $44,
    benefits_contribute_to_fees = $45,
    working_tax_credit = $46,
    college_uni_paid_to_parent = $47,
    college_uni_paid_to_nursery = $48,
    funding_3yo_term_time = $49,
    funding_2yo_term_time = $50,
    funding_support_notes = $51,
    routine_care_notes = $52,
    gdpr_declared_by_name = $53,
    gdpr_declared_at = $54,
    gdpr_declaration_date = $55,
    demographics_home_reviewed = $56,
    medical_dietary_reviewed = $57,
    health_contacts_reviewed = $58,
    social_development_reviewed = $59,
    parent_responsibility_reviewed = $60,
    emergency_collection_reviewed = $61,
    funding_support_reviewed = $62,
    routine_care_reviewed = $63,
    updated_at = now()
WHERE crp.tenant_id = $1
  AND crp.branch_id = $2
  AND crp.child_id = $3
RETURNING
    id, tenant_id, branch_id, child_id,
    sex, religion, ethnic_origin, first_language, other_languages,
    home_address, home_postcode, home_telephone,
    disability_status::text, disability_notes, access_requirements,
    medical_conditions_status::text, medical_conditions_notes,
    prescribed_medication_status::text, medication_notes,
    immunisation_status::text, immunisation_country, illness_diagnosis_history,
    dietary_requirements_status::text, dietary_requirements_notes, dietary_side_effects,
    doctor_name, doctor_address, doctor_phone,
    health_visitor_name, health_visitor_address, health_visitor_phone,
    social_services_status::text, social_services_notes,
    social_worker_name, social_worker_phone, social_worker_email,
    concern_walking::text, concern_speech_language::text, concern_hearing::text, concern_sight::text,
    concern_emotional_wellbeing::text, concern_behaviour::text, professional_referrals,
    parental_responsibility_notes,
    over18_collection_acknowledged,
    collection_password_hash IS NOT NULL AND crp.collection_password_hash <> '' AS collection_password_is_set,
    collection_password_updated_at, collection_password_updated_by_user_id, collection_password_updated_by_membership_id,
    benefits_contribute_to_fees::text, working_tax_credit::text,
    college_uni_paid_to_parent::text, college_uni_paid_to_nursery::text,
    funding_3yo_term_time::text, funding_2yo_term_time::text, funding_support_notes,
    routine_care_notes,
    gdpr_declared_by_name, gdpr_declared_at, gdpr_declaration_date,
    demographics_home_reviewed, medical_dietary_reviewed, health_contacts_reviewed,
    social_development_reviewed, parent_responsibility_reviewed,
    emergency_collection_reviewed, funding_support_reviewed, routine_care_reviewed,
    created_at, updated_at
`

type RegistrationProfileUpdateParams struct {
	TenantID                     pgtype.UUID
	BranchID                     pgtype.UUID
	ChildID                      pgtype.UUID
	Sex                          pgtype.Text
	Religion                     pgtype.Text
	EthnicOrigin                 pgtype.Text
	FirstLanguage                pgtype.Text
	OtherLanguages               pgtype.Text
	HomeAddress                  []byte
	HomePostcode                 pgtype.Text
	HomeTelephone                pgtype.Text
	DisabilityStatus             RegistrationYesNoUnknown
	DisabilityNotes              pgtype.Text
	AccessRequirements           pgtype.Text
	MedicalConditionsStatus      RegistrationYesNoUnknown
	MedicalConditionsNotes       pgtype.Text
	PrescribedMedicationStatus   RegistrationYesNoUnknown
	MedicationNotes              pgtype.Text
	ImmunisationStatus           RegistrationImmunisationStatus
	ImmunisationCountry          pgtype.Text
	IllnessDiagnosisHistory      pgtype.Text
	DietaryRequirementsStatus    RegistrationYesNoUnknown
	DietaryRequirementsNotes     pgtype.Text
	DietarySideEffects           pgtype.Text
	DoctorName                   pgtype.Text
	DoctorAddress                pgtype.Text
	DoctorPhone                  pgtype.Text
	HealthVisitorName            pgtype.Text
	HealthVisitorAddress         pgtype.Text
	HealthVisitorPhone           pgtype.Text
	SocialServicesStatus         RegistrationYesNoUnknown
	SocialServicesNotes          pgtype.Text
	SocialWorkerName             pgtype.Text
	SocialWorkerPhone            pgtype.Text
	SocialWorkerEmail            pgtype.Text
	ConcernWalking               RegistrationYesNoUnknown
	ConcernSpeechLanguage        RegistrationYesNoUnknown
	ConcernHearing               RegistrationYesNoUnknown
	ConcernSight                 RegistrationYesNoUnknown
	ConcernEmotionalWellbeing    RegistrationYesNoUnknown
	ConcernBehaviour             RegistrationYesNoUnknown
	ProfessionalReferrals        []byte
	ParentalResponsibilityNotes  pgtype.Text
	Over18CollectionAcknowledged bool
	BenefitsContributeToFees     RegistrationYesNoUnknown
	WorkingTaxCredit             RegistrationYesNoUnknown
	CollegeUniPaidToParent       RegistrationYesNoUnknown
	CollegeUniPaidToNursery      RegistrationYesNoUnknown
	Funding3yoTermTime           RegistrationYesNoUnknown
	Funding2yoTermTime           RegistrationYesNoUnknown
	FundingSupportNotes          pgtype.Text
	RoutineCareNotes             pgtype.Text
	GdprDeclaredByName           pgtype.Text
	GdprDeclaredAt               pgtype.Timestamptz
	GdprDeclarationDate          pgtype.Date
	DemographicsHomeReviewed     bool
	MedicalDietaryReviewed       bool
	HealthContactsReviewed       bool
	SocialDevelopmentReviewed    bool
	ParentResponsibilityReviewed bool
	EmergencyCollectionReviewed  bool
	FundingSupportReviewed       bool
	RoutineCareReviewed          bool
}

type RegistrationProfileUpdateRow struct {
	ID                                      pgtype.UUID
	TenantID                                pgtype.UUID
	BranchID                                pgtype.UUID
	ChildID                                 pgtype.UUID
	Sex                                     pgtype.Text
	Religion                                pgtype.Text
	EthnicOrigin                            pgtype.Text
	FirstLanguage                           pgtype.Text
	OtherLanguages                          pgtype.Text
	HomeAddress                             []byte
	HomePostcode                            pgtype.Text
	HomeTelephone                           pgtype.Text
	DisabilityStatus                        string
	DisabilityNotes                         pgtype.Text
	AccessRequirements                      pgtype.Text
	MedicalConditionsStatus                 string
	MedicalConditionsNotes                  pgtype.Text
	PrescribedMedicationStatus              string
	MedicationNotes                         pgtype.Text
	ImmunisationStatus                      string
	ImmunisationCountry                     pgtype.Text
	IllnessDiagnosisHistory                 pgtype.Text
	DietaryRequirementsStatus               string
	DietaryRequirementsNotes                pgtype.Text
	DietarySideEffects                      pgtype.Text
	DoctorName                              pgtype.Text
	DoctorAddress                           pgtype.Text
	DoctorPhone                             pgtype.Text
	HealthVisitorName                       pgtype.Text
	HealthVisitorAddress                    pgtype.Text
	HealthVisitorPhone                      pgtype.Text
	SocialServicesStatus                    string
	SocialServicesNotes                     pgtype.Text
	SocialWorkerName                        pgtype.Text
	SocialWorkerPhone                       pgtype.Text
	SocialWorkerEmail                       pgtype.Text
	ConcernWalking                          string
	ConcernSpeechLanguage                   string
	ConcernHearing                          string
	ConcernSight                            string
	ConcernEmotionalWellbeing               string
	ConcernBehaviour                        string
	ProfessionalReferrals                   []byte
	ParentalResponsibilityNotes             pgtype.Text
	Over18CollectionAcknowledged            bool
	CollectionPasswordIsSet                 pgtype.Bool
	CollectionPasswordUpdatedAt             pgtype.Timestamptz
	CollectionPasswordUpdatedByUserID       pgtype.UUID
	CollectionPasswordUpdatedByMembershipID pgtype.UUID
	BenefitsContributeToFees                string
	WorkingTaxCredit                        string
	CollegeUniPaidToParent                  string
	CollegeUniPaidToNursery                 string
	Funding3yoTermTime                      string
	Funding2yoTermTime                      string
	FundingSupportNotes                     pgtype.Text
	RoutineCareNotes                        pgtype.Text
	GdprDeclaredByName                      pgtype.Text
	GdprDeclaredAt                          pgtype.Timestamptz
	GdprDeclarationDate                     pgtype.Date
	DemographicsHomeReviewed                bool
	MedicalDietaryReviewed                  bool
	HealthContactsReviewed                  bool
	SocialDevelopmentReviewed               bool
	ParentResponsibilityReviewed            bool
	EmergencyCollectionReviewed             bool
	FundingSupportReviewed                  bool
	RoutineCareReviewed                     bool
	CreatedAt                               pgtype.Timestamptz
	UpdatedAt                               pgtype.Timestamptz
}

func (q *Queries) RegistrationProfileUpdate(ctx context.Context, arg RegistrationProfileUpdateParams) (RegistrationProfileUpdateRow, error) {
	row := q.db.QueryRow(ctx, registrationProfileUpdate,
		arg.TenantID,
		arg.BranchID,
		arg.ChildID,
		arg.Sex,
		arg.Religion,
		arg.EthnicOrigin,
		arg.FirstLanguage,
		arg.OtherLanguages,
		arg.HomeAddress,
		arg.HomePostcode,
		arg.HomeTelephone,
		arg.DisabilityStatus,
		arg.DisabilityNotes,
		arg.AccessRequirements,
		arg.MedicalConditionsStatus,
		arg.MedicalConditionsNotes,
		arg.PrescribedMedicationStatus,
		arg.MedicationNotes,
		arg.ImmunisationStatus,
		arg.ImmunisationCountry,
		arg.IllnessDiagnosisHistory,
		arg.DietaryRequirementsStatus,
		arg.DietaryRequirementsNotes,
		arg.DietarySideEffects,
		arg.DoctorName,
		arg.DoctorAddress,
		arg.DoctorPhone,
		arg.HealthVisitorName,
		arg.HealthVisitorAddress,
		arg.HealthVisitorPhone,
		arg.SocialServicesStatus,
		arg.SocialServicesNotes,
		arg.SocialWorkerName,
		arg.SocialWorkerPhone,
		arg.SocialWorkerEmail,
		arg.ConcernWalking,
		arg.ConcernSpeechLanguage,
		arg.ConcernHearing,
		arg.ConcernSight,
		arg.ConcernEmotionalWellbeing,
		arg.ConcernBehaviour,
		arg.ProfessionalReferrals,
		arg.ParentalResponsibilityNotes,
		arg.Over18CollectionAcknowledged,
		arg.BenefitsContributeToFees,
		arg.WorkingTaxCredit,
		arg.CollegeUniPaidToParent,
		arg.CollegeUniPaidToNursery,
		arg.Funding3yoTermTime,
		arg.Funding2yoTermTime,
		arg.FundingSupportNotes,
		arg.RoutineCareNotes,
		arg.GdprDeclaredByName,
		arg.GdprDeclaredAt,
		arg.GdprDeclarationDate,
		arg.DemographicsHomeReviewed,
		arg.MedicalDietaryReviewed,
		arg.HealthContactsReviewed,
		arg.SocialDevelopmentReviewed,
		arg.ParentResponsibilityReviewed,
		arg.EmergencyCollectionReviewed,
		arg.FundingSupportReviewed,
		arg.RoutineCareReviewed,
	)
	var i RegistrationProfileUpdateRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BranchID,
		&i.ChildID,
		&i.Sex,
		&i.Religion,
		&i.EthnicOrigin,
		&i.FirstLanguage,
		&i.OtherLanguages,
		&i.HomeAddress,
		&i.HomePostcode,
		&i.HomeTelephone,
		&i.DisabilityStatus,
		&i.DisabilityNotes,
		&i.AccessRequirements,
		&i.MedicalConditionsStatus,
		&i.MedicalConditionsNotes,
		&i.PrescribedMedicationStatus,
		&i.MedicationNotes,
		&i.ImmunisationStatus,
		&i.ImmunisationCountry,
		&i.IllnessDiagnosisHistory,
		&i.DietaryRequirementsStatus,
		&i.DietaryRequirementsNotes,
		&i.DietarySideEffects,
		&i.DoctorName,
		&i.DoctorAddress,
		&i.DoctorPhone,
		&i.HealthVisitorName,
		&i.HealthVisitorAddress,
		&i.HealthVisitorPhone,
		&i.SocialServicesStatus,
		&i.SocialServicesNotes,
		&i.SocialWorkerName,
		&i.SocialWorkerPhone,
		&i.SocialWorkerEmail,
		&i.ConcernWalking,
		&i.ConcernSpeechLanguage,
		&i.ConcernHearing,
		&i.ConcernSight,
		&i.ConcernEmotionalWellbeing,
		&i.ConcernBehaviour,
		&i.ProfessionalReferrals,
		&i.ParentalResponsibilityNotes,
		&i.Over18CollectionAcknowledged,
		&i.CollectionPasswordIsSet,
		&i.CollectionPasswordUpdatedAt,
		&i.CollectionPasswordUpdatedByUserID,
		&i.CollectionPasswordUpdatedByMembershipID,
		&i.BenefitsContributeToFees,
		&i.WorkingTaxCredit,
		&i.CollegeUniPaidToParent,
		&i.CollegeUniPaidToNursery,
		&i.Funding3yoTermTime,
		&i.Funding2yoTermTime,
		&i.FundingSupportNotes,
		&i.RoutineCareNotes,
		&i.GdprDeclaredByName,
		&i.GdprDeclaredAt,
		&i.GdprDeclarationDate,
		&i.DemographicsHomeReviewed,
		&i.MedicalDietaryReviewed,
		&i.HealthContactsReviewed,
		&i.SocialDevelopmentReviewed,
		&i.ParentResponsibilityReviewed,
		&i.EmergencyCollectionReviewed,
		&i.FundingSupportReviewed,
		&i.RoutineCareReviewed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
