// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: registration_completion.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const attestationCreate = `-- name: AttestationCreate :exec
INSERT INTO child_registration_completion_attestations (
    id, tenant_id, branch_id, child_id,
    consent_record_id, profile_updated_at, office_checklist_updated_at,
    attested_by_user_id, attested_by_membership_id, attested_at,
    request_id
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10,
    $11
)
`

type AttestationCreateParams struct {
	ID                       pgtype.UUID
	TenantID                 pgtype.UUID
	BranchID                 pgtype.UUID
	ChildID                  pgtype.UUID
	ConsentRecordID          pgtype.UUID
	ProfileUpdatedAt         pgtype.Timestamptz
	OfficeChecklistUpdatedAt pgtype.Timestamptz
	AttestedByUserID         pgtype.UUID
	AttestedByMembershipID   pgtype.UUID
	AttestedAt               pgtype.Timestamptz
	RequestID                pgtype.Text
}

func (q *Queries) AttestationCreate(ctx context.Context, arg AttestationCreateParams) error {
	_, err := q.db.Exec(ctx, attestationCreate,
		arg.ID,
		arg.TenantID,
		arg.BranchID,
		arg.ChildID,
		arg.ConsentRecordID,
		arg.ProfileUpdatedAt,
		arg.OfficeChecklistUpdatedAt,
		arg.AttestedByUserID,
		arg.AttestedByMembershipID,
		arg.AttestedAt,
		arg.RequestID,
	)
	return err
}

const attestationGetLatestByChild = `-- name: AttestationGetLatestByChild :one
SELECT
    id, tenant_id, branch_id, child_id,
    consent_record_id, profile_updated_at, office_checklist_updated_at,
    attested_by_user_id, attested_by_membership_id, attested_at,
    request_id, created_at
FROM child_registration_completion_attestations
WHERE tenant_id = $1 AND branch_id = $2 AND child_id = $3
ORDER BY attested_at DESC
LIMIT 1
`

type AttestationGetLatestByChildParams struct {
	TenantID pgtype.UUID
	BranchID pgtype.UUID
	ChildID  pgtype.UUID
}

func (q *Queries) AttestationGetLatestByChild(ctx context.Context, arg AttestationGetLatestByChildParams) (ChildRegistrationCompletionAttestation, error) {
	row := q.db.QueryRow(ctx, attestationGetLatestByChild, arg.TenantID, arg.BranchID, arg.ChildID)
	var i ChildRegistrationCompletionAttestation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BranchID,
		&i.ChildID,
		&i.ConsentRecordID,
		&i.ProfileUpdatedAt,
		&i.OfficeChecklistUpdatedAt,
		&i.AttestedByUserID,
		&i.AttestedByMembershipID,
		&i.AttestedAt,
		&i.RequestID,
		&i.CreatedAt,
	)
	return i, err
}

const officeChecklistGetUpdatedAt = `-- name: OfficeChecklistGetUpdatedAt :one
SELECT updated_at
FROM child_registration_office_checklists
WHERE tenant_id = $1 AND branch_id = $2 AND child_id = $3
`

type OfficeChecklistGetUpdatedAtParams struct {
	TenantID pgtype.UUID
	BranchID pgtype.UUID
	ChildID  pgtype.UUID
}

func (q *Queries) OfficeChecklistGetUpdatedAt(ctx context.Context, arg OfficeChecklistGetUpdatedAtParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, officeChecklistGetUpdatedAt, arg.TenantID, arg.BranchID, arg.ChildID)
	var updated_at pgtype.Timestamptz
	err := row.Scan(&updated_at)
	return updated_at, err
}

const profileGetUpdatedAt = `-- name: ProfileGetUpdatedAt :one
SELECT updated_at
FROM child_registration_profiles
WHERE tenant_id = $1 AND branch_id = $2 AND child_id = $3
`

type ProfileGetUpdatedAtParams struct {
	TenantID pgtype.UUID
	BranchID pgtype.UUID
	ChildID  pgtype.UUID
}

func (q *Queries) ProfileGetUpdatedAt(ctx context.Context, arg ProfileGetUpdatedAtParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, profileGetUpdatedAt, arg.TenantID, arg.BranchID, arg.ChildID)
	var updated_at pgtype.Timestamptz
	err := row.Scan(&updated_at)
	return updated_at, err
}
