// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session_template_entries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const sessionTemplateEntriesDeleteByTemplate = `-- name: SessionTemplateEntriesDeleteByTemplate :exec
DELETE FROM session_template_entries
WHERE tenant_id = $1 AND branch_id = $2 AND template_id = $3
`

type SessionTemplateEntriesDeleteByTemplateParams struct {
	TenantID   pgtype.UUID
	BranchID   pgtype.UUID
	TemplateID pgtype.UUID
}

func (q *Queries) SessionTemplateEntriesDeleteByTemplate(ctx context.Context, arg SessionTemplateEntriesDeleteByTemplateParams) error {
	_, err := q.db.Exec(ctx, sessionTemplateEntriesDeleteByTemplate, arg.TenantID, arg.BranchID, arg.TemplateID)
	return err
}

const sessionTemplateEntriesInsert = `-- name: SessionTemplateEntriesInsert :exec
INSERT INTO session_template_entries (id, tenant_id, branch_id, template_id, day_of_week, session_type_id)
VALUES ($1, $2, $3, $4, $5, $6)
`

type SessionTemplateEntriesInsertParams struct {
	ID            pgtype.UUID
	TenantID      pgtype.UUID
	BranchID      pgtype.UUID
	TemplateID    pgtype.UUID
	DayOfWeek     int32
	SessionTypeID pgtype.UUID
}

func (q *Queries) SessionTemplateEntriesInsert(ctx context.Context, arg SessionTemplateEntriesInsertParams) error {
	_, err := q.db.Exec(ctx, sessionTemplateEntriesInsert,
		arg.ID,
		arg.TenantID,
		arg.BranchID,
		arg.TemplateID,
		arg.DayOfWeek,
		arg.SessionTypeID,
	)
	return err
}

const sessionTemplateEntriesListByTemplate = `-- name: SessionTemplateEntriesListByTemplate :many
SELECT
    e.id,
    e.tenant_id,
    e.branch_id,
    e.template_id,
    e.day_of_week,
    e.session_type_id,
    e.created_at,
    e.updated_at,
    st.name AS session_type_name,
    st.start_time AS session_type_start_time,
    st.end_time AS session_type_end_time,
    st.is_active AS session_type_is_active
FROM session_template_entries e
JOIN session_types st
  ON st.tenant_id = e.tenant_id
 AND st.branch_id = e.branch_id
 AND st.id = e.session_type_id
WHERE e.tenant_id = $1 AND e.branch_id = $2 AND e.template_id = $3
ORDER BY e.day_of_week ASC, st.start_time ASC
`

type SessionTemplateEntriesListByTemplateParams struct {
	TenantID   pgtype.UUID
	BranchID   pgtype.UUID
	TemplateID pgtype.UUID
}

type SessionTemplateEntriesListByTemplateRow struct {
	ID                   pgtype.UUID
	TenantID             pgtype.UUID
	BranchID             pgtype.UUID
	TemplateID           pgtype.UUID
	DayOfWeek            int32
	SessionTypeID        pgtype.UUID
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	SessionTypeName      string
	SessionTypeStartTime pgtype.Time
	SessionTypeEndTime   pgtype.Time
	SessionTypeIsActive  bool
}

func (q *Queries) SessionTemplateEntriesListByTemplate(ctx context.Context, arg SessionTemplateEntriesListByTemplateParams) ([]SessionTemplateEntriesListByTemplateRow, error) {
	rows, err := q.db.Query(ctx, sessionTemplateEntriesListByTemplate, arg.TenantID, arg.BranchID, arg.TemplateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionTemplateEntriesListByTemplateRow
	for rows.Next() {
		var i SessionTemplateEntriesListByTemplateRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.BranchID,
			&i.TemplateID,
			&i.DayOfWeek,
			&i.SessionTypeID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SessionTypeName,
			&i.SessionTypeStartTime,
			&i.SessionTypeEndTime,
			&i.SessionTypeIsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
