// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session_types.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const sessionTypesArchive = `-- name: SessionTypesArchive :exec
UPDATE session_types
SET is_active = false, updated_at = now()
WHERE tenant_id = $1 AND branch_id = $2 AND id = $3
`

type SessionTypesArchiveParams struct {
	TenantID pgtype.UUID
	BranchID pgtype.UUID
	ID       pgtype.UUID
}

func (q *Queries) SessionTypesArchive(ctx context.Context, arg SessionTypesArchiveParams) error {
	_, err := q.db.Exec(ctx, sessionTypesArchive, arg.TenantID, arg.BranchID, arg.ID)
	return err
}

const sessionTypesCheckActiveNameExists = `-- name: SessionTypesCheckActiveNameExists :one
SELECT EXISTS (
    SELECT 1 FROM session_types
    WHERE tenant_id = $1 AND branch_id = $2 AND name = $3 AND is_active = true
      AND ($4::uuid IS NULL OR id != $4)
)
`

type SessionTypesCheckActiveNameExistsParams struct {
	TenantID pgtype.UUID
	BranchID pgtype.UUID
	Name     string
	Column4  pgtype.UUID
}

func (q *Queries) SessionTypesCheckActiveNameExists(ctx context.Context, arg SessionTypesCheckActiveNameExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, sessionTypesCheckActiveNameExists,
		arg.TenantID,
		arg.BranchID,
		arg.Name,
		arg.Column4,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const sessionTypesCountByBranch = `-- name: SessionTypesCountByBranch :one
SELECT COUNT(*)
FROM session_types
WHERE tenant_id = $1
  AND branch_id = $2
  AND (NOT $3::bool OR is_active = true)
`

type SessionTypesCountByBranchParams struct {
	TenantID pgtype.UUID
	BranchID pgtype.UUID
	Column3  bool
}

func (q *Queries) SessionTypesCountByBranch(ctx context.Context, arg SessionTypesCountByBranchParams) (int64, error) {
	row := q.db.QueryRow(ctx, sessionTypesCountByBranch, arg.TenantID, arg.BranchID, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const sessionTypesCreate = `-- name: SessionTypesCreate :exec
INSERT INTO session_types (id, tenant_id, branch_id, name, start_time, end_time)
VALUES ($1, $2, $3, $4, $5, $6)
`

type SessionTypesCreateParams struct {
	ID        pgtype.UUID
	TenantID  pgtype.UUID
	BranchID  pgtype.UUID
	Name      string
	StartTime pgtype.Time
	EndTime   pgtype.Time
}

func (q *Queries) SessionTypesCreate(ctx context.Context, arg SessionTypesCreateParams) error {
	_, err := q.db.Exec(ctx, sessionTypesCreate,
		arg.ID,
		arg.TenantID,
		arg.BranchID,
		arg.Name,
		arg.StartTime,
		arg.EndTime,
	)
	return err
}

const sessionTypesExists = `-- name: SessionTypesExists :one
SELECT EXISTS (
    SELECT 1 FROM session_types
    WHERE tenant_id = $1 AND branch_id = $2 AND id = $3
)
`

type SessionTypesExistsParams struct {
	TenantID pgtype.UUID
	BranchID pgtype.UUID
	ID       pgtype.UUID
}

func (q *Queries) SessionTypesExists(ctx context.Context, arg SessionTypesExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, sessionTypesExists, arg.TenantID, arg.BranchID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const sessionTypesGetByID = `-- name: SessionTypesGetByID :one
SELECT id, tenant_id, branch_id, name, start_time, end_time, is_active, created_at, updated_at
FROM session_types
WHERE tenant_id = $1
  AND branch_id = $2
  AND id = $3
`

type SessionTypesGetByIDParams struct {
	TenantID pgtype.UUID
	BranchID pgtype.UUID
	ID       pgtype.UUID
}

func (q *Queries) SessionTypesGetByID(ctx context.Context, arg SessionTypesGetByIDParams) (SessionType, error) {
	row := q.db.QueryRow(ctx, sessionTypesGetByID, arg.TenantID, arg.BranchID, arg.ID)
	var i SessionType
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BranchID,
		&i.Name,
		&i.StartTime,
		&i.EndTime,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const sessionTypesGetByIDForUpdate = `-- name: SessionTypesGetByIDForUpdate :one
SELECT id, tenant_id, branch_id, name, start_time, end_time, is_active, created_at, updated_at
FROM session_types
WHERE tenant_id = $1
  AND branch_id = $2
  AND id = $3
FOR UPDATE
`

type SessionTypesGetByIDForUpdateParams struct {
	TenantID pgtype.UUID
	BranchID pgtype.UUID
	ID       pgtype.UUID
}

func (q *Queries) SessionTypesGetByIDForUpdate(ctx context.Context, arg SessionTypesGetByIDForUpdateParams) (SessionType, error) {
	row := q.db.QueryRow(ctx, sessionTypesGetByIDForUpdate, arg.TenantID, arg.BranchID, arg.ID)
	var i SessionType
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BranchID,
		&i.Name,
		&i.StartTime,
		&i.EndTime,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const sessionTypesListByBranch = `-- name: SessionTypesListByBranch :many
SELECT id, tenant_id, branch_id, name, start_time, end_time, is_active, created_at, updated_at
FROM session_types
WHERE tenant_id = $1
  AND branch_id = $2
  AND (NOT $3::bool OR is_active = true)
ORDER BY name ASC
`

type SessionTypesListByBranchParams struct {
	TenantID pgtype.UUID
	BranchID pgtype.UUID
	Column3  bool
}

func (q *Queries) SessionTypesListByBranch(ctx context.Context, arg SessionTypesListByBranchParams) ([]SessionType, error) {
	rows, err := q.db.Query(ctx, sessionTypesListByBranch, arg.TenantID, arg.BranchID, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionType
	for rows.Next() {
		var i SessionType
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.BranchID,
			&i.Name,
			&i.StartTime,
			&i.EndTime,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sessionTypesListByBranchPaginated = `-- name: SessionTypesListByBranchPaginated :many
SELECT id, tenant_id, branch_id, name, start_time, end_time, is_active, created_at, updated_at
FROM session_types
WHERE tenant_id = $1
  AND branch_id = $2
  AND (NOT $3::bool OR is_active = true)
ORDER BY name ASC
LIMIT $5 OFFSET $4
`

type SessionTypesListByBranchPaginatedParams struct {
	TenantID pgtype.UUID
	BranchID pgtype.UUID
	Column3  bool
	Offset   pgtype.Int4
	Limit    pgtype.Int4
}

func (q *Queries) SessionTypesListByBranchPaginated(ctx context.Context, arg SessionTypesListByBranchPaginatedParams) ([]SessionType, error) {
	rows, err := q.db.Query(ctx, sessionTypesListByBranchPaginated,
		arg.TenantID,
		arg.BranchID,
		arg.Column3,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionType
	for rows.Next() {
		var i SessionType
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.BranchID,
			&i.Name,
			&i.StartTime,
			&i.EndTime,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sessionTypesListByBranchPaginatedSortByCreatedAtAsc = `-- name: SessionTypesListByBranchPaginatedSortByCreatedAtAsc :many
SELECT id, tenant_id, branch_id, name, start_time, end_time, is_active, created_at, updated_at
FROM session_types
WHERE tenant_id = $1
  AND branch_id = $2
  AND (NOT $3::bool OR is_active = true)
ORDER BY created_at ASC
LIMIT $5 OFFSET $4
`

type SessionTypesListByBranchPaginatedSortByCreatedAtAscParams struct {
	TenantID pgtype.UUID
	BranchID pgtype.UUID
	Column3  bool
	Offset   pgtype.Int4
	Limit    pgtype.Int4
}

func (q *Queries) SessionTypesListByBranchPaginatedSortByCreatedAtAsc(ctx context.Context, arg SessionTypesListByBranchPaginatedSortByCreatedAtAscParams) ([]SessionType, error) {
	rows, err := q.db.Query(ctx, sessionTypesListByBranchPaginatedSortByCreatedAtAsc,
		arg.TenantID,
		arg.BranchID,
		arg.Column3,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionType
	for rows.Next() {
		var i SessionType
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.BranchID,
			&i.Name,
			&i.StartTime,
			&i.EndTime,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sessionTypesListByBranchPaginatedSortByCreatedAtDesc = `-- name: SessionTypesListByBranchPaginatedSortByCreatedAtDesc :many
SELECT id, tenant_id, branch_id, name, start_time, end_time, is_active, created_at, updated_at
FROM session_types
WHERE tenant_id = $1
  AND branch_id = $2
  AND (NOT $3::bool OR is_active = true)
ORDER BY created_at DESC
LIMIT $5 OFFSET $4
`

type SessionTypesListByBranchPaginatedSortByCreatedAtDescParams struct {
	TenantID pgtype.UUID
	BranchID pgtype.UUID
	Column3  bool
	Offset   pgtype.Int4
	Limit    pgtype.Int4
}

func (q *Queries) SessionTypesListByBranchPaginatedSortByCreatedAtDesc(ctx context.Context, arg SessionTypesListByBranchPaginatedSortByCreatedAtDescParams) ([]SessionType, error) {
	rows, err := q.db.Query(ctx, sessionTypesListByBranchPaginatedSortByCreatedAtDesc,
		arg.TenantID,
		arg.BranchID,
		arg.Column3,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionType
	for rows.Next() {
		var i SessionType
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.BranchID,
			&i.Name,
			&i.StartTime,
			&i.EndTime,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sessionTypesListByBranchPaginatedSortByNameDesc = `-- name: SessionTypesListByBranchPaginatedSortByNameDesc :many
SELECT id, tenant_id, branch_id, name, start_time, end_time, is_active, created_at, updated_at
FROM session_types
WHERE tenant_id = $1
  AND branch_id = $2
  AND (NOT $3::bool OR is_active = true)
ORDER BY name DESC
LIMIT $5 OFFSET $4
`

type SessionTypesListByBranchPaginatedSortByNameDescParams struct {
	TenantID pgtype.UUID
	BranchID pgtype.UUID
	Column3  bool
	Offset   pgtype.Int4
	Limit    pgtype.Int4
}

func (q *Queries) SessionTypesListByBranchPaginatedSortByNameDesc(ctx context.Context, arg SessionTypesListByBranchPaginatedSortByNameDescParams) ([]SessionType, error) {
	rows, err := q.db.Query(ctx, sessionTypesListByBranchPaginatedSortByNameDesc,
		arg.TenantID,
		arg.BranchID,
		arg.Column3,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionType
	for rows.Next() {
		var i SessionType
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.BranchID,
			&i.Name,
			&i.StartTime,
			&i.EndTime,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sessionTypesReactivate = `-- name: SessionTypesReactivate :exec
UPDATE session_types
SET is_active = true, updated_at = now()
WHERE tenant_id = $1 AND branch_id = $2 AND id = $3
`

type SessionTypesReactivateParams struct {
	TenantID pgtype.UUID
	BranchID pgtype.UUID
	ID       pgtype.UUID
}

func (q *Queries) SessionTypesReactivate(ctx context.Context, arg SessionTypesReactivateParams) error {
	_, err := q.db.Exec(ctx, sessionTypesReactivate, arg.TenantID, arg.BranchID, arg.ID)
	return err
}

const sessionTypesUpdate = `-- name: SessionTypesUpdate :execrows
UPDATE session_types
SET
    name = CASE WHEN $1 = 1 THEN $2 ELSE name END,
    start_time = CASE WHEN $3 = 1 THEN $4 ELSE start_time END,
    end_time = CASE WHEN $5 = 1 THEN $6 ELSE end_time END,
    updated_at = now()
WHERE tenant_id = $7 AND branch_id = $8 AND id = $9
`

type SessionTypesUpdateParams struct {
	SetName      interface{}
	Name         string
	SetStartTime interface{}
	StartTime    pgtype.Time
	SetEndTime   interface{}
	EndTime      pgtype.Time
	TenantID     pgtype.UUID
	BranchID     pgtype.UUID
	ID           pgtype.UUID
}

func (q *Queries) SessionTypesUpdate(ctx context.Context, arg SessionTypesUpdateParams) (int64, error) {
	result, err := q.db.Exec(ctx, sessionTypesUpdate,
		arg.SetName,
		arg.Name,
		arg.SetStartTime,
		arg.StartTime,
		arg.SetEndTime,
		arg.EndTime,
		arg.TenantID,
		arg.BranchID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
