// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: smoke.sql

package sqlc

import (
	"context"
)

const smokeValue = `-- name: SmokeValue :one
SELECT 1::int AS value
`

func (q *Queries) SmokeValue(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, smokeValue)
	var value int32
	err := row.Scan(&value)
	return value, err
}
