// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stripe_webhooks.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPaymentAttemptAndInvoiceForWebhook = `-- name: GetPaymentAttemptAndInvoiceForWebhook :one
SELECT
    pa.id AS attempt_id,
    pa.status AS attempt_status,
    pa.amount_minor AS attempt_amount_minor,
    pa.currency_code AS attempt_currency_code,
    pa.stripe_checkout_session_id AS attempt_session_id,
    i.id AS invoice_id,
    i.status AS invoice_status,
    i.total_due_minor AS invoice_total_due_minor,
    i.amount_paid_minor AS invoice_amount_paid_minor,
    i.currency_code AS invoice_currency_code,
    i.paid_at AS invoice_paid_at,
    i.payment_failed_at AS invoice_payment_failed_at
FROM payment_attempts pa
JOIN invoices i ON i.tenant_id = pa.tenant_id AND i.branch_id = pa.branch_id AND i.id = pa.invoice_id
WHERE pa.tenant_id = $1
  AND pa.branch_id = $2
  AND pa.invoice_id = $3
  AND pa.id = $4
  AND pa.stripe_checkout_session_id = $5
FOR UPDATE OF pa, i
`

type GetPaymentAttemptAndInvoiceForWebhookParams struct {
	TenantID                pgtype.UUID
	BranchID                pgtype.UUID
	InvoiceID               pgtype.UUID
	ID                      pgtype.UUID
	StripeCheckoutSessionID pgtype.Text
}

type GetPaymentAttemptAndInvoiceForWebhookRow struct {
	AttemptID              pgtype.UUID
	AttemptStatus          string
	AttemptAmountMinor     int32
	AttemptCurrencyCode    string
	AttemptSessionID       pgtype.Text
	InvoiceID              pgtype.UUID
	InvoiceStatus          string
	InvoiceTotalDueMinor   int32
	InvoiceAmountPaidMinor int32
	InvoiceCurrencyCode    string
	InvoicePaidAt          pgtype.Timestamptz
	InvoicePaymentFailedAt pgtype.Timestamptz
}

func (q *Queries) GetPaymentAttemptAndInvoiceForWebhook(ctx context.Context, arg GetPaymentAttemptAndInvoiceForWebhookParams) (GetPaymentAttemptAndInvoiceForWebhookRow, error) {
	row := q.db.QueryRow(ctx, getPaymentAttemptAndInvoiceForWebhook,
		arg.TenantID,
		arg.BranchID,
		arg.InvoiceID,
		arg.ID,
		arg.StripeCheckoutSessionID,
	)
	var i GetPaymentAttemptAndInvoiceForWebhookRow
	err := row.Scan(
		&i.AttemptID,
		&i.AttemptStatus,
		&i.AttemptAmountMinor,
		&i.AttemptCurrencyCode,
		&i.AttemptSessionID,
		&i.InvoiceID,
		&i.InvoiceStatus,
		&i.InvoiceTotalDueMinor,
		&i.InvoiceAmountPaidMinor,
		&i.InvoiceCurrencyCode,
		&i.InvoicePaidAt,
		&i.InvoicePaymentFailedAt,
	)
	return i, err
}

const getWebhookEventByStripeEventID = `-- name: GetWebhookEventByStripeEventID :one
SELECT id, stripe_event_id, event_type, processing_status, processing_reason
FROM stripe_webhook_events
WHERE stripe_event_id = $1
`

type GetWebhookEventByStripeEventIDRow struct {
	ID               pgtype.UUID
	StripeEventID    string
	EventType        string
	ProcessingStatus string
	ProcessingReason pgtype.Text
}

func (q *Queries) GetWebhookEventByStripeEventID(ctx context.Context, stripeEventID string) (GetWebhookEventByStripeEventIDRow, error) {
	row := q.db.QueryRow(ctx, getWebhookEventByStripeEventID, stripeEventID)
	var i GetWebhookEventByStripeEventIDRow
	err := row.Scan(
		&i.ID,
		&i.StripeEventID,
		&i.EventType,
		&i.ProcessingStatus,
		&i.ProcessingReason,
	)
	return i, err
}

const insertReconciliationRecord = `-- name: InsertReconciliationRecord :exec
INSERT INTO payment_reconciliation_records (
    id, tenant_id, branch_id, invoice_id, payment_attempt_id,
    stripe_webhook_event_id, stripe_event_id, stripe_event_type,
    stripe_checkout_session_id, stripe_payment_intent_id,
    outcome, reason_code,
    previous_invoice_status, new_invoice_status,
    attempt_previous_status, attempt_new_status,
    amount_minor, currency_code, details
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19)
`

type InsertReconciliationRecordParams struct {
	ID                      pgtype.UUID
	TenantID                pgtype.UUID
	BranchID                pgtype.UUID
	InvoiceID               pgtype.UUID
	PaymentAttemptID        pgtype.UUID
	StripeWebhookEventID    pgtype.UUID
	StripeEventID           string
	StripeEventType         string
	StripeCheckoutSessionID string
	StripePaymentIntentID   pgtype.Text
	Outcome                 string
	ReasonCode              string
	PreviousInvoiceStatus   pgtype.Text
	NewInvoiceStatus        pgtype.Text
	AttemptPreviousStatus   pgtype.Text
	AttemptNewStatus        pgtype.Text
	AmountMinor             pgtype.Int4
	CurrencyCode            pgtype.Text
	Details                 []byte
}

func (q *Queries) InsertReconciliationRecord(ctx context.Context, arg InsertReconciliationRecordParams) error {
	_, err := q.db.Exec(ctx, insertReconciliationRecord,
		arg.ID,
		arg.TenantID,
		arg.BranchID,
		arg.InvoiceID,
		arg.PaymentAttemptID,
		arg.StripeWebhookEventID,
		arg.StripeEventID,
		arg.StripeEventType,
		arg.StripeCheckoutSessionID,
		arg.StripePaymentIntentID,
		arg.Outcome,
		arg.ReasonCode,
		arg.PreviousInvoiceStatus,
		arg.NewInvoiceStatus,
		arg.AttemptPreviousStatus,
		arg.AttemptNewStatus,
		arg.AmountMinor,
		arg.CurrencyCode,
		arg.Details,
	)
	return err
}

const insertWebhookEvent = `-- name: InsertWebhookEvent :one
INSERT INTO stripe_webhook_events (
    id, stripe_event_id, event_type, livemode, api_version,
    provider_created_at, processing_status, processing_reason,
    request_id, raw_payload
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (stripe_event_id) DO NOTHING
RETURNING id
`

type InsertWebhookEventParams struct {
	ID                pgtype.UUID
	StripeEventID     string
	EventType         string
	Livemode          bool
	ApiVersion        pgtype.Text
	ProviderCreatedAt pgtype.Timestamptz
	ProcessingStatus  string
	ProcessingReason  pgtype.Text
	RequestID         pgtype.Text
	RawPayload        []byte
}

func (q *Queries) InsertWebhookEvent(ctx context.Context, arg InsertWebhookEventParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertWebhookEvent,
		arg.ID,
		arg.StripeEventID,
		arg.EventType,
		arg.Livemode,
		arg.ApiVersion,
		arg.ProviderCreatedAt,
		arg.ProcessingStatus,
		arg.ProcessingReason,
		arg.RequestID,
		arg.RawPayload,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const markInvoicePaid = `-- name: MarkInvoicePaid :execrows
UPDATE invoices
SET status = 'paid',
    amount_paid_minor = total_due_minor,
    paid_at = COALESCE(paid_at, now()),
    payment_status_updated_at = now(),
    updated_at = now()
WHERE tenant_id = $1
  AND branch_id = $2
  AND id = $3
  AND status IN ('issued', 'overdue', 'payment_failed')
`

type MarkInvoicePaidParams struct {
	TenantID pgtype.UUID
	BranchID pgtype.UUID
	ID       pgtype.UUID
}

func (q *Queries) MarkInvoicePaid(ctx context.Context, arg MarkInvoicePaidParams) (int64, error) {
	result, err := q.db.Exec(ctx, markInvoicePaid, arg.TenantID, arg.BranchID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markInvoicePaymentFailed = `-- name: MarkInvoicePaymentFailed :execrows
UPDATE invoices
SET status = 'payment_failed',
    payment_failed_at = COALESCE(payment_failed_at, now()),
    payment_status_updated_at = now(),
    updated_at = now()
WHERE tenant_id = $1
  AND branch_id = $2
  AND id = $3
  AND status IN ('issued', 'overdue')
`

type MarkInvoicePaymentFailedParams struct {
	TenantID pgtype.UUID
	BranchID pgtype.UUID
	ID       pgtype.UUID
}

func (q *Queries) MarkInvoicePaymentFailed(ctx context.Context, arg MarkInvoicePaymentFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markInvoicePaymentFailed, arg.TenantID, arg.BranchID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markPaymentAttemptExpired = `-- name: MarkPaymentAttemptExpired :execrows
UPDATE payment_attempts
SET status = 'expired',
    updated_at = now()
WHERE tenant_id = $1
  AND branch_id = $2
  AND id = $3
  AND status IN ('checkout_created')
`

type MarkPaymentAttemptExpiredParams struct {
	TenantID pgtype.UUID
	BranchID pgtype.UUID
	ID       pgtype.UUID
}

func (q *Queries) MarkPaymentAttemptExpired(ctx context.Context, arg MarkPaymentAttemptExpiredParams) (int64, error) {
	result, err := q.db.Exec(ctx, markPaymentAttemptExpired, arg.TenantID, arg.BranchID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markPaymentAttemptFailed = `-- name: MarkPaymentAttemptFailed :execrows
UPDATE payment_attempts
SET status = 'payment_failed',
    updated_at = now()
WHERE tenant_id = $1
  AND branch_id = $2
  AND id = $3
  AND status IN ('checkout_created')
`

type MarkPaymentAttemptFailedParams struct {
	TenantID pgtype.UUID
	BranchID pgtype.UUID
	ID       pgtype.UUID
}

func (q *Queries) MarkPaymentAttemptFailed(ctx context.Context, arg MarkPaymentAttemptFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markPaymentAttemptFailed, arg.TenantID, arg.BranchID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markPaymentAttemptPaid = `-- name: MarkPaymentAttemptPaid :execrows
UPDATE payment_attempts
SET status = 'paid',
    updated_at = now()
WHERE tenant_id = $1
  AND branch_id = $2
  AND id = $3
  AND status IN ('checkout_created', 'payment_failed')
`

type MarkPaymentAttemptPaidParams struct {
	TenantID pgtype.UUID
	BranchID pgtype.UUID
	ID       pgtype.UUID
}

func (q *Queries) MarkPaymentAttemptPaid(ctx context.Context, arg MarkPaymentAttemptPaidParams) (int64, error) {
	result, err := q.db.Exec(ctx, markPaymentAttemptPaid, arg.TenantID, arg.BranchID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateWebhookEventStatus = `-- name: UpdateWebhookEventStatus :execrows
UPDATE stripe_webhook_events
SET processing_status = $2,
    processing_reason = $3,
    processed_at = now(),
    error_message = $4,
    updated_at = now()
WHERE id = $1
`

type UpdateWebhookEventStatusParams struct {
	ID               pgtype.UUID
	ProcessingStatus string
	ProcessingReason pgtype.Text
	ErrorMessage     pgtype.Text
}

func (q *Queries) UpdateWebhookEventStatus(ctx context.Context, arg UpdateWebhookEventStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateWebhookEventStatus,
		arg.ID,
		arg.ProcessingStatus,
		arg.ProcessingReason,
		arg.ErrorMessage,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
