// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants_branches.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listAllTenantBranches = `-- name: ListAllTenantBranches :many
SELECT tenant_id, id AS branch_id
FROM branches
WHERE is_active = true
ORDER BY tenant_id, id
`

type ListAllTenantBranchesRow struct {
	TenantID pgtype.UUID
	BranchID pgtype.UUID
}

func (q *Queries) ListAllTenantBranches(ctx context.Context) ([]ListAllTenantBranchesRow, error) {
	rows, err := q.db.Query(ctx, listAllTenantBranches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllTenantBranchesRow
	for rows.Next() {
		var i ListAllTenantBranchesRow
		if err := rows.Scan(&i.TenantID, &i.BranchID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
