-- name: RegistrationProfileGetByChild :one
SELECT
    crp.id,
    crp.tenant_id,
    crp.branch_id,
    crp.child_id,
    c.full_name AS child_full_name,
    c.date_of_birth AS child_date_of_birth,
    crp.sex,
    crp.religion,
    crp.ethnic_origin,
    crp.first_language,
    crp.other_languages,
    crp.home_address,
    crp.home_postcode,
    crp.home_telephone,
    crp.disability_status::text,
    crp.disability_notes,
    crp.access_requirements,
    crp.medical_conditions_status::text,
    crp.medical_conditions_notes,
    crp.prescribed_medication_status::text,
    crp.medication_notes,
    crp.immunisation_status::text,
    crp.immunisation_country,
    crp.illness_diagnosis_history,
    crp.dietary_requirements_status::text,
    crp.dietary_requirements_notes,
    crp.dietary_side_effects,
    crp.doctor_name,
    crp.doctor_address,
    crp.doctor_phone,
    crp.health_visitor_name,
    crp.health_visitor_address,
    crp.health_visitor_phone,
    crp.social_services_status::text,
    crp.social_services_notes,
    crp.social_worker_name,
    crp.social_worker_phone,
    crp.social_worker_email,
    crp.concern_walking::text,
    crp.concern_speech_language::text,
    crp.concern_hearing::text,
    crp.concern_sight::text,
    crp.concern_emotional_wellbeing::text,
    crp.concern_behaviour::text,
    crp.professional_referrals,
    crp.parental_responsibility_notes,
    crp.over18_collection_acknowledged,
    crp.collection_password_hash IS NOT NULL AND crp.collection_password_hash <> '' AS collection_password_is_set,
    crp.collection_password_updated_at,
    crp.collection_password_updated_by_user_id,
    crp.collection_password_updated_by_membership_id,
    crp.benefits_contribute_to_fees::text,
    crp.working_tax_credit::text,
    crp.college_uni_paid_to_parent::text,
    crp.college_uni_paid_to_nursery::text,
    crp.funding_3yo_term_time::text,
    crp.funding_2yo_term_time::text,
    crp.funding_support_notes,
    crp.routine_care_notes,
    crp.gdpr_declared_by_name,
    crp.gdpr_declared_at,
    crp.gdpr_declaration_date,
    crp.demographics_home_reviewed,
    crp.medical_dietary_reviewed,
    crp.health_contacts_reviewed,
    crp.social_development_reviewed,
    crp.parent_responsibility_reviewed,
    crp.emergency_collection_reviewed,
    crp.funding_support_reviewed,
    crp.routine_care_reviewed,
    crp.created_at,
    crp.updated_at
FROM child_registration_profiles crp
JOIN children c ON c.tenant_id = crp.tenant_id AND c.branch_id = crp.branch_id AND c.id = crp.child_id
WHERE crp.tenant_id = $1
  AND crp.branch_id = $2
  AND crp.child_id = $3;

-- name: RegistrationProfileListContacts :many
SELECT
    crc.id,
    crc.tenant_id,
    crc.branch_id,
    crc.profile_id,
    crc.child_id,
    crc.contact_type::text,
    crc.sort_order,
    crc.full_name,
    crc.relationship_to_child,
    crc.address,
    crc.telephone,
    crc.email,
    crc.work_address,
    crc.has_parental_responsibility,
    crc.created_at,
    crc.updated_at
FROM child_registration_contacts crc
WHERE crc.tenant_id = $1
  AND crc.branch_id = $2
  AND crc.profile_id = $3
ORDER BY crc.contact_type, crc.sort_order;

-- name: RegistrationProfileChildGet :one
SELECT
    c.id,
    c.full_name,
    c.date_of_birth
FROM children c
WHERE c.tenant_id = $1
  AND c.branch_id = $2
  AND c.id = $3;

-- name: RegistrationProfileGetForUpdateByChild :one
SELECT
    crp.id,
    crp.tenant_id,
    crp.branch_id,
    crp.child_id,
    c.full_name AS child_full_name,
    c.date_of_birth AS child_date_of_birth,
    crp.sex,
    crp.religion,
    crp.ethnic_origin,
    crp.first_language,
    crp.other_languages,
    crp.home_address,
    crp.home_postcode,
    crp.home_telephone,
    crp.disability_status::text,
    crp.disability_notes,
    crp.access_requirements,
    crp.medical_conditions_status::text,
    crp.medical_conditions_notes,
    crp.prescribed_medication_status::text,
    crp.medication_notes,
    crp.immunisation_status::text,
    crp.immunisation_country,
    crp.illness_diagnosis_history,
    crp.dietary_requirements_status::text,
    crp.dietary_requirements_notes,
    crp.dietary_side_effects,
    crp.doctor_name,
    crp.doctor_address,
    crp.doctor_phone,
    crp.health_visitor_name,
    crp.health_visitor_address,
    crp.health_visitor_phone,
    crp.social_services_status::text,
    crp.social_services_notes,
    crp.social_worker_name,
    crp.social_worker_phone,
    crp.social_worker_email,
    crp.concern_walking::text,
    crp.concern_speech_language::text,
    crp.concern_hearing::text,
    crp.concern_sight::text,
    crp.concern_emotional_wellbeing::text,
    crp.concern_behaviour::text,
    crp.professional_referrals,
    crp.parental_responsibility_notes,
    crp.over18_collection_acknowledged,
    crp.collection_password_hash IS NOT NULL AND crp.collection_password_hash <> '' AS collection_password_is_set,
    crp.collection_password_updated_at,
    crp.collection_password_updated_by_user_id,
    crp.collection_password_updated_by_membership_id,
    crp.benefits_contribute_to_fees::text,
    crp.working_tax_credit::text,
    crp.college_uni_paid_to_parent::text,
    crp.college_uni_paid_to_nursery::text,
    crp.funding_3yo_term_time::text,
    crp.funding_2yo_term_time::text,
    crp.funding_support_notes,
    crp.routine_care_notes,
    crp.gdpr_declared_by_name,
    crp.gdpr_declared_at,
    crp.gdpr_declaration_date,
    crp.demographics_home_reviewed,
    crp.medical_dietary_reviewed,
    crp.health_contacts_reviewed,
    crp.social_development_reviewed,
    crp.parent_responsibility_reviewed,
    crp.emergency_collection_reviewed,
    crp.funding_support_reviewed,
    crp.routine_care_reviewed,
    crp.created_at,
    crp.updated_at
FROM child_registration_profiles crp
JOIN children c ON c.tenant_id = crp.tenant_id AND c.branch_id = crp.branch_id AND c.id = crp.child_id
WHERE crp.tenant_id = $1
  AND crp.branch_id = $2
  AND crp.child_id = $3
FOR UPDATE OF crp;

-- name: RegistrationProfileCreate :one
INSERT INTO child_registration_profiles (
    id, tenant_id, branch_id, child_id,
    sex, religion, ethnic_origin, first_language, other_languages,
    home_address, home_postcode, home_telephone,
    disability_status, disability_notes, access_requirements,
    medical_conditions_status, medical_conditions_notes,
    prescribed_medication_status, medication_notes,
    immunisation_status, immunisation_country, illness_diagnosis_history,
    dietary_requirements_status, dietary_requirements_notes, dietary_side_effects,
    doctor_name, doctor_address, doctor_phone,
    health_visitor_name, health_visitor_address, health_visitor_phone,
    social_services_status, social_services_notes,
    social_worker_name, social_worker_phone, social_worker_email,
    concern_walking, concern_speech_language, concern_hearing, concern_sight,
    concern_emotional_wellbeing, concern_behaviour, professional_referrals,
    parental_responsibility_notes,
    over18_collection_acknowledged,
    benefits_contribute_to_fees, working_tax_credit,
    college_uni_paid_to_parent, college_uni_paid_to_nursery,
    funding_3yo_term_time, funding_2yo_term_time, funding_support_notes,
    routine_care_notes,
    gdpr_declared_by_name, gdpr_declared_at, gdpr_declaration_date,
    demographics_home_reviewed, medical_dietary_reviewed, health_contacts_reviewed,
    social_development_reviewed, parent_responsibility_reviewed,
    emergency_collection_reviewed, funding_support_reviewed, routine_care_reviewed
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8, $9,
    $10, $11, $12,
    $13, $14, $15,
    $16, $17,
    $18, $19,
    $20, $21, $22,
    $23, $24, $25,
    $26, $27, $28,
    $29, $30, $31,
    $32, $33,
    $34, $35, $36,
    $37, $38, $39, $40,
    $41, $42, $43,
    $44,
    $45,
    $46, $47,
    $48, $49,
    $50, $51, $52,
    $53,
    $54, $55, $56,
    $57, $58, $59,
    $60, $61,
    $62, $63, $64
)
RETURNING
    id, tenant_id, branch_id, child_id,
    sex, religion, ethnic_origin, first_language, other_languages,
    home_address, home_postcode, home_telephone,
    disability_status::text, disability_notes, access_requirements,
    medical_conditions_status::text, medical_conditions_notes,
    prescribed_medication_status::text, medication_notes,
    immunisation_status::text, immunisation_country, illness_diagnosis_history,
    dietary_requirements_status::text, dietary_requirements_notes, dietary_side_effects,
    doctor_name, doctor_address, doctor_phone,
    health_visitor_name, health_visitor_address, health_visitor_phone,
    social_services_status::text, social_services_notes,
    social_worker_name, social_worker_phone, social_worker_email,
    concern_walking::text, concern_speech_language::text, concern_hearing::text, concern_sight::text,
    concern_emotional_wellbeing::text, concern_behaviour::text, professional_referrals,
    parental_responsibility_notes,
    over18_collection_acknowledged,
    FALSE AS collection_password_is_set,
    NULL::timestamptz AS collection_password_updated_at,
    NULL::uuid AS collection_password_updated_by_user_id,
    NULL::uuid AS collection_password_updated_by_membership_id,
    benefits_contribute_to_fees::text, working_tax_credit::text,
    college_uni_paid_to_parent::text, college_uni_paid_to_nursery::text,
    funding_3yo_term_time::text, funding_2yo_term_time::text, funding_support_notes,
    routine_care_notes,
    gdpr_declared_by_name, gdpr_declared_at, gdpr_declaration_date,
    demographics_home_reviewed, medical_dietary_reviewed, health_contacts_reviewed,
    social_development_reviewed, parent_responsibility_reviewed,
    emergency_collection_reviewed, funding_support_reviewed, routine_care_reviewed,
    created_at, updated_at;

-- name: RegistrationProfileUpdate :one
UPDATE child_registration_profiles crp
SET
    sex = $4,
    religion = $5,
    ethnic_origin = $6,
    first_language = $7,
    other_languages = $8,
    home_address = $9,
    home_postcode = $10,
    home_telephone = $11,
    disability_status = $12,
    disability_notes = $13,
    access_requirements = $14,
    medical_conditions_status = $15,
    medical_conditions_notes = $16,
    prescribed_medication_status = $17,
    medication_notes = $18,
    immunisation_status = $19,
    immunisation_country = $20,
    illness_diagnosis_history = $21,
    dietary_requirements_status = $22,
    dietary_requirements_notes = $23,
    dietary_side_effects = $24,
    doctor_name = $25,
    doctor_address = $26,
    doctor_phone = $27,
    health_visitor_name = $28,
    health_visitor_address = $29,
    health_visitor_phone = $30,
    social_services_status = $31,
    social_services_notes = $32,
    social_worker_name = $33,
    social_worker_phone = $34,
    social_worker_email = $35,
    concern_walking = $36,
    concern_speech_language = $37,
    concern_hearing = $38,
    concern_sight = $39,
    concern_emotional_wellbeing = $40,
    concern_behaviour = $41,
    professional_referrals = $42,
    parental_responsibility_notes = $43,
    over18_collection_acknowledged = $44,
    benefits_contribute_to_fees = $45,
    working_tax_credit = $46,
    college_uni_paid_to_parent = $47,
    college_uni_paid_to_nursery = $48,
    funding_3yo_term_time = $49,
    funding_2yo_term_time = $50,
    funding_support_notes = $51,
    routine_care_notes = $52,
    gdpr_declared_by_name = $53,
    gdpr_declared_at = $54,
    gdpr_declaration_date = $55,
    demographics_home_reviewed = $56,
    medical_dietary_reviewed = $57,
    health_contacts_reviewed = $58,
    social_development_reviewed = $59,
    parent_responsibility_reviewed = $60,
    emergency_collection_reviewed = $61,
    funding_support_reviewed = $62,
    routine_care_reviewed = $63,
    updated_at = now()
WHERE crp.tenant_id = $1
  AND crp.branch_id = $2
  AND crp.child_id = $3
RETURNING
    id, tenant_id, branch_id, child_id,
    sex, religion, ethnic_origin, first_language, other_languages,
    home_address, home_postcode, home_telephone,
    disability_status::text, disability_notes, access_requirements,
    medical_conditions_status::text, medical_conditions_notes,
    prescribed_medication_status::text, medication_notes,
    immunisation_status::text, immunisation_country, illness_diagnosis_history,
    dietary_requirements_status::text, dietary_requirements_notes, dietary_side_effects,
    doctor_name, doctor_address, doctor_phone,
    health_visitor_name, health_visitor_address, health_visitor_phone,
    social_services_status::text, social_services_notes,
    social_worker_name, social_worker_phone, social_worker_email,
    concern_walking::text, concern_speech_language::text, concern_hearing::text, concern_sight::text,
    concern_emotional_wellbeing::text, concern_behaviour::text, professional_referrals,
    parental_responsibility_notes,
    over18_collection_acknowledged,
    collection_password_hash IS NOT NULL AND crp.collection_password_hash <> '' AS collection_password_is_set,
    collection_password_updated_at, collection_password_updated_by_user_id, collection_password_updated_by_membership_id,
    benefits_contribute_to_fees::text, working_tax_credit::text,
    college_uni_paid_to_parent::text, college_uni_paid_to_nursery::text,
    funding_3yo_term_time::text, funding_2yo_term_time::text, funding_support_notes,
    routine_care_notes,
    gdpr_declared_by_name, gdpr_declared_at, gdpr_declaration_date,
    demographics_home_reviewed, medical_dietary_reviewed, health_contacts_reviewed,
    social_development_reviewed, parent_responsibility_reviewed,
    emergency_collection_reviewed, funding_support_reviewed, routine_care_reviewed,
    created_at, updated_at;

-- name: RegistrationProfileSetCollectionPassword :one
UPDATE child_registration_profiles
SET
    collection_password_hash = $4,
    collection_password_updated_at = $5,
    collection_password_updated_by_user_id = $6,
    collection_password_updated_by_membership_id = $7,
    updated_at = now()
WHERE tenant_id = $1
  AND branch_id = $2
  AND child_id = $3
RETURNING
    id, tenant_id, branch_id, child_id,
    sex, religion, ethnic_origin, first_language, other_languages,
    home_address, home_postcode, home_telephone,
    disability_status::text, disability_notes, access_requirements,
    medical_conditions_status::text, medical_conditions_notes,
    prescribed_medication_status::text, medication_notes,
    immunisation_status::text, immunisation_country, illness_diagnosis_history,
    dietary_requirements_status::text, dietary_requirements_notes, dietary_side_effects,
    doctor_name, doctor_address, doctor_phone,
    health_visitor_name, health_visitor_address, health_visitor_phone,
    social_services_status::text, social_services_notes,
    social_worker_name, social_worker_phone, social_worker_email,
    concern_walking::text, concern_speech_language::text, concern_hearing::text, concern_sight::text,
    concern_emotional_wellbeing::text, concern_behaviour::text, professional_referrals,
    parental_responsibility_notes,
    over18_collection_acknowledged,
    collection_password_hash IS NOT NULL AND child_registration_profiles.collection_password_hash <> '' AS collection_password_is_set,
    collection_password_updated_at, collection_password_updated_by_user_id, collection_password_updated_by_membership_id,
    benefits_contribute_to_fees::text, working_tax_credit::text,
    college_uni_paid_to_parent::text, college_uni_paid_to_nursery::text,
    funding_3yo_term_time::text, funding_2yo_term_time::text, funding_support_notes,
    routine_care_notes,
    gdpr_declared_by_name, gdpr_declared_at, gdpr_declaration_date,
    demographics_home_reviewed, medical_dietary_reviewed, health_contacts_reviewed,
    social_development_reviewed, parent_responsibility_reviewed,
    emergency_collection_reviewed, funding_support_reviewed, routine_care_reviewed,
    created_at, updated_at;

-- name: RegistrationProfileDeleteContactsByTypes :exec
DELETE FROM child_registration_contacts
WHERE tenant_id = $1
  AND branch_id = $2
  AND profile_id = $3
  AND contact_type::text = ANY(sqlc.arg('contact_types')::text[]);

-- name: RegistrationProfileCreateContact :one
INSERT INTO child_registration_contacts (
    id, tenant_id, branch_id, profile_id, child_id,
    contact_type, sort_order, full_name, relationship_to_child,
    address, telephone, email, work_address, has_parental_responsibility
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9,
    $10, $11, $12, $13, $14
)
RETURNING
    id, tenant_id, branch_id, profile_id, child_id,
    contact_type::text, sort_order, full_name, relationship_to_child,
    address, telephone, email, work_address, has_parental_responsibility,
    created_at, updated_at;
