// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"github.com/jackc/pgx/v5/pgxpool"
	"log/slog"
	application19 "nursery-management-system/api/internal/modules/absence/application"
	domain2 "nursery-management-system/api/internal/modules/absence/domain"
	postgres9 "nursery-management-system/api/internal/modules/absence/infrastructure/postgres"
	"nursery-management-system/api/internal/modules/absence/interfaces/http"
	application17 "nursery-management-system/api/internal/modules/ad_hoc_bookings/application"
	domain17 "nursery-management-system/api/internal/modules/ad_hoc_bookings/domain"
	postgres19 "nursery-management-system/api/internal/modules/ad_hoc_bookings/infrastructure/postgres"
	"nursery-management-system/api/internal/modules/ad_hoc_bookings/interfaces/http"
	application5 "nursery-management-system/api/internal/modules/attendance/application"
	domain7 "nursery-management-system/api/internal/modules/attendance/domain"
	postgres8 "nursery-management-system/api/internal/modules/attendance/infrastructure/postgres"
	"nursery-management-system/api/internal/modules/attendance/interfaces/http"
	"nursery-management-system/api/internal/modules/authentication/application"
	"nursery-management-system/api/internal/modules/authentication/domain"
	"nursery-management-system/api/internal/modules/authentication/infrastructure/postgres"
	"nursery-management-system/api/internal/modules/authentication/infrastructure/tokens"
	"nursery-management-system/api/internal/modules/authentication/interfaces/http"
	application7 "nursery-management-system/api/internal/modules/billing/application"
	domain8 "nursery-management-system/api/internal/modules/billing/domain"
	postgres11 "nursery-management-system/api/internal/modules/billing/infrastructure/postgres"
	"nursery-management-system/api/internal/modules/billing/interfaces/http"
	application18 "nursery-management-system/api/internal/modules/branch_closures/application"
	domain18 "nursery-management-system/api/internal/modules/branch_closures/domain"
	postgres13 "nursery-management-system/api/internal/modules/branch_closures/infrastructure/postgres"
	"nursery-management-system/api/internal/modules/branch_closures/interfaces/http"
	application3 "nursery-management-system/api/internal/modules/children/application"
	domain5 "nursery-management-system/api/internal/modules/children/domain"
	postgres3 "nursery-management-system/api/internal/modules/children/infrastructure/postgres"
	"nursery-management-system/api/internal/modules/children/interfaces/http"
	application6 "nursery-management-system/api/internal/modules/funding/application"
	domain3 "nursery-management-system/api/internal/modules/funding/domain"
	postgres10 "nursery-management-system/api/internal/modules/funding/infrastructure/postgres"
	"nursery-management-system/api/internal/modules/funding/interfaces/http"
	application10 "nursery-management-system/api/internal/modules/invites/application"
	domain10 "nursery-management-system/api/internal/modules/invites/domain"
	postgres16 "nursery-management-system/api/internal/modules/invites/infrastructure/postgres"
	"nursery-management-system/api/internal/modules/invites/interfaces/http"
	application11 "nursery-management-system/api/internal/modules/owner/application"
	domain11 "nursery-management-system/api/internal/modules/owner/domain"
	postgres6 "nursery-management-system/api/internal/modules/owner/infrastructure/postgres"
	"nursery-management-system/api/internal/modules/owner/interfaces/http"
	application4 "nursery-management-system/api/internal/modules/parentchildmappings/application"
	domain6 "nursery-management-system/api/internal/modules/parentchildmappings/domain"
	postgres7 "nursery-management-system/api/internal/modules/parentchildmappings/infrastructure/postgres"
	"nursery-management-system/api/internal/modules/parentchildmappings/interfaces/http"
	application2 "nursery-management-system/api/internal/modules/passwordreset/application"
	domain4 "nursery-management-system/api/internal/modules/passwordreset/domain"
	postgres2 "nursery-management-system/api/internal/modules/passwordreset/infrastructure/postgres"
	"nursery-management-system/api/internal/modules/passwordreset/interfaces/http"
	application9 "nursery-management-system/api/internal/modules/payments/application"
	domain9 "nursery-management-system/api/internal/modules/payments/domain"
	postgres15 "nursery-management-system/api/internal/modules/payments/infrastructure/postgres"
	"nursery-management-system/api/internal/modules/payments/infrastructure/stripe"
	application12 "nursery-management-system/api/internal/modules/rooms/application"
	domain12 "nursery-management-system/api/internal/modules/rooms/domain"
	postgres17 "nursery-management-system/api/internal/modules/rooms/infrastructure/postgres"
	"nursery-management-system/api/internal/modules/rooms/interfaces/http"
	application14 "nursery-management-system/api/internal/modules/sessiontemplates/application"
	domain13 "nursery-management-system/api/internal/modules/sessiontemplates/domain"
	postgres18 "nursery-management-system/api/internal/modules/sessiontemplates/infrastructure/postgres"
	"nursery-management-system/api/internal/modules/sessiontemplates/interfaces/http"
	application13 "nursery-management-system/api/internal/modules/sessiontypes/application"
	postgres4 "nursery-management-system/api/internal/modules/sessiontypes/infrastructure/postgres"
	"nursery-management-system/api/internal/modules/sessiontypes/interfaces/http"
	application8 "nursery-management-system/api/internal/modules/siteprofile/application"
	domain15 "nursery-management-system/api/internal/modules/siteprofile/domain"
	postgres14 "nursery-management-system/api/internal/modules/siteprofile/infrastructure/postgres"
	"nursery-management-system/api/internal/modules/siteprofile/interfaces/http"
	application15 "nursery-management-system/api/internal/modules/term/application"
	domain14 "nursery-management-system/api/internal/modules/term/domain"
	postgres5 "nursery-management-system/api/internal/modules/term/infrastructure/postgres"
	"nursery-management-system/api/internal/modules/term/interfaces/http"
	application16 "nursery-management-system/api/internal/modules/term_calendar/application"
	domain16 "nursery-management-system/api/internal/modules/term_calendar/domain"
	postgres12 "nursery-management-system/api/internal/modules/term_calendar/infrastructure/postgres"
	"nursery-management-system/api/internal/modules/term_calendar/interfaces/http"
	"nursery-management-system/api/internal/platform/audit"
	"nursery-management-system/api/internal/platform/config"
	"nursery-management-system/api/internal/platform/metrics"
	"nursery-management-system/api/internal/platform/ratelimit"
	"nursery-management-system/api/internal/platform/transaction"
	"time"
)

// Injectors from wire.go:

func InitializeApp(cfg config.Config, logger *slog.Logger, pool *pgxpool.Pool) (*gin.Engine, error) {
	registry := provideMetricsRegistry(cfg)
	recorder := provideMetricsRecorder(cfg, registry)
	tokenManager := provideTokenManager(cfg)
	tokenParser := provideTokenParserAdapter(tokenManager)
	repository := postgres.NewRepository(pool)
	loginUseCase := application.NewLoginUseCase(repository, repository, tokenManager)
	refreshUseCase := application.NewRefreshUseCase(repository, repository, tokenManager)
	logoutUseCase := application.NewLogoutUseCase(repository, tokenManager)
	switchMembershipUseCase := application.NewSwitchMembershipUseCase(repository, repository, tokenManager)
	handler := httpauth.NewHandler(loginUseCase, refreshUseCase, logoutUseCase, switchMembershipUseCase, cfg, recorder, logger)
	postgresRepository := postgres2.NewRepository(pool)
	sender := provideEmailSender(cfg)
	emailAdapter := application2.NewEmailAdapter(sender)
	manager := provideResetTokenManager(cfg)
	tokenGeneratorAdapter := application2.NewTokenGeneratorAdapter(manager)
	string2 := provideWebBaseURL(cfg)
	requestResetUseCase := application2.NewRequestResetUseCase(postgresRepository, emailAdapter, tokenGeneratorAdapter, string2, logger)
	setNewPasswordUseCase := application2.NewSetNewPasswordUseCase(postgresRepository, logger)
	httpresetHandler := provideResetHandler(requestResetUseCase, setNewPasswordUseCase, recorder, logger)
	childRepository := postgres3.NewChildRepository(pool)
	listChildren := application3.NewListChildren(childRepository)
	getChild := application3.NewGetChild(childRepository)
	writer := provideAuditWriter()
	transactionManager := provideTxManager(pool)
	sessionTypeRepository := postgres4.NewRepository(pool)
	bootstrapSessionTypeLookupAdapter := provideSessionTypeLookupAdapter(sessionTypeRepository)
	termRepository := postgres5.NewTermRepository(pool)
	ownerRepository := postgres6.NewRepository(pool)
	bootstrapSiteRateProviderAdapter := provideSiteRateProviderAdapter(ownerRepository)
	bootstrapEnrollmentTermCreatorAdapter := provideEnrollmentTermCreatorAdapter(termRepository, bootstrapSiteRateProviderAdapter, writer)
	todayFunc := provideTodayFunc()
	createChildWithFullProfile := application3.NewCreateChildWithFullProfile(childRepository, writer, transactionManager, bootstrapSessionTypeLookupAdapter, bootstrapEnrollmentTermCreatorAdapter, todayFunc)
	updateChild := application3.NewUpdateChild(childRepository, writer, transactionManager)
	eventDispatcher := provideEventDispatcher(transactionManager)
	markInactive := application3.NewMarkInactive(childRepository, eventDispatcher, writer)
	v := provideClock()
	listAttendance := application3.NewListAttendance(childRepository, v)
	coreUseCases := httpchild.CoreUseCases{
		List:           listChildren,
		Get:            getChild,
		Create:         createChildWithFullProfile,
		Update:         updateChild,
		MarkInactive:   markInactive,
		ListAttendance: listAttendance,
	}
	getProfile := application3.NewGetProfile(childRepository)
	updateProfile := application3.NewUpdateProfile(childRepository, writer, transactionManager)
	profileUseCases := httpchild.ProfileUseCases{
		Get:    getProfile,
		Update: updateProfile,
	}
	getContacts := application3.NewGetContacts(childRepository)
	replaceContacts := application3.NewReplaceContacts(childRepository, writer, transactionManager)
	contactsUseCases := httpchild.ContactsUseCases{
		Get:     getContacts,
		Replace: replaceContacts,
	}
	getHealth := application3.NewGetHealth(childRepository)
	updateHealth := application3.NewUpdateHealth(childRepository, writer, transactionManager)
	healthUseCases := httpchild.HealthUseCases{
		Get:    getHealth,
		Update: updateHealth,
	}
	getSafeguarding := application3.NewGetSafeguarding(childRepository)
	updateSafeguarding := application3.NewUpdateSafeguarding(childRepository, writer, transactionManager)
	safeguardingUseCases := httpchild.SafeguardingUseCases{
		Get:    getSafeguarding,
		Update: updateSafeguarding,
	}
	getConsent := application3.NewGetConsent(childRepository)
	updateConsent := application3.NewUpdateConsent(childRepository, writer, transactionManager)
	consentUseCases := httpchild.ConsentUseCases{
		Get:    getConsent,
		Update: updateConsent,
	}
	getFunding := application3.NewGetFunding(childRepository)
	updateFunding := application3.NewUpdateFunding(childRepository, writer, transactionManager)
	fundingUseCases := httpchild.FundingUseCases{
		Get:    getFunding,
		Update: updateFunding,
	}
	getCollectionSetting := application3.NewGetCollectionSetting(childRepository)
	setCollectionPassword := application3.NewSetCollectionPassword(childRepository, writer, transactionManager)
	collectionUseCases := httpchild.CollectionUseCases{
		GetSetting:  getCollectionSetting,
		SetPassword: setCollectionPassword,
	}
	listRoomAssignments := application3.NewListRoomAssignments(childRepository)
	createRoomAssignment := application3.NewCreateRoomAssignment(childRepository, writer, transactionManager)
	closeRoomAssignment := application3.NewCloseRoomAssignment(childRepository, writer, transactionManager)
	roomAssignmentUseCases := httpchild.RoomAssignmentUseCases{
		List:   listRoomAssignments,
		Create: createRoomAssignment,
		Close:  closeRoomAssignment,
	}
	getBillingProfile := application3.NewGetBillingProfile(childRepository)
	updateBillingProfile := application3.NewUpdateBillingProfile(childRepository, writer, transactionManager)
	billingProfileUseCases := httpchild.BillingProfileUseCases{
		Get:    getBillingProfile,
		Update: updateBillingProfile,
	}
	getLeavingRecord := application3.NewGetLeavingRecord(childRepository)
	listBookingPatterns := application3.NewListBookingPatterns(childRepository)
	getBookingPattern := application3.NewGetBookingPattern(childRepository)
	getCurrentBookingPattern := application3.NewGetCurrentBookingPattern(childRepository, todayFunc)
	createBookingPattern := application3.NewCreateBookingPattern(childRepository, writer, transactionManager, bootstrapSessionTypeLookupAdapter, todayFunc)
	updateBookingPattern := application3.NewUpdateBookingPattern(childRepository, writer, transactionManager, bootstrapSessionTypeLookupAdapter, todayFunc)
	bookingPatternUseCases := httpchild.BookingPatternUseCases{
		List:       listBookingPatterns,
		Get:        getBookingPattern,
		GetCurrent: getCurrentBookingPattern,
		Create:     createBookingPattern,
		Update:     updateBookingPattern,
	}
	childrenHandlerConfig := httpchild.ChildrenHandlerConfig{
		Core:            coreUseCases,
		Profile:         profileUseCases,
		Contacts:        contactsUseCases,
		Health:          healthUseCases,
		Safeguarding:    safeguardingUseCases,
		Consent:         consentUseCases,
		Funding:         fundingUseCases,
		Collection:      collectionUseCases,
		RoomAssignments: roomAssignmentUseCases,
		BillingProfile:  billingProfileUseCases,
		LeavingRecord:   getLeavingRecord,
		BookingPatterns: bookingPatternUseCases,
	}
	httpchildHandler := httpchild.NewHandler(childrenHandlerConfig, logger)
	parentChildMappingRepository := postgres7.NewParentChildMappingRepository(pool)
	bootstrapMembershipCheckerAdapter := provideMembershipCheckerAdapter(parentChildMappingRepository)
	bootstrapChildScopeCheckerAdapter := provideChildScopeCheckerAdapter(childRepository)
	createMappingUseCase := application4.NewCreateMappingUseCase(parentChildMappingRepository, writer, transactionManager, bootstrapMembershipCheckerAdapter, bootstrapChildScopeCheckerAdapter)
	endMappingUseCase := application4.NewEndMappingUseCase(parentChildMappingRepository, writer, transactionManager)
	httpmappingHandler := httpmapping.NewHandler(createMappingUseCase, endMappingUseCase, logger)
	attendanceRepository := postgres8.NewAttendanceRepository(pool)
	bootstrapChildEnrollmentCheckerAdapter := provideChildEnrollmentCheckerAdapter(childRepository)
	absenceRepository := postgres9.NewAbsenceRepository(pool)
	bootstrapAbsenceMarkerCheckerAdapter := provideAbsenceMarkerCheckerAdapter(absenceRepository)
	attendanceClock := provideAttendanceClock()
	checkInChild := application5.NewCheckInChild(attendanceRepository, bootstrapChildEnrollmentCheckerAdapter, bootstrapAbsenceMarkerCheckerAdapter, transactionManager, writer, attendanceClock)
	checkOutChild := application5.NewCheckOutChild(attendanceRepository, transactionManager, writer, attendanceClock)
	bootstrapChildCorrectionCheckerAdapter := provideChildCorrectionCheckerAdapter(childRepository)
	correctAttendance := application5.NewCorrectAttendance(attendanceRepository, bootstrapChildCorrectionCheckerAdapter, transactionManager, writer, attendanceClock)
	listCorrectionSessions := application5.NewListCorrectionSessions(attendanceRepository)
	listCorrectionHistory := application5.NewListCorrectionHistory(attendanceRepository)
	httpattendanceHandler := httpattendance.NewHandler(checkInChild, checkOutChild, correctAttendance, listCorrectionSessions, listCorrectionHistory, logger)
	markAbsent := provideMarkAbsent(absenceRepository, bootstrapChildEnrollmentCheckerAdapter, transactionManager, writer, attendanceClock)
	clearMarker := provideClearMarker(absenceRepository, transactionManager, writer, attendanceClock)
	httpabsenceHandler := httpabsence.NewHandler(markAbsent, clearMarker, logger)
	repository2 := postgres10.NewRepository(pool)
	applicationGetProfile := application6.NewGetProfile(repository2)
	upsertProfile := provideUpsertProfile(repository2, transactionManager, writer)
	listOverview := application6.NewListOverview(repository2)
	httpfundingHandler := httpfunding.NewHandler(applicationGetProfile, upsertProfile, listOverview, logger)
	repository3 := postgres11.NewRepository(pool)
	preflightDraftInvoices := application7.NewPreflightDraftInvoices(repository3)
	academicTermRepository := postgres12.NewRepository(pool)
	bootstrapTermDateLookupAdapter := provideTermDateLookupAdapter(academicTermRepository)
	bootstrapAdHocBookingLookupAdapter := provideAdHocBookingLookupAdapter(repository3)
	repository4 := postgres13.NewRepository(pool)
	bootstrapClosureDateLookupAdapter := provideClosureDateLookupAdapter(repository4)
	generateDraftInvoicesUseCase := application7.NewGenerateDraftInvoices(repository3, transactionManager, writer, logger, recorder, bootstrapTermDateLookupAdapter, bootstrapAdHocBookingLookupAdapter, bootstrapClosureDateLookupAdapter)
	computeInvoicePrefill := application7.NewComputeInvoicePrefill(repository3, transactionManager)
	createDraftInvoice := application7.NewCreateDraftInvoice(repository3, transactionManager, writer)
	issueInvoice := application7.NewIssueInvoice(repository3, transactionManager, writer, eventDispatcher)
	createAndIssueInvoiceFromForm := application7.NewCreateAndIssueInvoiceFromForm(repository3, eventDispatcher, writer, issueInvoice)
	draftUseCases := httpbilling.DraftUseCases{
		Preflight:              preflightDraftInvoices,
		Generation:             generateDraftInvoicesUseCase,
		ComputePrefill:         computeInvoicePrefill,
		CreateDraft:            createDraftInvoice,
		CreateAndIssueFromForm: createAndIssueInvoiceFromForm,
	}
	listInvoices := application7.NewListInvoices(repository3)
	siteProfileRepository := postgres14.NewRepository(pool)
	getSiteProfileUseCase := application8.NewGetSiteProfileUseCase(siteProfileRepository)
	bootstrapSiteProfileLookupAdapter := provideSiteProfileLookupAdapter(getSiteProfileUseCase)
	bootstrapParentContactLookupAdapter := provideParentContactLookupAdapter(pool)
	getInvoice := application7.NewGetInvoice(repository3, bootstrapSiteProfileLookupAdapter, bootstrapParentContactLookupAdapter)
	bulkIssueInvoices := application7.NewBulkIssueInvoices(repository3, transactionManager, writer)
	overrideAttendanceBlockUseCase := application7.NewOverrideAttendanceBlockUseCase(repository3, writer, transactionManager)
	lifecycleUseCases := httpbilling.LifecycleUseCases{
		ListInvoices:          listInvoices,
		GetInvoice:            getInvoice,
		IssueInvoice:          issueInvoice,
		BulkIssueInvoices:     bulkIssueInvoices,
		OverrideAttendanceBlk: overrideAttendanceBlockUseCase,
	}
	listParentInvoices := application7.NewListParentInvoices(repository3)
	getParentInvoice := application7.NewGetParentInvoice(repository3, bootstrapSiteProfileLookupAdapter)
	parentInvoiceUseCases := httpbilling.ParentInvoiceUseCases{
		List: listParentInvoices,
		Get:  getParentInvoice,
	}
	bootstrapSiteRateUpdateAdapter := provideSiteRateUpdateAdapter(ownerRepository)
	updateSiteRateUseCase := application7.NewUpdateSiteRateUseCase(bootstrapSiteRateUpdateAdapter, writer, transactionManager)
	adminUseCases := httpbilling.AdminUseCases{
		UpdateSiteRate: updateSiteRateUseCase,
	}
	billingHandlerConfig := httpbilling.BillingHandlerConfig{
		Drafting:  draftUseCases,
		Lifecycle: lifecycleUseCases,
		Parent:    parentInvoiceUseCases,
		Admin:     adminUseCases,
	}
	httpbillingHandler := httpbilling.NewHandler(billingHandlerConfig, logger)
	repository5 := postgres15.NewRepository(pool)
	bootstrapTxManagerAdapter := provideTxManagerAdapter(transactionManager)
	client := provideStripeClient(cfg)
	createCheckoutSession := provideCreateCheckoutSession(repository5, bootstrapTxManagerAdapter, client, cfg, logger, recorder)
	webhookVerifier := provideWebhookVerifier(cfg)
	bootstrapAuditSystemWriterAdapter := provideAuditSystemWriterAdapter(writer)
	handleStripeWebhook := provideHandleStripeWebhook(repository5, webhookVerifier, bootstrapTxManagerAdapter, bootstrapAuditSystemWriterAdapter, logger, recorder)
	managerPaymentRepository := provideManagerPaymentRepo(repository5)
	getManagerPaymentStatus := application9.NewGetManagerPaymentStatus(managerPaymentRepository)
	listManagerPaymentEvents := application9.NewListManagerPaymentEvents(managerPaymentRepository)
	httpaymentHandler := providePaymentsHandler(createCheckoutSession, handleStripeWebhook, getManagerPaymentStatus, listManagerPaymentEvents, recorder, logger)
	repository6 := postgres16.NewRepository(pool, writer)
	tokensManager := provideInviteTokenManager(cfg)
	applicationTokenGeneratorAdapter := application10.NewTokenGeneratorAdapter(tokensManager)
	inviteEmailAdapter := application10.NewInviteEmailAdapter(sender)
	createInviteUseCase := application10.NewCreateInviteUseCase(repository6, applicationTokenGeneratorAdapter, inviteEmailAdapter, string2, logger)
	listInvitesUseCase := application10.NewListInvitesUseCase(repository6)
	resendInviteUseCase := application10.NewResendInviteUseCase(repository6, applicationTokenGeneratorAdapter, inviteEmailAdapter, string2, logger)
	revokeInviteUseCase := application10.NewRevokeInviteUseCase(repository6, logger)
	acceptInviteUseCase := application10.NewAcceptInviteUseCase(repository6, logger)
	fixedWindowLimiter := provideInviteIPLimiter()
	httpinviteHandler := httpinvite.NewHandler(createInviteUseCase, listInvitesUseCase, resendInviteUseCase, revokeInviteUseCase, acceptInviteUseCase, tokensManager, fixedWindowLimiter, logger)
	getSiteSummariesUseCase := application11.NewGetSiteSummariesUseCase(ownerRepository)
	listManagerAccessUseCase := application11.NewListManagerAccessUseCase(ownerRepository)
	bootstrapInviteTokenGeneratorAdapter := provideInviteTokenGeneratorAdapter(tokensManager)
	bootstrapEmailSenderAdapter := provideEmailSenderAdapter(sender, cfg)
	grantManagerAccessUseCase := application11.NewGrantManagerAccessUseCase(ownerRepository, bootstrapInviteTokenGeneratorAdapter, bootstrapEmailSenderAdapter, string2)
	deactivateManagerAccessUseCase := application11.NewDeactivateManagerAccessUseCase(ownerRepository)
	reactivateManagerAccessUseCase := application11.NewReactivateManagerAccessUseCase(ownerRepository)
	updateSiteBillingSetupUseCase := application11.NewUpdateSiteBillingSetupUseCase(ownerRepository, writer, transactionManager)
	httpownerHandler := provideOwnerHandler(getSiteSummariesUseCase, listManagerAccessUseCase, grantManagerAccessUseCase, deactivateManagerAccessUseCase, reactivateManagerAccessUseCase, updateSiteBillingSetupUseCase, recorder, logger)
	roomRepository := postgres17.NewRepository(pool)
	bootstrapSiteExistsCheckerAdapter := provideSiteExistsCheckerAdapter(ownerRepository)
	createRoom := application12.NewCreateRoom(roomRepository, bootstrapSiteExistsCheckerAdapter)
	updateRoom := application12.NewUpdateRoom(roomRepository, bootstrapSiteExistsCheckerAdapter)
	listRooms := application12.NewListRooms(roomRepository)
	getRoom := application12.NewGetRoom(roomRepository)
	archiveRoom := application12.NewArchiveRoom(roomRepository, transactionManager, writer)
	reactivateRoom := application12.NewReactivateRoom(roomRepository, transactionManager, writer)
	httproomsHandler := httprooms.NewHandler(createRoom, updateRoom, listRooms, getRoom, archiveRoom, reactivateRoom, logger)
	createSessionType := application13.NewCreateSessionType(sessionTypeRepository, bootstrapSiteExistsCheckerAdapter, transactionManager, writer)
	updateSessionType := application13.NewUpdateSessionType(sessionTypeRepository, bootstrapSiteExistsCheckerAdapter, transactionManager, writer)
	listSessionTypes := application13.NewListSessionTypes(sessionTypeRepository)
	getSessionType := application13.NewGetSessionType(sessionTypeRepository)
	archiveSessionType := application13.NewArchiveSessionType(sessionTypeRepository, transactionManager, writer)
	reactivateSessionType := application13.NewReactivateSessionType(sessionTypeRepository, transactionManager, writer)
	httpsessiontypesHandler := httpsessiontypes.NewHandler(createSessionType, updateSessionType, listSessionTypes, getSessionType, archiveSessionType, reactivateSessionType, logger)
	sessionTemplateRepository := postgres18.NewRepository(pool)
	bootstrapSessionTemplateLookupTemplateAdapter := provideSessionTemplateLookupTemplateAdapter(bootstrapSessionTypeLookupAdapter)
	createSessionTemplate := application14.NewCreateSessionTemplate(sessionTemplateRepository, bootstrapSiteExistsCheckerAdapter, bootstrapSessionTemplateLookupTemplateAdapter, transactionManager, writer)
	updateSessionTemplate := application14.NewUpdateSessionTemplate(sessionTemplateRepository, bootstrapSiteExistsCheckerAdapter, bootstrapSessionTemplateLookupTemplateAdapter, transactionManager, writer)
	listSessionTemplates := application14.NewListSessionTemplates(sessionTemplateRepository)
	getSessionTemplate := application14.NewGetSessionTemplate(sessionTemplateRepository)
	archiveSessionTemplate := application14.NewArchiveSessionTemplate(sessionTemplateRepository, transactionManager, writer)
	reactivateSessionTemplate := application14.NewReactivateSessionTemplate(sessionTemplateRepository, transactionManager, writer)
	httpsessiontemplatesHandler := httpsessiontemplates.NewHandler(createSessionTemplate, updateSessionTemplate, listSessionTemplates, getSessionTemplate, archiveSessionTemplate, reactivateSessionTemplate, logger)
	bootstrapBookingPatternLookupAdapter := provideBookingPatternLookupAdapter(childRepository)
	createTermUseCase := application15.NewCreateTermUseCase(termRepository, transactionManager, writer, bootstrapBookingPatternLookupAdapter, bootstrapSiteRateProviderAdapter)
	getTermUseCase := application15.NewGetTermUseCase(termRepository)
	getCurrentTermForChildUseCase := application15.NewGetCurrentTermForChildUseCase(termRepository)
	listTermsForChildUseCase := application15.NewListTermsForChildUseCase(termRepository)
	listExpiringTermsUseCase := application15.NewListExpiringTermsUseCase(termRepository)
	terminateTermUseCase := application15.NewTerminateTermUseCase(termRepository, transactionManager, writer)
	coreTermUseCases := httpterm.CoreTermUseCases{
		Create:       createTermUseCase,
		Get:          getTermUseCase,
		GetCurrent:   getCurrentTermForChildUseCase,
		List:         listTermsForChildUseCase,
		ListExpiring: listExpiringTermsUseCase,
		Terminate:    terminateTermUseCase,
	}
	scheduleChangeRepository := postgres5.NewScheduleChangeRepository(pool)
	requestScheduleChangeUseCase := application15.NewRequestScheduleChangeUseCase(termRepository, scheduleChangeRepository, transactionManager, writer, bootstrapBookingPatternLookupAdapter)
	approveScheduleChangeUseCase := application15.NewApproveScheduleChangeUseCase(scheduleChangeRepository, writer, transactionManager)
	rejectScheduleChangeUseCase := application15.NewRejectScheduleChangeUseCase(scheduleChangeRepository, writer, transactionManager)
	scheduleChangeUseCases := httpterm.ScheduleChangeUseCases{
		Request: requestScheduleChangeUseCase,
		Approve: approveScheduleChangeUseCase,
		Reject:  rejectScheduleChangeUseCase,
	}
	termHandlerConfig := httpterm.TermHandlerConfig{
		Core:    coreTermUseCases,
		Changes: scheduleChangeUseCases,
	}
	httptermHandler := httpterm.NewHandler(termHandlerConfig, logger)
	createTerm := application16.NewCreateTerm(academicTermRepository)
	listTerms := application16.NewListTerms(academicTermRepository)
	updateTerm := application16.NewUpdateTerm(academicTermRepository, transactionManager)
	archiveTerm := application16.NewArchiveTerm(academicTermRepository, transactionManager)
	httptermcalendarHandler := httptermcalendar.NewHandler(createTerm, listTerms, updateTerm, archiveTerm, logger)
	adHocBookingRepository := postgres19.NewRepository(pool)
	createAdHocBooking := application17.NewCreateAdHocBooking(adHocBookingRepository)
	listAdHocBookings := application17.NewListAdHocBookings(adHocBookingRepository)
	cancelAdHocBooking := application17.NewCancelAdHocBooking(adHocBookingRepository, transactionManager)
	httpadhocbookingsHandler := httpadhocbookings.NewHandler(createAdHocBooking, listAdHocBookings, cancelAdHocBooking, logger)
	createClosureDay := application18.NewCreateClosureDay(repository4)
	listClosureDays := application18.NewListClosureDays(repository4)
	deleteClosureDay := application18.NewDeleteClosureDay(repository4)
	httpclosureHandler := httpclosure.NewHandler(createClosureDay, listClosureDays, deleteClosureDay, logger)
	httpHandler := provideSiteProfileHandlerSet(siteProfileRepository, writer, transactionManager, logger)
	bootstrapAppComponents := appComponents{
		Logger:                  logger,
		Config:                  cfg,
		Pool:                    pool,
		Recorder:                recorder,
		Registry:                registry,
		TokenParser:             tokenParser,
		AuthHandler:             handler,
		ResetHandler:            httpresetHandler,
		ChildrenHandler:         httpchildHandler,
		MappingsHandler:         httpmappingHandler,
		AttendanceHandler:       httpattendanceHandler,
		AbsenceHandler:          httpabsenceHandler,
		FundingHandler:          httpfundingHandler,
		BillingHandler:          httpbillingHandler,
		PaymentsHandler:         httpaymentHandler,
		InviteHandler:           httpinviteHandler,
		OwnerHandler:            httpownerHandler,
		RoomsHandler:            httproomsHandler,
		SessionTypesHandler:     httpsessiontypesHandler,
		SessionTemplatesHandler: httpsessiontemplatesHandler,
		TermHandler:             httptermHandler,
		TermCalendarHandler:     httptermcalendarHandler,
		AdHocBookingsHandler:    httpadhocbookingsHandler,
		BranchClosureHandler:    httpclosureHandler,
		SiteProfileHandler:      httpHandler,
	}
	engine := buildGinEngine(bootstrapAppComponents)
	return engine, nil
}

func InitializeTestApp(cfg config.Config, logger *slog.Logger, pool *pgxpool.Pool) (*gin.Engine, error) {
	registry := provideMetricsRegistry(cfg)
	recorder := provideMetricsRecorder(cfg, registry)
	tokenManager := provideTokenManager(cfg)
	tokenParser := provideTokenParserAdapter(tokenManager)
	repository := postgres.NewRepository(pool)
	loginUseCase := application.NewLoginUseCase(repository, repository, tokenManager)
	refreshUseCase := application.NewRefreshUseCase(repository, repository, tokenManager)
	logoutUseCase := application.NewLogoutUseCase(repository, tokenManager)
	switchMembershipUseCase := application.NewSwitchMembershipUseCase(repository, repository, tokenManager)
	handler := httpauth.NewHandler(loginUseCase, refreshUseCase, logoutUseCase, switchMembershipUseCase, cfg, recorder, logger)
	postgresRepository := postgres2.NewRepository(pool)
	sender := provideEmailSender(cfg)
	emailAdapter := application2.NewEmailAdapter(sender)
	manager := provideResetTokenManager(cfg)
	tokenGeneratorAdapter := application2.NewTokenGeneratorAdapter(manager)
	string2 := provideWebBaseURL(cfg)
	requestResetUseCase := application2.NewRequestResetUseCase(postgresRepository, emailAdapter, tokenGeneratorAdapter, string2, logger)
	setNewPasswordUseCase := application2.NewSetNewPasswordUseCase(postgresRepository, logger)
	httpresetHandler := provideResetHandler(requestResetUseCase, setNewPasswordUseCase, recorder, logger)
	childRepository := postgres3.NewChildRepository(pool)
	listChildren := application3.NewListChildren(childRepository)
	getChild := application3.NewGetChild(childRepository)
	writer := provideAuditWriter()
	transactionManager := provideTxManager(pool)
	sessionTypeRepository := postgres4.NewRepository(pool)
	bootstrapSessionTypeLookupAdapter := provideSessionTypeLookupAdapter(sessionTypeRepository)
	termRepository := postgres5.NewTermRepository(pool)
	ownerRepository := postgres6.NewRepository(pool)
	bootstrapSiteRateProviderAdapter := provideSiteRateProviderAdapter(ownerRepository)
	bootstrapEnrollmentTermCreatorAdapter := provideEnrollmentTermCreatorAdapter(termRepository, bootstrapSiteRateProviderAdapter, writer)
	todayFunc := provideTodayFunc()
	createChildWithFullProfile := application3.NewCreateChildWithFullProfile(childRepository, writer, transactionManager, bootstrapSessionTypeLookupAdapter, bootstrapEnrollmentTermCreatorAdapter, todayFunc)
	updateChild := application3.NewUpdateChild(childRepository, writer, transactionManager)
	eventDispatcher := provideEventDispatcher(transactionManager)
	markInactive := application3.NewMarkInactive(childRepository, eventDispatcher, writer)
	v := provideClock()
	listAttendance := application3.NewListAttendance(childRepository, v)
	coreUseCases := httpchild.CoreUseCases{
		List:           listChildren,
		Get:            getChild,
		Create:         createChildWithFullProfile,
		Update:         updateChild,
		MarkInactive:   markInactive,
		ListAttendance: listAttendance,
	}
	getProfile := application3.NewGetProfile(childRepository)
	updateProfile := application3.NewUpdateProfile(childRepository, writer, transactionManager)
	profileUseCases := httpchild.ProfileUseCases{
		Get:    getProfile,
		Update: updateProfile,
	}
	getContacts := application3.NewGetContacts(childRepository)
	replaceContacts := application3.NewReplaceContacts(childRepository, writer, transactionManager)
	contactsUseCases := httpchild.ContactsUseCases{
		Get:     getContacts,
		Replace: replaceContacts,
	}
	getHealth := application3.NewGetHealth(childRepository)
	updateHealth := application3.NewUpdateHealth(childRepository, writer, transactionManager)
	healthUseCases := httpchild.HealthUseCases{
		Get:    getHealth,
		Update: updateHealth,
	}
	getSafeguarding := application3.NewGetSafeguarding(childRepository)
	updateSafeguarding := application3.NewUpdateSafeguarding(childRepository, writer, transactionManager)
	safeguardingUseCases := httpchild.SafeguardingUseCases{
		Get:    getSafeguarding,
		Update: updateSafeguarding,
	}
	getConsent := application3.NewGetConsent(childRepository)
	updateConsent := application3.NewUpdateConsent(childRepository, writer, transactionManager)
	consentUseCases := httpchild.ConsentUseCases{
		Get:    getConsent,
		Update: updateConsent,
	}
	getFunding := application3.NewGetFunding(childRepository)
	updateFunding := application3.NewUpdateFunding(childRepository, writer, transactionManager)
	fundingUseCases := httpchild.FundingUseCases{
		Get:    getFunding,
		Update: updateFunding,
	}
	getCollectionSetting := application3.NewGetCollectionSetting(childRepository)
	setCollectionPassword := application3.NewSetCollectionPassword(childRepository, writer, transactionManager)
	collectionUseCases := httpchild.CollectionUseCases{
		GetSetting:  getCollectionSetting,
		SetPassword: setCollectionPassword,
	}
	listRoomAssignments := application3.NewListRoomAssignments(childRepository)
	createRoomAssignment := application3.NewCreateRoomAssignment(childRepository, writer, transactionManager)
	closeRoomAssignment := application3.NewCloseRoomAssignment(childRepository, writer, transactionManager)
	roomAssignmentUseCases := httpchild.RoomAssignmentUseCases{
		List:   listRoomAssignments,
		Create: createRoomAssignment,
		Close:  closeRoomAssignment,
	}
	getBillingProfile := application3.NewGetBillingProfile(childRepository)
	updateBillingProfile := application3.NewUpdateBillingProfile(childRepository, writer, transactionManager)
	billingProfileUseCases := httpchild.BillingProfileUseCases{
		Get:    getBillingProfile,
		Update: updateBillingProfile,
	}
	getLeavingRecord := application3.NewGetLeavingRecord(childRepository)
	listBookingPatterns := application3.NewListBookingPatterns(childRepository)
	getBookingPattern := application3.NewGetBookingPattern(childRepository)
	getCurrentBookingPattern := application3.NewGetCurrentBookingPattern(childRepository, todayFunc)
	createBookingPattern := application3.NewCreateBookingPattern(childRepository, writer, transactionManager, bootstrapSessionTypeLookupAdapter, todayFunc)
	updateBookingPattern := application3.NewUpdateBookingPattern(childRepository, writer, transactionManager, bootstrapSessionTypeLookupAdapter, todayFunc)
	bookingPatternUseCases := httpchild.BookingPatternUseCases{
		List:       listBookingPatterns,
		Get:        getBookingPattern,
		GetCurrent: getCurrentBookingPattern,
		Create:     createBookingPattern,
		Update:     updateBookingPattern,
	}
	childrenHandlerConfig := httpchild.ChildrenHandlerConfig{
		Core:            coreUseCases,
		Profile:         profileUseCases,
		Contacts:        contactsUseCases,
		Health:          healthUseCases,
		Safeguarding:    safeguardingUseCases,
		Consent:         consentUseCases,
		Funding:         fundingUseCases,
		Collection:      collectionUseCases,
		RoomAssignments: roomAssignmentUseCases,
		BillingProfile:  billingProfileUseCases,
		LeavingRecord:   getLeavingRecord,
		BookingPatterns: bookingPatternUseCases,
	}
	httpchildHandler := httpchild.NewHandler(childrenHandlerConfig, logger)
	parentChildMappingRepository := postgres7.NewParentChildMappingRepository(pool)
	bootstrapMembershipCheckerAdapter := provideMembershipCheckerAdapter(parentChildMappingRepository)
	bootstrapChildScopeCheckerAdapter := provideChildScopeCheckerAdapter(childRepository)
	createMappingUseCase := application4.NewCreateMappingUseCase(parentChildMappingRepository, writer, transactionManager, bootstrapMembershipCheckerAdapter, bootstrapChildScopeCheckerAdapter)
	endMappingUseCase := application4.NewEndMappingUseCase(parentChildMappingRepository, writer, transactionManager)
	httpmappingHandler := httpmapping.NewHandler(createMappingUseCase, endMappingUseCase, logger)
	attendanceRepository := postgres8.NewAttendanceRepository(pool)
	bootstrapChildEnrollmentCheckerAdapter := provideChildEnrollmentCheckerAdapter(childRepository)
	absenceRepository := postgres9.NewAbsenceRepository(pool)
	bootstrapAbsenceMarkerCheckerAdapter := provideAbsenceMarkerCheckerAdapter(absenceRepository)
	attendanceClock := provideAttendanceClock()
	checkInChild := application5.NewCheckInChild(attendanceRepository, bootstrapChildEnrollmentCheckerAdapter, bootstrapAbsenceMarkerCheckerAdapter, transactionManager, writer, attendanceClock)
	checkOutChild := application5.NewCheckOutChild(attendanceRepository, transactionManager, writer, attendanceClock)
	bootstrapChildCorrectionCheckerAdapter := provideChildCorrectionCheckerAdapter(childRepository)
	correctAttendance := application5.NewCorrectAttendance(attendanceRepository, bootstrapChildCorrectionCheckerAdapter, transactionManager, writer, attendanceClock)
	listCorrectionSessions := application5.NewListCorrectionSessions(attendanceRepository)
	listCorrectionHistory := application5.NewListCorrectionHistory(attendanceRepository)
	httpattendanceHandler := httpattendance.NewHandler(checkInChild, checkOutChild, correctAttendance, listCorrectionSessions, listCorrectionHistory, logger)
	markAbsent := provideMarkAbsent(absenceRepository, bootstrapChildEnrollmentCheckerAdapter, transactionManager, writer, attendanceClock)
	clearMarker := provideClearMarker(absenceRepository, transactionManager, writer, attendanceClock)
	httpabsenceHandler := httpabsence.NewHandler(markAbsent, clearMarker, logger)
	repository2 := postgres10.NewRepository(pool)
	applicationGetProfile := application6.NewGetProfile(repository2)
	upsertProfile := provideUpsertProfile(repository2, transactionManager, writer)
	listOverview := application6.NewListOverview(repository2)
	httpfundingHandler := httpfunding.NewHandler(applicationGetProfile, upsertProfile, listOverview, logger)
	repository3 := postgres11.NewRepository(pool)
	preflightDraftInvoices := application7.NewPreflightDraftInvoices(repository3)
	academicTermRepository := postgres12.NewRepository(pool)
	bootstrapTermDateLookupAdapter := provideTermDateLookupAdapter(academicTermRepository)
	bootstrapAdHocBookingLookupAdapter := provideAdHocBookingLookupAdapter(repository3)
	repository4 := postgres13.NewRepository(pool)
	bootstrapClosureDateLookupAdapter := provideClosureDateLookupAdapter(repository4)
	generateDraftInvoicesUseCase := application7.NewGenerateDraftInvoices(repository3, transactionManager, writer, logger, recorder, bootstrapTermDateLookupAdapter, bootstrapAdHocBookingLookupAdapter, bootstrapClosureDateLookupAdapter)
	computeInvoicePrefill := application7.NewComputeInvoicePrefill(repository3, transactionManager)
	createDraftInvoice := application7.NewCreateDraftInvoice(repository3, transactionManager, writer)
	issueInvoice := application7.NewIssueInvoice(repository3, transactionManager, writer, eventDispatcher)
	createAndIssueInvoiceFromForm := application7.NewCreateAndIssueInvoiceFromForm(repository3, eventDispatcher, writer, issueInvoice)
	draftUseCases := httpbilling.DraftUseCases{
		Preflight:              preflightDraftInvoices,
		Generation:             generateDraftInvoicesUseCase,
		ComputePrefill:         computeInvoicePrefill,
		CreateDraft:            createDraftInvoice,
		CreateAndIssueFromForm: createAndIssueInvoiceFromForm,
	}
	listInvoices := application7.NewListInvoices(repository3)
	siteProfileRepository := postgres14.NewRepository(pool)
	getSiteProfileUseCase := application8.NewGetSiteProfileUseCase(siteProfileRepository)
	bootstrapSiteProfileLookupAdapter := provideSiteProfileLookupAdapter(getSiteProfileUseCase)
	bootstrapParentContactLookupAdapter := provideParentContactLookupAdapter(pool)
	getInvoice := application7.NewGetInvoice(repository3, bootstrapSiteProfileLookupAdapter, bootstrapParentContactLookupAdapter)
	bulkIssueInvoices := application7.NewBulkIssueInvoices(repository3, transactionManager, writer)
	overrideAttendanceBlockUseCase := application7.NewOverrideAttendanceBlockUseCase(repository3, writer, transactionManager)
	lifecycleUseCases := httpbilling.LifecycleUseCases{
		ListInvoices:          listInvoices,
		GetInvoice:            getInvoice,
		IssueInvoice:          issueInvoice,
		BulkIssueInvoices:     bulkIssueInvoices,
		OverrideAttendanceBlk: overrideAttendanceBlockUseCase,
	}
	listParentInvoices := application7.NewListParentInvoices(repository3)
	getParentInvoice := application7.NewGetParentInvoice(repository3, bootstrapSiteProfileLookupAdapter)
	parentInvoiceUseCases := httpbilling.ParentInvoiceUseCases{
		List: listParentInvoices,
		Get:  getParentInvoice,
	}
	bootstrapSiteRateUpdateAdapter := provideSiteRateUpdateAdapter(ownerRepository)
	updateSiteRateUseCase := application7.NewUpdateSiteRateUseCase(bootstrapSiteRateUpdateAdapter, writer, transactionManager)
	adminUseCases := httpbilling.AdminUseCases{
		UpdateSiteRate: updateSiteRateUseCase,
	}
	billingHandlerConfig := httpbilling.BillingHandlerConfig{
		Drafting:  draftUseCases,
		Lifecycle: lifecycleUseCases,
		Parent:    parentInvoiceUseCases,
		Admin:     adminUseCases,
	}
	httpbillingHandler := httpbilling.NewHandler(billingHandlerConfig, logger)
	repository5 := postgres15.NewRepository(pool)
	bootstrapTxManagerAdapter := provideTxManagerAdapter(transactionManager)
	client := provideStripeClient(cfg)
	createCheckoutSession := provideCreateCheckoutSession(repository5, bootstrapTxManagerAdapter, client, cfg, logger, recorder)
	webhookVerifier := provideWebhookVerifier(cfg)
	bootstrapAuditSystemWriterAdapter := provideAuditSystemWriterAdapter(writer)
	handleStripeWebhook := provideHandleStripeWebhook(repository5, webhookVerifier, bootstrapTxManagerAdapter, bootstrapAuditSystemWriterAdapter, logger, recorder)
	managerPaymentRepository := provideManagerPaymentRepo(repository5)
	getManagerPaymentStatus := application9.NewGetManagerPaymentStatus(managerPaymentRepository)
	listManagerPaymentEvents := application9.NewListManagerPaymentEvents(managerPaymentRepository)
	httpaymentHandler := providePaymentsHandler(createCheckoutSession, handleStripeWebhook, getManagerPaymentStatus, listManagerPaymentEvents, recorder, logger)
	repository6 := postgres16.NewRepository(pool, writer)
	tokensManager := provideInviteTokenManager(cfg)
	applicationTokenGeneratorAdapter := application10.NewTokenGeneratorAdapter(tokensManager)
	inviteEmailAdapter := application10.NewInviteEmailAdapter(sender)
	createInviteUseCase := application10.NewCreateInviteUseCase(repository6, applicationTokenGeneratorAdapter, inviteEmailAdapter, string2, logger)
	listInvitesUseCase := application10.NewListInvitesUseCase(repository6)
	resendInviteUseCase := application10.NewResendInviteUseCase(repository6, applicationTokenGeneratorAdapter, inviteEmailAdapter, string2, logger)
	revokeInviteUseCase := application10.NewRevokeInviteUseCase(repository6, logger)
	acceptInviteUseCase := application10.NewAcceptInviteUseCase(repository6, logger)
	fixedWindowLimiter := provideInviteIPLimiter()
	httpinviteHandler := httpinvite.NewHandler(createInviteUseCase, listInvitesUseCase, resendInviteUseCase, revokeInviteUseCase, acceptInviteUseCase, tokensManager, fixedWindowLimiter, logger)
	getSiteSummariesUseCase := application11.NewGetSiteSummariesUseCase(ownerRepository)
	listManagerAccessUseCase := application11.NewListManagerAccessUseCase(ownerRepository)
	bootstrapInviteTokenGeneratorAdapter := provideInviteTokenGeneratorAdapter(tokensManager)
	bootstrapEmailSenderAdapter := provideEmailSenderAdapter(sender, cfg)
	grantManagerAccessUseCase := application11.NewGrantManagerAccessUseCase(ownerRepository, bootstrapInviteTokenGeneratorAdapter, bootstrapEmailSenderAdapter, string2)
	deactivateManagerAccessUseCase := application11.NewDeactivateManagerAccessUseCase(ownerRepository)
	reactivateManagerAccessUseCase := application11.NewReactivateManagerAccessUseCase(ownerRepository)
	updateSiteBillingSetupUseCase := application11.NewUpdateSiteBillingSetupUseCase(ownerRepository, writer, transactionManager)
	httpownerHandler := provideOwnerHandler(getSiteSummariesUseCase, listManagerAccessUseCase, grantManagerAccessUseCase, deactivateManagerAccessUseCase, reactivateManagerAccessUseCase, updateSiteBillingSetupUseCase, recorder, logger)
	roomRepository := postgres17.NewRepository(pool)
	bootstrapSiteExistsCheckerAdapter := provideSiteExistsCheckerAdapter(ownerRepository)
	createRoom := application12.NewCreateRoom(roomRepository, bootstrapSiteExistsCheckerAdapter)
	updateRoom := application12.NewUpdateRoom(roomRepository, bootstrapSiteExistsCheckerAdapter)
	listRooms := application12.NewListRooms(roomRepository)
	getRoom := application12.NewGetRoom(roomRepository)
	archiveRoom := application12.NewArchiveRoom(roomRepository, transactionManager, writer)
	reactivateRoom := application12.NewReactivateRoom(roomRepository, transactionManager, writer)
	httproomsHandler := httprooms.NewHandler(createRoom, updateRoom, listRooms, getRoom, archiveRoom, reactivateRoom, logger)
	createSessionType := application13.NewCreateSessionType(sessionTypeRepository, bootstrapSiteExistsCheckerAdapter, transactionManager, writer)
	updateSessionType := application13.NewUpdateSessionType(sessionTypeRepository, bootstrapSiteExistsCheckerAdapter, transactionManager, writer)
	listSessionTypes := application13.NewListSessionTypes(sessionTypeRepository)
	getSessionType := application13.NewGetSessionType(sessionTypeRepository)
	archiveSessionType := application13.NewArchiveSessionType(sessionTypeRepository, transactionManager, writer)
	reactivateSessionType := application13.NewReactivateSessionType(sessionTypeRepository, transactionManager, writer)
	httpsessiontypesHandler := httpsessiontypes.NewHandler(createSessionType, updateSessionType, listSessionTypes, getSessionType, archiveSessionType, reactivateSessionType, logger)
	sessionTemplateRepository := postgres18.NewRepository(pool)
	bootstrapSessionTemplateLookupTemplateAdapter := provideSessionTemplateLookupTemplateAdapter(bootstrapSessionTypeLookupAdapter)
	createSessionTemplate := application14.NewCreateSessionTemplate(sessionTemplateRepository, bootstrapSiteExistsCheckerAdapter, bootstrapSessionTemplateLookupTemplateAdapter, transactionManager, writer)
	updateSessionTemplate := application14.NewUpdateSessionTemplate(sessionTemplateRepository, bootstrapSiteExistsCheckerAdapter, bootstrapSessionTemplateLookupTemplateAdapter, transactionManager, writer)
	listSessionTemplates := application14.NewListSessionTemplates(sessionTemplateRepository)
	getSessionTemplate := application14.NewGetSessionTemplate(sessionTemplateRepository)
	archiveSessionTemplate := application14.NewArchiveSessionTemplate(sessionTemplateRepository, transactionManager, writer)
	reactivateSessionTemplate := application14.NewReactivateSessionTemplate(sessionTemplateRepository, transactionManager, writer)
	httpsessiontemplatesHandler := httpsessiontemplates.NewHandler(createSessionTemplate, updateSessionTemplate, listSessionTemplates, getSessionTemplate, archiveSessionTemplate, reactivateSessionTemplate, logger)
	bootstrapBookingPatternLookupAdapter := provideBookingPatternLookupAdapter(childRepository)
	createTermUseCase := application15.NewCreateTermUseCase(termRepository, transactionManager, writer, bootstrapBookingPatternLookupAdapter, bootstrapSiteRateProviderAdapter)
	getTermUseCase := application15.NewGetTermUseCase(termRepository)
	getCurrentTermForChildUseCase := application15.NewGetCurrentTermForChildUseCase(termRepository)
	listTermsForChildUseCase := application15.NewListTermsForChildUseCase(termRepository)
	listExpiringTermsUseCase := application15.NewListExpiringTermsUseCase(termRepository)
	terminateTermUseCase := application15.NewTerminateTermUseCase(termRepository, transactionManager, writer)
	coreTermUseCases := httpterm.CoreTermUseCases{
		Create:       createTermUseCase,
		Get:          getTermUseCase,
		GetCurrent:   getCurrentTermForChildUseCase,
		List:         listTermsForChildUseCase,
		ListExpiring: listExpiringTermsUseCase,
		Terminate:    terminateTermUseCase,
	}
	scheduleChangeRepository := postgres5.NewScheduleChangeRepository(pool)
	requestScheduleChangeUseCase := application15.NewRequestScheduleChangeUseCase(termRepository, scheduleChangeRepository, transactionManager, writer, bootstrapBookingPatternLookupAdapter)
	approveScheduleChangeUseCase := application15.NewApproveScheduleChangeUseCase(scheduleChangeRepository, writer, transactionManager)
	rejectScheduleChangeUseCase := application15.NewRejectScheduleChangeUseCase(scheduleChangeRepository, writer, transactionManager)
	scheduleChangeUseCases := httpterm.ScheduleChangeUseCases{
		Request: requestScheduleChangeUseCase,
		Approve: approveScheduleChangeUseCase,
		Reject:  rejectScheduleChangeUseCase,
	}
	termHandlerConfig := httpterm.TermHandlerConfig{
		Core:    coreTermUseCases,
		Changes: scheduleChangeUseCases,
	}
	httptermHandler := httpterm.NewHandler(termHandlerConfig, logger)
	createTerm := application16.NewCreateTerm(academicTermRepository)
	listTerms := application16.NewListTerms(academicTermRepository)
	updateTerm := application16.NewUpdateTerm(academicTermRepository, transactionManager)
	archiveTerm := application16.NewArchiveTerm(academicTermRepository, transactionManager)
	httptermcalendarHandler := httptermcalendar.NewHandler(createTerm, listTerms, updateTerm, archiveTerm, logger)
	adHocBookingRepository := postgres19.NewRepository(pool)
	createAdHocBooking := application17.NewCreateAdHocBooking(adHocBookingRepository)
	listAdHocBookings := application17.NewListAdHocBookings(adHocBookingRepository)
	cancelAdHocBooking := application17.NewCancelAdHocBooking(adHocBookingRepository, transactionManager)
	httpadhocbookingsHandler := httpadhocbookings.NewHandler(createAdHocBooking, listAdHocBookings, cancelAdHocBooking, logger)
	createClosureDay := application18.NewCreateClosureDay(repository4)
	listClosureDays := application18.NewListClosureDays(repository4)
	deleteClosureDay := application18.NewDeleteClosureDay(repository4)
	httpclosureHandler := httpclosure.NewHandler(createClosureDay, listClosureDays, deleteClosureDay, logger)
	httpHandler := provideSiteProfileHandlerSet(siteProfileRepository, writer, transactionManager, logger)
	bootstrapAppComponents := appComponents{
		Logger:                  logger,
		Config:                  cfg,
		Pool:                    pool,
		Recorder:                recorder,
		Registry:                registry,
		TokenParser:             tokenParser,
		AuthHandler:             handler,
		ResetHandler:            httpresetHandler,
		ChildrenHandler:         httpchildHandler,
		MappingsHandler:         httpmappingHandler,
		AttendanceHandler:       httpattendanceHandler,
		AbsenceHandler:          httpabsenceHandler,
		FundingHandler:          httpfundingHandler,
		BillingHandler:          httpbillingHandler,
		PaymentsHandler:         httpaymentHandler,
		InviteHandler:           httpinviteHandler,
		OwnerHandler:            httpownerHandler,
		RoomsHandler:            httproomsHandler,
		SessionTypesHandler:     httpsessiontypesHandler,
		SessionTemplatesHandler: httpsessiontemplatesHandler,
		TermHandler:             httptermHandler,
		TermCalendarHandler:     httptermcalendarHandler,
		AdHocBookingsHandler:    httpadhocbookingsHandler,
		BranchClosureHandler:    httpclosureHandler,
		SiteProfileHandler:      httpHandler,
	}
	engine := buildGinEngine(bootstrapAppComponents)
	return engine, nil
}

// wire.go:

var authSet = wire.NewSet(
	provideTokenManager, postgres.NewRepository, wire.Bind(new(domain.UserRepository), new(*postgres.Repository)), wire.Bind(new(domain.SessionRepository), new(*postgres.Repository)), wire.Bind(new(application.TokenGenerator), new(*tokens.TokenManager)), application.NewLoginUseCase, application.NewRefreshUseCase, application.NewLogoutUseCase, application.NewSwitchMembershipUseCase, httpauth.NewHandler,
)

func provideMarkAbsent(
	repo domain2.Repository,
	childChecker domain2.ChildEnrollmentChecker,
	txMgr *transaction.Manager, audit2 *audit.Writer,
	clock *application5.AttendanceClock,
) *application19.MarkAbsent {
	return application19.NewMarkAbsent(repo, childChecker, txMgr, audit2, clock)
}

func provideClearMarker(
	repo domain2.Repository,
	txMgr *transaction.Manager, audit2 *audit.Writer,
	clock *application5.AttendanceClock,
) *application19.ClearMarker {
	return application19.NewClearMarker(repo, txMgr, audit2, clock)
}

func provideUpsertProfile(
	repo domain3.Repository,
	txMgr *transaction.Manager, audit2 *audit.Writer,
) *application6.UpsertProfile {
	return application6.NewUpsertProfile(repo, txMgr, audit2)
}

var passwordResetSet = wire.NewSet(
	provideResetTokenManager, postgres2.NewRepository, wire.Bind(new(domain4.Repository), new(*postgres2.Repository)), application2.NewTokenGeneratorAdapter, wire.Bind(new(application2.TokenGenerator), new(*application2.TokenGeneratorAdapter)), application2.NewEmailAdapter, wire.Bind(new(domain4.EmailSender), new(*application2.EmailAdapter)), application2.NewRequestResetUseCase, application2.NewSetNewPasswordUseCase, provideResetHandler,
)

var childrenSet = wire.NewSet(postgres3.NewChildRepository, wire.Bind(new(domain5.Repository), new(*postgres3.ChildRepository)), provideSessionTypeLookupAdapter, wire.Bind(new(application3.SessionTypeLookup), new(*sessionTypeLookupAdapter)), provideEnrollmentTermCreatorAdapter, wire.Bind(new(application3.EnrollmentTermCreator), new(*enrollmentTermCreatorAdapter)), provideClock,
	provideTodayFunc, application3.NewListChildren, application3.NewGetChild, application3.NewCreateChildWithFullProfile, application3.NewUpdateChild, application3.NewMarkInactive, application3.NewListAttendance, application3.NewGetProfile, application3.NewUpdateProfile, application3.NewGetContacts, application3.NewReplaceContacts, application3.NewGetHealth, application3.NewUpdateHealth, application3.NewGetSafeguarding, application3.NewUpdateSafeguarding, application3.NewGetConsent, application3.NewUpdateConsent, application3.NewGetFunding, application3.NewUpdateFunding, application3.NewGetCollectionSetting, application3.NewSetCollectionPassword, application3.NewListRoomAssignments, application3.NewCreateRoomAssignment, application3.NewCloseRoomAssignment, application3.NewGetBillingProfile, application3.NewUpdateBillingProfile, application3.NewGetLeavingRecord, application3.NewListBookingPatterns, application3.NewGetBookingPattern, application3.NewGetCurrentBookingPattern, application3.NewCreateBookingPattern, application3.NewUpdateBookingPattern, wire.Struct(new(httpchild.CoreUseCases), "*"), wire.Struct(new(httpchild.ProfileUseCases), "*"), wire.Struct(new(httpchild.ContactsUseCases), "*"), wire.Struct(new(httpchild.HealthUseCases), "*"), wire.Struct(new(httpchild.SafeguardingUseCases), "*"), wire.Struct(new(httpchild.ConsentUseCases), "*"), wire.Struct(new(httpchild.FundingUseCases), "*"), wire.Struct(new(httpchild.CollectionUseCases), "*"), wire.Struct(new(httpchild.RoomAssignmentUseCases), "*"), wire.Struct(new(httpchild.BillingProfileUseCases), "*"), wire.Struct(new(httpchild.BookingPatternUseCases), "*"), wire.Struct(new(httpchild.ChildrenHandlerConfig), "*"), httpchild.NewHandler,
)

var parentChildMappingsSet = wire.NewSet(postgres7.NewParentChildMappingRepository, wire.Bind(new(domain6.Repository), new(*postgres7.ParentChildMappingRepository)), provideMembershipCheckerAdapter, wire.Bind(new(domain6.MembershipChecker), new(*membershipCheckerAdapter)), provideChildScopeCheckerAdapter, wire.Bind(new(application4.ChildChecker), new(*childScopeCheckerAdapter)), application4.NewCreateMappingUseCase, application4.NewEndMappingUseCase, httpmapping.NewHandler)

var attendanceSet = wire.NewSet(postgres8.NewAttendanceRepository, wire.Bind(new(domain7.Repository), new(*postgres8.AttendanceRepository)), provideChildEnrollmentCheckerAdapter, wire.Bind(new(domain7.ChildEnrollmentChecker), new(*childEnrollmentCheckerAdapter)), provideChildCorrectionCheckerAdapter, wire.Bind(new(domain7.ChildCorrectionChecker), new(*childCorrectionCheckerAdapter)), application5.NewCheckInChild, application5.NewCheckOutChild, application5.NewCorrectAttendance, application5.NewListCorrectionSessions, application5.NewListCorrectionHistory, httpattendance.NewHandler)

var absenceSet = wire.NewSet(postgres9.NewAbsenceRepository, wire.Bind(new(domain2.Repository), new(*postgres9.AbsenceRepository)), provideAbsenceMarkerCheckerAdapter, wire.Bind(new(domain7.AbsenceMarkerChecker), new(*absenceMarkerCheckerAdapter)), provideMarkAbsent,
	provideClearMarker, httpabsence.NewHandler,
)

var fundingSet = wire.NewSet(postgres10.NewRepository, wire.Bind(new(domain3.Repository), new(*postgres10.Repository)), application6.NewGetProfile, provideUpsertProfile, application6.NewListOverview, httpfunding.NewHandler)

var billingSet = wire.NewSet(postgres11.NewRepository, wire.Bind(new(domain8.BillingRepository), new(*postgres11.Repository)), provideSiteProfileLookupAdapter, wire.Bind(new(application7.SiteProfileLookup), new(*siteProfileLookupAdapter)), provideParentContactLookupAdapter, wire.Bind(new(application7.ParentContactLookup), new(*parentContactLookupAdapter)), provideSiteRateUpdateAdapter, wire.Bind(new(domain8.SiteRateRepository), new(*siteRateUpdateAdapter)), provideTermDateLookupAdapter, wire.Bind(new(domain8.TermDateLookup), new(*termDateLookupAdapter)), provideAdHocBookingLookupAdapter, wire.Bind(new(domain8.AdHocBookingLookup), new(*adHocBookingLookupAdapter)), application7.NewPreflightDraftInvoices, application7.NewComputeInvoicePrefill, application7.NewCreateDraftInvoice, application7.NewCreateAndIssueInvoiceFromForm, application7.NewGenerateDraftInvoices, application7.NewListInvoices, application7.NewGetInvoice, application7.NewIssueInvoice, application7.NewBulkIssueInvoices, application7.NewOverrideAttendanceBlockUseCase, application7.NewListParentInvoices, application7.NewGetParentInvoice, application7.NewUpdateSiteRateUseCase, wire.Struct(new(httpbilling.DraftUseCases), "*"), wire.Struct(new(httpbilling.LifecycleUseCases), "*"), wire.Struct(new(httpbilling.ParentInvoiceUseCases), "*"), wire.Struct(new(httpbilling.AdminUseCases), "*"), wire.Struct(new(httpbilling.BillingHandlerConfig), "*"), httpbilling.NewHandler)

func provideCreateCheckoutSession(
	repo *postgres15.Repository,
	paymentsTxMgr *txManagerAdapter,
	checkoutProvider domain9.CheckoutProvider,
	cfg config.Config,
	logger *slog.Logger,
	recorder *metrics.Recorder,
) *application9.CreateCheckoutSession {
	stripeConfigured := checkoutProvider != nil
	uc := application9.NewCreateCheckoutSession(repo, paymentsTxMgr, checkoutProvider, cfg.WebBaseURL, stripeConfigured)
	return uc.WithObservability(logger, recorder)
}

func provideHandleStripeWebhook(
	repo *postgres15.Repository,
	webhookVerifier domain9.WebhookVerifier,
	paymentsTxMgr *txManagerAdapter,
	auditWriter *auditSystemWriterAdapter,
	logger *slog.Logger,
	recorder *metrics.Recorder,
) *application9.HandleStripeWebhook {
	if webhookVerifier == nil {
		return nil
	}
	uc := application9.NewHandleStripeWebhook(repo, webhookVerifier, paymentsTxMgr, auditWriter)
	return uc.WithObservability(logger, recorder)
}

var paymentsSet = wire.NewSet(postgres15.NewRepository, provideTxManagerAdapter,
	provideAuditSystemWriterAdapter,
	provideStripeClient, wire.Bind(new(domain9.CheckoutProvider), new(*stripe.Client)), provideWebhookVerifier, wire.Bind(new(domain9.WebhookVerifier), new(*stripe.WebhookVerifier)), provideManagerPaymentRepo,
	provideCreateCheckoutSession,
	provideHandleStripeWebhook, application9.NewGetManagerPaymentStatus, application9.NewListManagerPaymentEvents, providePaymentsHandler,
)

var invitesSet = wire.NewSet(
	provideInviteTokenManager, postgres16.NewRepository, wire.Bind(new(domain10.Repository), new(*postgres16.Repository)), application10.NewTokenGeneratorAdapter, wire.Bind(new(application10.TokenGenerator), new(*application10.TokenGeneratorAdapter)), application10.NewInviteEmailAdapter, wire.Bind(new(application10.EmailSender), new(*application10.InviteEmailAdapter)), application10.NewCreateInviteUseCase, application10.NewListInvitesUseCase, application10.NewResendInviteUseCase, application10.NewRevokeInviteUseCase, application10.NewAcceptInviteUseCase, provideInviteIPLimiter, httpinvite.NewHandler,
)

func provideResetHandler(
	requestReset *application2.RequestResetUseCase,
	setPassword *application2.SetNewPasswordUseCase,
	recorder *metrics.Recorder,
	logger *slog.Logger,
) *httpreset.Handler {
	emailLimiter := ratelimit.NewFixedWindowLimiter(5, 15*time.Minute)
	ipLimiter := ratelimit.NewFixedWindowLimiter(20, 15*time.Minute)
	return httpreset.NewHandler(requestReset, setPassword, emailLimiter, ipLimiter, recorder, logger)
}

func provideOwnerHandler(
	summaries *application11.GetSiteSummariesUseCase,
	listAccess *application11.ListManagerAccessUseCase,
	grant *application11.GrantManagerAccessUseCase,
	deactivate *application11.DeactivateManagerAccessUseCase,
	reactivate *application11.ReactivateManagerAccessUseCase,
	updateBilling *application11.UpdateSiteBillingSetupUseCase,
	recorder *metrics.Recorder,
	logger *slog.Logger,
) *httpowner.Handler {
	return httpowner.NewHandler(summaries, listAccess, grant, deactivate, reactivate, recorder, logger).
		WithUpdateBillingSetup(updateBilling)
}

var ownerSet = wire.NewSet(postgres6.NewRepository, wire.Bind(new(domain11.SummaryRepository), new(*postgres6.OwnerRepository)), wire.Bind(new(domain11.ManagerAccessRepository), new(*postgres6.OwnerRepository)), application11.NewGetSiteSummariesUseCase, application11.NewListManagerAccessUseCase, provideInviteTokenGeneratorAdapter, wire.Bind(new(domain11.InviteTokenGenerator), new(*inviteTokenGeneratorAdapter)), provideEmailSenderAdapter, wire.Bind(new(domain11.ManagerInviteSender), new(*emailSenderAdapter)), application11.NewGrantManagerAccessUseCase, application11.NewDeactivateManagerAccessUseCase, application11.NewReactivateManagerAccessUseCase, application11.NewUpdateSiteBillingSetupUseCase, provideOwnerHandler)

var roomsSet = wire.NewSet(postgres17.NewRepository, wire.Bind(new(domain12.Repository), new(*postgres17.RoomRepository)), application12.NewCreateRoom, application12.NewUpdateRoom, application12.NewListRooms, application12.NewGetRoom, application12.NewArchiveRoom, application12.NewReactivateRoom, httprooms.NewHandler)

var sessionTypesSet = wire.NewSet(application13.NewCreateSessionType, application13.NewUpdateSessionType, application13.NewListSessionTypes, application13.NewGetSessionType, application13.NewArchiveSessionType, application13.NewReactivateSessionType, httpsessiontypes.NewHandler)

var sessionTemplatesSet = wire.NewSet(postgres18.NewRepository, wire.Bind(new(domain13.Repository), new(*postgres18.SessionTemplateRepository)), provideSessionTemplateLookupTemplateAdapter, wire.Bind(new(application14.SessionTypeLookup), new(*sessionTemplateLookupTemplateAdapter)), application14.NewCreateSessionTemplate, application14.NewUpdateSessionTemplate, application14.NewListSessionTemplates, application14.NewGetSessionTemplate, application14.NewArchiveSessionTemplate, application14.NewReactivateSessionTemplate, httpsessiontemplates.NewHandler)

var termSet = wire.NewSet(postgres5.NewTermRepository, postgres5.NewScheduleChangeRepository, wire.Bind(new(domain14.Repository), new(*postgres5.TermRepository)), wire.Bind(new(domain14.ScheduleChangeRepository), new(*postgres5.ScheduleChangeRepository)), provideBookingPatternLookupAdapter, wire.Bind(new(application15.BookingPatternLookup), new(*bookingPatternLookupAdapter)), provideSiteRateProviderAdapter, wire.Bind(new(application15.SiteRateProvider), new(*siteRateProviderAdapter)), application15.NewCreateTermUseCase, application15.NewGetTermUseCase, application15.NewGetCurrentTermForChildUseCase, application15.NewListTermsForChildUseCase, application15.NewListExpiringTermsUseCase, application15.NewRequestScheduleChangeUseCase, application15.NewApproveScheduleChangeUseCase, application15.NewRejectScheduleChangeUseCase, application15.NewTerminateTermUseCase, wire.Struct(new(httpterm.CoreTermUseCases), "*"), wire.Struct(new(httpterm.ScheduleChangeUseCases), "*"), wire.Struct(new(httpterm.TermHandlerConfig), "*"), httpterm.NewHandler)

func provideSiteProfileHandlerSet(
	repo domain15.Repository,
	auditWriter *audit.Writer,
	txMgr *transaction.Manager,
	logger *slog.Logger,
) *http.Handler {
	getUC := application8.NewGetSiteProfileUseCase(repo)
	updateUC := application8.NewUpdateSiteProfileUseCase(repo, auditWriter, txMgr)
	return http.NewHandler(getUC, updateUC, logger)
}

var siteProfileSet = wire.NewSet(postgres14.NewRepository, wire.Bind(new(domain15.Repository), new(*postgres14.SiteProfileRepository)), application8.NewGetSiteProfileUseCase, application8.NewUpdateSiteProfileUseCase, provideSiteProfileHandlerSet)

var termCalendarSet = wire.NewSet(postgres12.NewRepository, wire.Bind(new(domain16.Repository), new(*postgres12.AcademicTermRepository)), application16.NewCreateTerm, application16.NewListTerms, application16.NewUpdateTerm, application16.NewArchiveTerm, httptermcalendar.NewHandler)

var adHocBookingsSet = wire.NewSet(postgres19.NewRepository, wire.Bind(new(domain17.Repository), new(*postgres19.AdHocBookingRepository)), application17.NewCreateAdHocBooking, application17.NewListAdHocBookings, application17.NewCancelAdHocBooking, httpadhocbookings.NewHandler)

var branchClosuresSet = wire.NewSet(postgres13.NewRepository, wire.Bind(new(domain18.Repository), new(*postgres13.Repository)), application18.NewCreateClosureDay, application18.NewListClosureDays, application18.NewDeleteClosureDay, httpclosure.NewHandler, provideClosureDateLookupAdapter, wire.Bind(new(domain8.ClosureDateLookup), new(*closureDateLookupAdapter)))
