// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"github.com/jackc/pgx/v5/pgxpool"
	"log/slog"
	application15 "nursery-management-system/api/internal/modules/absence/application"
	domain2 "nursery-management-system/api/internal/modules/absence/domain"
	postgres7 "nursery-management-system/api/internal/modules/absence/infrastructure/postgres"
	"nursery-management-system/api/internal/modules/absence/interfaces/http"
	application5 "nursery-management-system/api/internal/modules/attendance/application"
	domain7 "nursery-management-system/api/internal/modules/attendance/domain"
	postgres6 "nursery-management-system/api/internal/modules/attendance/infrastructure/postgres"
	"nursery-management-system/api/internal/modules/attendance/interfaces/http"
	"nursery-management-system/api/internal/modules/authentication/application"
	"nursery-management-system/api/internal/modules/authentication/domain"
	"nursery-management-system/api/internal/modules/authentication/infrastructure/postgres"
	"nursery-management-system/api/internal/modules/authentication/infrastructure/tokens"
	"nursery-management-system/api/internal/modules/authentication/interfaces/http"
	application7 "nursery-management-system/api/internal/modules/billing/application"
	domain8 "nursery-management-system/api/internal/modules/billing/domain"
	postgres9 "nursery-management-system/api/internal/modules/billing/infrastructure/postgres"
	"nursery-management-system/api/internal/modules/billing/interfaces/http"
	application3 "nursery-management-system/api/internal/modules/children/application"
	domain5 "nursery-management-system/api/internal/modules/children/domain"
	postgres3 "nursery-management-system/api/internal/modules/children/infrastructure/postgres"
	"nursery-management-system/api/internal/modules/children/interfaces/http"
	application6 "nursery-management-system/api/internal/modules/funding/application"
	domain3 "nursery-management-system/api/internal/modules/funding/domain"
	postgres8 "nursery-management-system/api/internal/modules/funding/infrastructure/postgres"
	"nursery-management-system/api/internal/modules/funding/interfaces/http"
	application9 "nursery-management-system/api/internal/modules/invites/application"
	domain10 "nursery-management-system/api/internal/modules/invites/domain"
	postgres12 "nursery-management-system/api/internal/modules/invites/infrastructure/postgres"
	"nursery-management-system/api/internal/modules/invites/interfaces/http"
	application10 "nursery-management-system/api/internal/modules/owner/application"
	domain11 "nursery-management-system/api/internal/modules/owner/domain"
	postgres10 "nursery-management-system/api/internal/modules/owner/infrastructure/postgres"
	"nursery-management-system/api/internal/modules/owner/interfaces/http"
	application4 "nursery-management-system/api/internal/modules/parentchildmappings/application"
	domain6 "nursery-management-system/api/internal/modules/parentchildmappings/domain"
	postgres5 "nursery-management-system/api/internal/modules/parentchildmappings/infrastructure/postgres"
	"nursery-management-system/api/internal/modules/parentchildmappings/interfaces/http"
	application2 "nursery-management-system/api/internal/modules/passwordreset/application"
	domain4 "nursery-management-system/api/internal/modules/passwordreset/domain"
	postgres2 "nursery-management-system/api/internal/modules/passwordreset/infrastructure/postgres"
	"nursery-management-system/api/internal/modules/passwordreset/interfaces/http"
	application8 "nursery-management-system/api/internal/modules/payments/application"
	domain9 "nursery-management-system/api/internal/modules/payments/domain"
	postgres11 "nursery-management-system/api/internal/modules/payments/infrastructure/postgres"
	"nursery-management-system/api/internal/modules/payments/infrastructure/stripe"
	application11 "nursery-management-system/api/internal/modules/rooms/application"
	domain12 "nursery-management-system/api/internal/modules/rooms/domain"
	postgres13 "nursery-management-system/api/internal/modules/rooms/infrastructure/postgres"
	"nursery-management-system/api/internal/modules/rooms/interfaces/http"
	application13 "nursery-management-system/api/internal/modules/sessiontemplates/application"
	domain13 "nursery-management-system/api/internal/modules/sessiontemplates/domain"
	postgres14 "nursery-management-system/api/internal/modules/sessiontemplates/infrastructure/postgres"
	"nursery-management-system/api/internal/modules/sessiontemplates/interfaces/http"
	application12 "nursery-management-system/api/internal/modules/sessiontypes/application"
	postgres4 "nursery-management-system/api/internal/modules/sessiontypes/infrastructure/postgres"
	"nursery-management-system/api/internal/modules/sessiontypes/interfaces/http"
	application14 "nursery-management-system/api/internal/modules/term/application"
	domain14 "nursery-management-system/api/internal/modules/term/domain"
	postgres15 "nursery-management-system/api/internal/modules/term/infrastructure/postgres"
	"nursery-management-system/api/internal/modules/term/interfaces/http"
	"nursery-management-system/api/internal/platform/audit"
	"nursery-management-system/api/internal/platform/config"
	"nursery-management-system/api/internal/platform/metrics"
	"nursery-management-system/api/internal/platform/ratelimit"
	"nursery-management-system/api/internal/platform/transaction"
	"time"
)

// Injectors from wire.go:

func InitializeApp(cfg config.Config, logger *slog.Logger, pool *pgxpool.Pool) (*gin.Engine, error) {
	registry := provideMetricsRegistry(cfg)
	recorder := provideMetricsRecorder(cfg, registry)
	tokenManager := provideTokenManager(cfg)
	tokenParser := provideTokenParserAdapter(tokenManager)
	repository := postgres.NewRepository(pool)
	loginUseCase := application.NewLoginUseCase(repository, repository, tokenManager)
	refreshUseCase := application.NewRefreshUseCase(repository, repository, tokenManager)
	logoutUseCase := application.NewLogoutUseCase(repository, tokenManager)
	switchMembershipUseCase := application.NewSwitchMembershipUseCase(repository, repository, tokenManager)
	handler := httpauth.NewHandler(loginUseCase, refreshUseCase, logoutUseCase, switchMembershipUseCase, cfg, recorder, logger)
	postgresRepository := postgres2.NewRepository(pool)
	sender := provideEmailSender(cfg)
	emailAdapter := application2.NewEmailAdapter(sender)
	manager := provideResetTokenManager(cfg)
	tokenGeneratorAdapter := application2.NewTokenGeneratorAdapter(manager)
	string2 := provideWebBaseURL(cfg)
	requestResetUseCase := application2.NewRequestResetUseCase(postgresRepository, emailAdapter, tokenGeneratorAdapter, string2, logger)
	setNewPasswordUseCase := application2.NewSetNewPasswordUseCase(postgresRepository, logger)
	httpresetHandler := provideResetHandler(requestResetUseCase, setNewPasswordUseCase, recorder, logger)
	childRepository := postgres3.NewChildRepository(pool)
	listChildren := application3.NewListChildren(childRepository)
	getChild := application3.NewGetChild(childRepository)
	writer := provideAuditWriter()
	transactionManager := provideTxManager(pool)
	sessionTypeRepository := postgres4.NewRepository(pool)
	bootstrapSessionTypeLookupAdapter := provideSessionTypeLookupAdapter(sessionTypeRepository)
	todayFunc := provideTodayFunc()
	createChildWithFullProfile := application3.NewCreateChildWithFullProfile(childRepository, writer, transactionManager, bootstrapSessionTypeLookupAdapter, todayFunc)
	updateChild := application3.NewUpdateChild(childRepository, writer, transactionManager)
	eventDispatcher := provideEventDispatcher(transactionManager)
	markInactive := application3.NewMarkInactive(childRepository, eventDispatcher, writer)
	v := provideClock()
	listAttendance := application3.NewListAttendance(childRepository, v)
	coreUseCases := httpchild.CoreUseCases{
		List:           listChildren,
		Get:            getChild,
		Create:         createChildWithFullProfile,
		Update:         updateChild,
		MarkInactive:   markInactive,
		ListAttendance: listAttendance,
	}
	getProfile := application3.NewGetProfile(childRepository)
	updateProfile := application3.NewUpdateProfile(childRepository, writer, transactionManager)
	profileUseCases := httpchild.ProfileUseCases{
		Get:    getProfile,
		Update: updateProfile,
	}
	getContacts := application3.NewGetContacts(childRepository)
	replaceContacts := application3.NewReplaceContacts(childRepository, writer, transactionManager)
	contactsUseCases := httpchild.ContactsUseCases{
		Get:     getContacts,
		Replace: replaceContacts,
	}
	getHealth := application3.NewGetHealth(childRepository)
	updateHealth := application3.NewUpdateHealth(childRepository, writer, transactionManager)
	healthUseCases := httpchild.HealthUseCases{
		Get:    getHealth,
		Update: updateHealth,
	}
	getSafeguarding := application3.NewGetSafeguarding(childRepository)
	updateSafeguarding := application3.NewUpdateSafeguarding(childRepository, writer, transactionManager)
	safeguardingUseCases := httpchild.SafeguardingUseCases{
		Get:    getSafeguarding,
		Update: updateSafeguarding,
	}
	getConsent := application3.NewGetConsent(childRepository)
	updateConsent := application3.NewUpdateConsent(childRepository, writer, transactionManager)
	consentUseCases := httpchild.ConsentUseCases{
		Get:    getConsent,
		Update: updateConsent,
	}
	getFunding := application3.NewGetFunding(childRepository)
	updateFunding := application3.NewUpdateFunding(childRepository, writer, transactionManager)
	fundingUseCases := httpchild.FundingUseCases{
		Get:    getFunding,
		Update: updateFunding,
	}
	getCollectionSetting := application3.NewGetCollectionSetting(childRepository)
	setCollectionPassword := application3.NewSetCollectionPassword(childRepository, writer, transactionManager)
	collectionUseCases := httpchild.CollectionUseCases{
		GetSetting:  getCollectionSetting,
		SetPassword: setCollectionPassword,
	}
	listRoomAssignments := application3.NewListRoomAssignments(childRepository)
	createRoomAssignment := application3.NewCreateRoomAssignment(childRepository, writer, transactionManager)
	closeRoomAssignment := application3.NewCloseRoomAssignment(childRepository, writer, transactionManager)
	roomAssignmentUseCases := httpchild.RoomAssignmentUseCases{
		List:   listRoomAssignments,
		Create: createRoomAssignment,
		Close:  closeRoomAssignment,
	}
	getBillingProfile := application3.NewGetBillingProfile(childRepository)
	updateBillingProfile := application3.NewUpdateBillingProfile(childRepository, writer, transactionManager)
	billingProfileUseCases := httpchild.BillingProfileUseCases{
		Get:    getBillingProfile,
		Update: updateBillingProfile,
	}
	getLeavingRecord := application3.NewGetLeavingRecord(childRepository)
	listBookingPatterns := application3.NewListBookingPatterns(childRepository)
	getBookingPattern := application3.NewGetBookingPattern(childRepository)
	getCurrentBookingPattern := application3.NewGetCurrentBookingPattern(childRepository, todayFunc)
	createBookingPattern := application3.NewCreateBookingPattern(childRepository, writer, transactionManager, bootstrapSessionTypeLookupAdapter, todayFunc)
	updateBookingPattern := application3.NewUpdateBookingPattern(childRepository, writer, transactionManager, bootstrapSessionTypeLookupAdapter, todayFunc)
	bookingPatternUseCases := httpchild.BookingPatternUseCases{
		List:       listBookingPatterns,
		Get:        getBookingPattern,
		GetCurrent: getCurrentBookingPattern,
		Create:     createBookingPattern,
		Update:     updateBookingPattern,
	}
	childrenHandlerConfig := httpchild.ChildrenHandlerConfig{
		Core:            coreUseCases,
		Profile:         profileUseCases,
		Contacts:        contactsUseCases,
		Health:          healthUseCases,
		Safeguarding:    safeguardingUseCases,
		Consent:         consentUseCases,
		Funding:         fundingUseCases,
		Collection:      collectionUseCases,
		RoomAssignments: roomAssignmentUseCases,
		BillingProfile:  billingProfileUseCases,
		LeavingRecord:   getLeavingRecord,
		BookingPatterns: bookingPatternUseCases,
	}
	httpchildHandler := httpchild.NewHandler(childrenHandlerConfig, logger)
	parentChildMappingRepository := postgres5.NewParentChildMappingRepository(pool)
	bootstrapMembershipCheckerAdapter := provideMembershipCheckerAdapter(parentChildMappingRepository)
	bootstrapChildScopeCheckerAdapter := provideChildScopeCheckerAdapter(childRepository)
	createMappingUseCase := application4.NewCreateMappingUseCase(parentChildMappingRepository, writer, transactionManager, bootstrapMembershipCheckerAdapter, bootstrapChildScopeCheckerAdapter)
	endMappingUseCase := application4.NewEndMappingUseCase(parentChildMappingRepository, writer, transactionManager)
	httpmappingHandler := httpmapping.NewHandler(createMappingUseCase, endMappingUseCase, logger)
	attendanceRepository := postgres6.NewAttendanceRepository(pool)
	bootstrapChildEnrollmentCheckerAdapter := provideChildEnrollmentCheckerAdapter(childRepository)
	absenceRepository := postgres7.NewAbsenceRepository(pool)
	bootstrapAbsenceMarkerCheckerAdapter := provideAbsenceMarkerCheckerAdapter(absenceRepository)
	attendanceClock := provideAttendanceClock()
	checkInChild := application5.NewCheckInChild(attendanceRepository, bootstrapChildEnrollmentCheckerAdapter, bootstrapAbsenceMarkerCheckerAdapter, transactionManager, writer, attendanceClock)
	checkOutChild := application5.NewCheckOutChild(attendanceRepository, transactionManager, writer, attendanceClock)
	bootstrapChildCorrectionCheckerAdapter := provideChildCorrectionCheckerAdapter(childRepository)
	correctAttendance := application5.NewCorrectAttendance(attendanceRepository, bootstrapChildCorrectionCheckerAdapter, transactionManager, writer, attendanceClock)
	listCorrectionSessions := application5.NewListCorrectionSessions(attendanceRepository)
	listCorrectionHistory := application5.NewListCorrectionHistory(attendanceRepository)
	httpattendanceHandler := httpattendance.NewHandler(checkInChild, checkOutChild, correctAttendance, listCorrectionSessions, listCorrectionHistory, logger)
	markAbsent := provideMarkAbsent(absenceRepository, bootstrapChildEnrollmentCheckerAdapter, transactionManager, writer, attendanceClock)
	clearMarker := provideClearMarker(absenceRepository, transactionManager, writer, attendanceClock)
	httpabsenceHandler := httpabsence.NewHandler(markAbsent, clearMarker, logger)
	repository2 := postgres8.NewRepository(pool)
	applicationGetProfile := application6.NewGetProfile(repository2)
	upsertProfile := provideUpsertProfile(repository2, transactionManager, writer)
	listOverview := application6.NewListOverview(repository2)
	httpfundingHandler := httpfunding.NewHandler(applicationGetProfile, upsertProfile, listOverview, logger)
	repository3 := postgres9.NewRepository(pool)
	preflightDraftInvoices := application7.NewPreflightDraftInvoices(repository3)
	generateDraftInvoicesUseCase := application7.NewGenerateDraftInvoices(repository3, transactionManager, writer, logger, recorder)
	draftUseCases := httpbilling.DraftUseCases{
		Preflight:  preflightDraftInvoices,
		Generation: generateDraftInvoicesUseCase,
	}
	listInvoices := application7.NewListInvoices(repository3)
	getInvoice := application7.NewGetInvoice(repository3)
	issueInvoice := application7.NewIssueInvoice(repository3, transactionManager, writer, eventDispatcher)
	bulkIssueInvoices := application7.NewBulkIssueInvoices(repository3, transactionManager, writer)
	overrideAttendanceBlockUseCase := application7.NewOverrideAttendanceBlockUseCase(repository3, writer, transactionManager)
	lifecycleUseCases := httpbilling.LifecycleUseCases{
		ListInvoices:          listInvoices,
		GetInvoice:            getInvoice,
		IssueInvoice:          issueInvoice,
		BulkIssueInvoices:     bulkIssueInvoices,
		OverrideAttendanceBlk: overrideAttendanceBlockUseCase,
	}
	listParentInvoices := application7.NewListParentInvoices(repository3)
	getParentInvoice := application7.NewGetParentInvoice(repository3)
	parentInvoiceUseCases := httpbilling.ParentInvoiceUseCases{
		List: listParentInvoices,
		Get:  getParentInvoice,
	}
	ownerRepository := postgres10.NewRepository(pool)
	bootstrapSiteRateUpdateAdapter := provideSiteRateUpdateAdapter(ownerRepository)
	updateSiteRateUseCase := application7.NewUpdateSiteRateUseCase(bootstrapSiteRateUpdateAdapter, writer, transactionManager)
	adminUseCases := httpbilling.AdminUseCases{
		UpdateSiteRate: updateSiteRateUseCase,
	}
	billingHandlerConfig := httpbilling.BillingHandlerConfig{
		Drafting:  draftUseCases,
		Lifecycle: lifecycleUseCases,
		Parent:    parentInvoiceUseCases,
		Admin:     adminUseCases,
	}
	httpbillingHandler := httpbilling.NewHandler(billingHandlerConfig, logger)
	repository4 := postgres11.NewRepository(pool)
	bootstrapTxManagerAdapter := provideTxManagerAdapter(transactionManager)
	client := provideStripeClient(cfg)
	createCheckoutSession := provideCreateCheckoutSession(repository4, bootstrapTxManagerAdapter, client, cfg, logger, recorder)
	webhookVerifier := provideWebhookVerifier(cfg)
	bootstrapAuditSystemWriterAdapter := provideAuditSystemWriterAdapter(writer)
	handleStripeWebhook := provideHandleStripeWebhook(repository4, webhookVerifier, bootstrapTxManagerAdapter, bootstrapAuditSystemWriterAdapter, logger, recorder)
	managerPaymentRepository := provideManagerPaymentRepo(repository4)
	getManagerPaymentStatus := application8.NewGetManagerPaymentStatus(managerPaymentRepository)
	listManagerPaymentEvents := application8.NewListManagerPaymentEvents(managerPaymentRepository)
	httpaymentHandler := providePaymentsHandler(createCheckoutSession, handleStripeWebhook, getManagerPaymentStatus, listManagerPaymentEvents, recorder, logger)
	repository5 := postgres12.NewRepository(pool, writer)
	tokensManager := provideInviteTokenManager(cfg)
	applicationTokenGeneratorAdapter := application9.NewTokenGeneratorAdapter(tokensManager)
	inviteEmailAdapter := application9.NewInviteEmailAdapter(sender)
	createInviteUseCase := application9.NewCreateInviteUseCase(repository5, applicationTokenGeneratorAdapter, inviteEmailAdapter, string2, logger)
	listInvitesUseCase := application9.NewListInvitesUseCase(repository5)
	resendInviteUseCase := application9.NewResendInviteUseCase(repository5, applicationTokenGeneratorAdapter, inviteEmailAdapter, string2, logger)
	revokeInviteUseCase := application9.NewRevokeInviteUseCase(repository5, logger)
	acceptInviteUseCase := application9.NewAcceptInviteUseCase(repository5, logger)
	fixedWindowLimiter := provideInviteIPLimiter()
	httpinviteHandler := httpinvite.NewHandler(createInviteUseCase, listInvitesUseCase, resendInviteUseCase, revokeInviteUseCase, acceptInviteUseCase, tokensManager, fixedWindowLimiter, logger)
	getSiteSummariesUseCase := application10.NewGetSiteSummariesUseCase(ownerRepository)
	listManagerAccessUseCase := application10.NewListManagerAccessUseCase(ownerRepository)
	bootstrapInviteTokenGeneratorAdapter := provideInviteTokenGeneratorAdapter(tokensManager)
	bootstrapEmailSenderAdapter := provideEmailSenderAdapter(sender, cfg)
	grantManagerAccessUseCase := application10.NewGrantManagerAccessUseCase(ownerRepository, bootstrapInviteTokenGeneratorAdapter, bootstrapEmailSenderAdapter, string2)
	deactivateManagerAccessUseCase := application10.NewDeactivateManagerAccessUseCase(ownerRepository)
	reactivateManagerAccessUseCase := application10.NewReactivateManagerAccessUseCase(ownerRepository)
	updateSiteBillingSetupUseCase := application10.NewUpdateSiteBillingSetupUseCase(ownerRepository, writer, transactionManager)
	httpownerHandler := provideOwnerHandler(getSiteSummariesUseCase, listManagerAccessUseCase, grantManagerAccessUseCase, deactivateManagerAccessUseCase, reactivateManagerAccessUseCase, updateSiteBillingSetupUseCase, recorder, logger)
	roomRepository := postgres13.NewRepository(pool)
	bootstrapSiteExistsCheckerAdapter := provideSiteExistsCheckerAdapter(ownerRepository)
	createRoom := application11.NewCreateRoom(roomRepository, bootstrapSiteExistsCheckerAdapter)
	updateRoom := application11.NewUpdateRoom(roomRepository, bootstrapSiteExistsCheckerAdapter)
	listRooms := application11.NewListRooms(roomRepository)
	getRoom := application11.NewGetRoom(roomRepository)
	archiveRoom := application11.NewArchiveRoom(roomRepository, transactionManager, writer)
	reactivateRoom := application11.NewReactivateRoom(roomRepository, transactionManager, writer)
	httproomsHandler := httprooms.NewHandler(createRoom, updateRoom, listRooms, getRoom, archiveRoom, reactivateRoom, logger)
	createSessionType := application12.NewCreateSessionType(sessionTypeRepository, bootstrapSiteExistsCheckerAdapter, transactionManager, writer)
	updateSessionType := application12.NewUpdateSessionType(sessionTypeRepository, bootstrapSiteExistsCheckerAdapter, transactionManager, writer)
	listSessionTypes := application12.NewListSessionTypes(sessionTypeRepository)
	getSessionType := application12.NewGetSessionType(sessionTypeRepository)
	archiveSessionType := application12.NewArchiveSessionType(sessionTypeRepository, transactionManager, writer)
	reactivateSessionType := application12.NewReactivateSessionType(sessionTypeRepository, transactionManager, writer)
	httpsessiontypesHandler := httpsessiontypes.NewHandler(createSessionType, updateSessionType, listSessionTypes, getSessionType, archiveSessionType, reactivateSessionType, logger)
	sessionTemplateRepository := postgres14.NewRepository(pool)
	bootstrapSessionTemplateLookupTemplateAdapter := provideSessionTemplateLookupTemplateAdapter(bootstrapSessionTypeLookupAdapter)
	createSessionTemplate := application13.NewCreateSessionTemplate(sessionTemplateRepository, bootstrapSiteExistsCheckerAdapter, bootstrapSessionTemplateLookupTemplateAdapter, transactionManager, writer)
	updateSessionTemplate := application13.NewUpdateSessionTemplate(sessionTemplateRepository, bootstrapSiteExistsCheckerAdapter, bootstrapSessionTemplateLookupTemplateAdapter, transactionManager, writer)
	listSessionTemplates := application13.NewListSessionTemplates(sessionTemplateRepository)
	getSessionTemplate := application13.NewGetSessionTemplate(sessionTemplateRepository)
	archiveSessionTemplate := application13.NewArchiveSessionTemplate(sessionTemplateRepository, transactionManager, writer)
	reactivateSessionTemplate := application13.NewReactivateSessionTemplate(sessionTemplateRepository, transactionManager, writer)
	httpsessiontemplatesHandler := httpsessiontemplates.NewHandler(createSessionTemplate, updateSessionTemplate, listSessionTemplates, getSessionTemplate, archiveSessionTemplate, reactivateSessionTemplate, logger)
	termRepository := postgres15.NewTermRepository(pool)
	bootstrapBookingPatternLookupAdapter := provideBookingPatternLookupAdapter(childRepository)
	bootstrapSiteRateProviderAdapter := provideSiteRateProviderAdapter(ownerRepository)
	createTermUseCase := application14.NewCreateTermUseCase(termRepository, transactionManager, writer, bootstrapBookingPatternLookupAdapter, bootstrapSiteRateProviderAdapter)
	getTermUseCase := application14.NewGetTermUseCase(termRepository)
	getCurrentTermForChildUseCase := application14.NewGetCurrentTermForChildUseCase(termRepository)
	listTermsForChildUseCase := application14.NewListTermsForChildUseCase(termRepository)
	listExpiringTermsUseCase := application14.NewListExpiringTermsUseCase(termRepository)
	terminateTermUseCase := application14.NewTerminateTermUseCase(termRepository, transactionManager, writer)
	coreTermUseCases := httpterm.CoreTermUseCases{
		Create:       createTermUseCase,
		Get:          getTermUseCase,
		GetCurrent:   getCurrentTermForChildUseCase,
		List:         listTermsForChildUseCase,
		ListExpiring: listExpiringTermsUseCase,
		Terminate:    terminateTermUseCase,
	}
	scheduleChangeRepository := postgres15.NewScheduleChangeRepository(pool)
	requestScheduleChangeUseCase := application14.NewRequestScheduleChangeUseCase(termRepository, scheduleChangeRepository, transactionManager, writer, bootstrapBookingPatternLookupAdapter)
	approveScheduleChangeUseCase := application14.NewApproveScheduleChangeUseCase(scheduleChangeRepository, writer, transactionManager)
	rejectScheduleChangeUseCase := application14.NewRejectScheduleChangeUseCase(scheduleChangeRepository, writer, transactionManager)
	scheduleChangeUseCases := httpterm.ScheduleChangeUseCases{
		Request: requestScheduleChangeUseCase,
		Approve: approveScheduleChangeUseCase,
		Reject:  rejectScheduleChangeUseCase,
	}
	termHandlerConfig := httpterm.TermHandlerConfig{
		Core:    coreTermUseCases,
		Changes: scheduleChangeUseCases,
	}
	httptermHandler := httpterm.NewHandler(termHandlerConfig, logger)
	bootstrapAppComponents := appComponents{
		Logger:                  logger,
		Config:                  cfg,
		Pool:                    pool,
		Recorder:                recorder,
		Registry:                registry,
		TokenParser:             tokenParser,
		AuthHandler:             handler,
		ResetHandler:            httpresetHandler,
		ChildrenHandler:         httpchildHandler,
		MappingsHandler:         httpmappingHandler,
		AttendanceHandler:       httpattendanceHandler,
		AbsenceHandler:          httpabsenceHandler,
		FundingHandler:          httpfundingHandler,
		BillingHandler:          httpbillingHandler,
		PaymentsHandler:         httpaymentHandler,
		InviteHandler:           httpinviteHandler,
		OwnerHandler:            httpownerHandler,
		RoomsHandler:            httproomsHandler,
		SessionTypesHandler:     httpsessiontypesHandler,
		SessionTemplatesHandler: httpsessiontemplatesHandler,
		TermHandler:             httptermHandler,
	}
	engine := buildGinEngine(bootstrapAppComponents)
	return engine, nil
}

func InitializeTestApp(cfg config.Config, logger *slog.Logger, pool *pgxpool.Pool) (*gin.Engine, error) {
	registry := provideMetricsRegistry(cfg)
	recorder := provideMetricsRecorder(cfg, registry)
	tokenManager := provideTokenManager(cfg)
	tokenParser := provideTokenParserAdapter(tokenManager)
	repository := postgres.NewRepository(pool)
	loginUseCase := application.NewLoginUseCase(repository, repository, tokenManager)
	refreshUseCase := application.NewRefreshUseCase(repository, repository, tokenManager)
	logoutUseCase := application.NewLogoutUseCase(repository, tokenManager)
	switchMembershipUseCase := application.NewSwitchMembershipUseCase(repository, repository, tokenManager)
	handler := httpauth.NewHandler(loginUseCase, refreshUseCase, logoutUseCase, switchMembershipUseCase, cfg, recorder, logger)
	postgresRepository := postgres2.NewRepository(pool)
	sender := provideEmailSender(cfg)
	emailAdapter := application2.NewEmailAdapter(sender)
	manager := provideResetTokenManager(cfg)
	tokenGeneratorAdapter := application2.NewTokenGeneratorAdapter(manager)
	string2 := provideWebBaseURL(cfg)
	requestResetUseCase := application2.NewRequestResetUseCase(postgresRepository, emailAdapter, tokenGeneratorAdapter, string2, logger)
	setNewPasswordUseCase := application2.NewSetNewPasswordUseCase(postgresRepository, logger)
	httpresetHandler := provideResetHandler(requestResetUseCase, setNewPasswordUseCase, recorder, logger)
	childRepository := postgres3.NewChildRepository(pool)
	listChildren := application3.NewListChildren(childRepository)
	getChild := application3.NewGetChild(childRepository)
	writer := provideAuditWriter()
	transactionManager := provideTxManager(pool)
	sessionTypeRepository := postgres4.NewRepository(pool)
	bootstrapSessionTypeLookupAdapter := provideSessionTypeLookupAdapter(sessionTypeRepository)
	todayFunc := provideTodayFunc()
	createChildWithFullProfile := application3.NewCreateChildWithFullProfile(childRepository, writer, transactionManager, bootstrapSessionTypeLookupAdapter, todayFunc)
	updateChild := application3.NewUpdateChild(childRepository, writer, transactionManager)
	eventDispatcher := provideEventDispatcher(transactionManager)
	markInactive := application3.NewMarkInactive(childRepository, eventDispatcher, writer)
	v := provideClock()
	listAttendance := application3.NewListAttendance(childRepository, v)
	coreUseCases := httpchild.CoreUseCases{
		List:           listChildren,
		Get:            getChild,
		Create:         createChildWithFullProfile,
		Update:         updateChild,
		MarkInactive:   markInactive,
		ListAttendance: listAttendance,
	}
	getProfile := application3.NewGetProfile(childRepository)
	updateProfile := application3.NewUpdateProfile(childRepository, writer, transactionManager)
	profileUseCases := httpchild.ProfileUseCases{
		Get:    getProfile,
		Update: updateProfile,
	}
	getContacts := application3.NewGetContacts(childRepository)
	replaceContacts := application3.NewReplaceContacts(childRepository, writer, transactionManager)
	contactsUseCases := httpchild.ContactsUseCases{
		Get:     getContacts,
		Replace: replaceContacts,
	}
	getHealth := application3.NewGetHealth(childRepository)
	updateHealth := application3.NewUpdateHealth(childRepository, writer, transactionManager)
	healthUseCases := httpchild.HealthUseCases{
		Get:    getHealth,
		Update: updateHealth,
	}
	getSafeguarding := application3.NewGetSafeguarding(childRepository)
	updateSafeguarding := application3.NewUpdateSafeguarding(childRepository, writer, transactionManager)
	safeguardingUseCases := httpchild.SafeguardingUseCases{
		Get:    getSafeguarding,
		Update: updateSafeguarding,
	}
	getConsent := application3.NewGetConsent(childRepository)
	updateConsent := application3.NewUpdateConsent(childRepository, writer, transactionManager)
	consentUseCases := httpchild.ConsentUseCases{
		Get:    getConsent,
		Update: updateConsent,
	}
	getFunding := application3.NewGetFunding(childRepository)
	updateFunding := application3.NewUpdateFunding(childRepository, writer, transactionManager)
	fundingUseCases := httpchild.FundingUseCases{
		Get:    getFunding,
		Update: updateFunding,
	}
	getCollectionSetting := application3.NewGetCollectionSetting(childRepository)
	setCollectionPassword := application3.NewSetCollectionPassword(childRepository, writer, transactionManager)
	collectionUseCases := httpchild.CollectionUseCases{
		GetSetting:  getCollectionSetting,
		SetPassword: setCollectionPassword,
	}
	listRoomAssignments := application3.NewListRoomAssignments(childRepository)
	createRoomAssignment := application3.NewCreateRoomAssignment(childRepository, writer, transactionManager)
	closeRoomAssignment := application3.NewCloseRoomAssignment(childRepository, writer, transactionManager)
	roomAssignmentUseCases := httpchild.RoomAssignmentUseCases{
		List:   listRoomAssignments,
		Create: createRoomAssignment,
		Close:  closeRoomAssignment,
	}
	getBillingProfile := application3.NewGetBillingProfile(childRepository)
	updateBillingProfile := application3.NewUpdateBillingProfile(childRepository, writer, transactionManager)
	billingProfileUseCases := httpchild.BillingProfileUseCases{
		Get:    getBillingProfile,
		Update: updateBillingProfile,
	}
	getLeavingRecord := application3.NewGetLeavingRecord(childRepository)
	listBookingPatterns := application3.NewListBookingPatterns(childRepository)
	getBookingPattern := application3.NewGetBookingPattern(childRepository)
	getCurrentBookingPattern := application3.NewGetCurrentBookingPattern(childRepository, todayFunc)
	createBookingPattern := application3.NewCreateBookingPattern(childRepository, writer, transactionManager, bootstrapSessionTypeLookupAdapter, todayFunc)
	updateBookingPattern := application3.NewUpdateBookingPattern(childRepository, writer, transactionManager, bootstrapSessionTypeLookupAdapter, todayFunc)
	bookingPatternUseCases := httpchild.BookingPatternUseCases{
		List:       listBookingPatterns,
		Get:        getBookingPattern,
		GetCurrent: getCurrentBookingPattern,
		Create:     createBookingPattern,
		Update:     updateBookingPattern,
	}
	childrenHandlerConfig := httpchild.ChildrenHandlerConfig{
		Core:            coreUseCases,
		Profile:         profileUseCases,
		Contacts:        contactsUseCases,
		Health:          healthUseCases,
		Safeguarding:    safeguardingUseCases,
		Consent:         consentUseCases,
		Funding:         fundingUseCases,
		Collection:      collectionUseCases,
		RoomAssignments: roomAssignmentUseCases,
		BillingProfile:  billingProfileUseCases,
		LeavingRecord:   getLeavingRecord,
		BookingPatterns: bookingPatternUseCases,
	}
	httpchildHandler := httpchild.NewHandler(childrenHandlerConfig, logger)
	parentChildMappingRepository := postgres5.NewParentChildMappingRepository(pool)
	bootstrapMembershipCheckerAdapter := provideMembershipCheckerAdapter(parentChildMappingRepository)
	bootstrapChildScopeCheckerAdapter := provideChildScopeCheckerAdapter(childRepository)
	createMappingUseCase := application4.NewCreateMappingUseCase(parentChildMappingRepository, writer, transactionManager, bootstrapMembershipCheckerAdapter, bootstrapChildScopeCheckerAdapter)
	endMappingUseCase := application4.NewEndMappingUseCase(parentChildMappingRepository, writer, transactionManager)
	httpmappingHandler := httpmapping.NewHandler(createMappingUseCase, endMappingUseCase, logger)
	attendanceRepository := postgres6.NewAttendanceRepository(pool)
	bootstrapChildEnrollmentCheckerAdapter := provideChildEnrollmentCheckerAdapter(childRepository)
	absenceRepository := postgres7.NewAbsenceRepository(pool)
	bootstrapAbsenceMarkerCheckerAdapter := provideAbsenceMarkerCheckerAdapter(absenceRepository)
	attendanceClock := provideAttendanceClock()
	checkInChild := application5.NewCheckInChild(attendanceRepository, bootstrapChildEnrollmentCheckerAdapter, bootstrapAbsenceMarkerCheckerAdapter, transactionManager, writer, attendanceClock)
	checkOutChild := application5.NewCheckOutChild(attendanceRepository, transactionManager, writer, attendanceClock)
	bootstrapChildCorrectionCheckerAdapter := provideChildCorrectionCheckerAdapter(childRepository)
	correctAttendance := application5.NewCorrectAttendance(attendanceRepository, bootstrapChildCorrectionCheckerAdapter, transactionManager, writer, attendanceClock)
	listCorrectionSessions := application5.NewListCorrectionSessions(attendanceRepository)
	listCorrectionHistory := application5.NewListCorrectionHistory(attendanceRepository)
	httpattendanceHandler := httpattendance.NewHandler(checkInChild, checkOutChild, correctAttendance, listCorrectionSessions, listCorrectionHistory, logger)
	markAbsent := provideMarkAbsent(absenceRepository, bootstrapChildEnrollmentCheckerAdapter, transactionManager, writer, attendanceClock)
	clearMarker := provideClearMarker(absenceRepository, transactionManager, writer, attendanceClock)
	httpabsenceHandler := httpabsence.NewHandler(markAbsent, clearMarker, logger)
	repository2 := postgres8.NewRepository(pool)
	applicationGetProfile := application6.NewGetProfile(repository2)
	upsertProfile := provideUpsertProfile(repository2, transactionManager, writer)
	listOverview := application6.NewListOverview(repository2)
	httpfundingHandler := httpfunding.NewHandler(applicationGetProfile, upsertProfile, listOverview, logger)
	repository3 := postgres9.NewRepository(pool)
	preflightDraftInvoices := application7.NewPreflightDraftInvoices(repository3)
	generateDraftInvoicesUseCase := application7.NewGenerateDraftInvoices(repository3, transactionManager, writer, logger, recorder)
	draftUseCases := httpbilling.DraftUseCases{
		Preflight:  preflightDraftInvoices,
		Generation: generateDraftInvoicesUseCase,
	}
	listInvoices := application7.NewListInvoices(repository3)
	getInvoice := application7.NewGetInvoice(repository3)
	issueInvoice := application7.NewIssueInvoice(repository3, transactionManager, writer, eventDispatcher)
	bulkIssueInvoices := application7.NewBulkIssueInvoices(repository3, transactionManager, writer)
	overrideAttendanceBlockUseCase := application7.NewOverrideAttendanceBlockUseCase(repository3, writer, transactionManager)
	lifecycleUseCases := httpbilling.LifecycleUseCases{
		ListInvoices:          listInvoices,
		GetInvoice:            getInvoice,
		IssueInvoice:          issueInvoice,
		BulkIssueInvoices:     bulkIssueInvoices,
		OverrideAttendanceBlk: overrideAttendanceBlockUseCase,
	}
	listParentInvoices := application7.NewListParentInvoices(repository3)
	getParentInvoice := application7.NewGetParentInvoice(repository3)
	parentInvoiceUseCases := httpbilling.ParentInvoiceUseCases{
		List: listParentInvoices,
		Get:  getParentInvoice,
	}
	ownerRepository := postgres10.NewRepository(pool)
	bootstrapSiteRateUpdateAdapter := provideSiteRateUpdateAdapter(ownerRepository)
	updateSiteRateUseCase := application7.NewUpdateSiteRateUseCase(bootstrapSiteRateUpdateAdapter, writer, transactionManager)
	adminUseCases := httpbilling.AdminUseCases{
		UpdateSiteRate: updateSiteRateUseCase,
	}
	billingHandlerConfig := httpbilling.BillingHandlerConfig{
		Drafting:  draftUseCases,
		Lifecycle: lifecycleUseCases,
		Parent:    parentInvoiceUseCases,
		Admin:     adminUseCases,
	}
	httpbillingHandler := httpbilling.NewHandler(billingHandlerConfig, logger)
	repository4 := postgres11.NewRepository(pool)
	bootstrapTxManagerAdapter := provideTxManagerAdapter(transactionManager)
	client := provideStripeClient(cfg)
	createCheckoutSession := provideCreateCheckoutSession(repository4, bootstrapTxManagerAdapter, client, cfg, logger, recorder)
	webhookVerifier := provideWebhookVerifier(cfg)
	bootstrapAuditSystemWriterAdapter := provideAuditSystemWriterAdapter(writer)
	handleStripeWebhook := provideHandleStripeWebhook(repository4, webhookVerifier, bootstrapTxManagerAdapter, bootstrapAuditSystemWriterAdapter, logger, recorder)
	managerPaymentRepository := provideManagerPaymentRepo(repository4)
	getManagerPaymentStatus := application8.NewGetManagerPaymentStatus(managerPaymentRepository)
	listManagerPaymentEvents := application8.NewListManagerPaymentEvents(managerPaymentRepository)
	httpaymentHandler := providePaymentsHandler(createCheckoutSession, handleStripeWebhook, getManagerPaymentStatus, listManagerPaymentEvents, recorder, logger)
	repository5 := postgres12.NewRepository(pool, writer)
	tokensManager := provideInviteTokenManager(cfg)
	applicationTokenGeneratorAdapter := application9.NewTokenGeneratorAdapter(tokensManager)
	inviteEmailAdapter := application9.NewInviteEmailAdapter(sender)
	createInviteUseCase := application9.NewCreateInviteUseCase(repository5, applicationTokenGeneratorAdapter, inviteEmailAdapter, string2, logger)
	listInvitesUseCase := application9.NewListInvitesUseCase(repository5)
	resendInviteUseCase := application9.NewResendInviteUseCase(repository5, applicationTokenGeneratorAdapter, inviteEmailAdapter, string2, logger)
	revokeInviteUseCase := application9.NewRevokeInviteUseCase(repository5, logger)
	acceptInviteUseCase := application9.NewAcceptInviteUseCase(repository5, logger)
	fixedWindowLimiter := provideInviteIPLimiter()
	httpinviteHandler := httpinvite.NewHandler(createInviteUseCase, listInvitesUseCase, resendInviteUseCase, revokeInviteUseCase, acceptInviteUseCase, tokensManager, fixedWindowLimiter, logger)
	getSiteSummariesUseCase := application10.NewGetSiteSummariesUseCase(ownerRepository)
	listManagerAccessUseCase := application10.NewListManagerAccessUseCase(ownerRepository)
	bootstrapInviteTokenGeneratorAdapter := provideInviteTokenGeneratorAdapter(tokensManager)
	bootstrapEmailSenderAdapter := provideEmailSenderAdapter(sender, cfg)
	grantManagerAccessUseCase := application10.NewGrantManagerAccessUseCase(ownerRepository, bootstrapInviteTokenGeneratorAdapter, bootstrapEmailSenderAdapter, string2)
	deactivateManagerAccessUseCase := application10.NewDeactivateManagerAccessUseCase(ownerRepository)
	reactivateManagerAccessUseCase := application10.NewReactivateManagerAccessUseCase(ownerRepository)
	updateSiteBillingSetupUseCase := application10.NewUpdateSiteBillingSetupUseCase(ownerRepository, writer, transactionManager)
	httpownerHandler := provideOwnerHandler(getSiteSummariesUseCase, listManagerAccessUseCase, grantManagerAccessUseCase, deactivateManagerAccessUseCase, reactivateManagerAccessUseCase, updateSiteBillingSetupUseCase, recorder, logger)
	roomRepository := postgres13.NewRepository(pool)
	bootstrapSiteExistsCheckerAdapter := provideSiteExistsCheckerAdapter(ownerRepository)
	createRoom := application11.NewCreateRoom(roomRepository, bootstrapSiteExistsCheckerAdapter)
	updateRoom := application11.NewUpdateRoom(roomRepository, bootstrapSiteExistsCheckerAdapter)
	listRooms := application11.NewListRooms(roomRepository)
	getRoom := application11.NewGetRoom(roomRepository)
	archiveRoom := application11.NewArchiveRoom(roomRepository, transactionManager, writer)
	reactivateRoom := application11.NewReactivateRoom(roomRepository, transactionManager, writer)
	httproomsHandler := httprooms.NewHandler(createRoom, updateRoom, listRooms, getRoom, archiveRoom, reactivateRoom, logger)
	createSessionType := application12.NewCreateSessionType(sessionTypeRepository, bootstrapSiteExistsCheckerAdapter, transactionManager, writer)
	updateSessionType := application12.NewUpdateSessionType(sessionTypeRepository, bootstrapSiteExistsCheckerAdapter, transactionManager, writer)
	listSessionTypes := application12.NewListSessionTypes(sessionTypeRepository)
	getSessionType := application12.NewGetSessionType(sessionTypeRepository)
	archiveSessionType := application12.NewArchiveSessionType(sessionTypeRepository, transactionManager, writer)
	reactivateSessionType := application12.NewReactivateSessionType(sessionTypeRepository, transactionManager, writer)
	httpsessiontypesHandler := httpsessiontypes.NewHandler(createSessionType, updateSessionType, listSessionTypes, getSessionType, archiveSessionType, reactivateSessionType, logger)
	sessionTemplateRepository := postgres14.NewRepository(pool)
	bootstrapSessionTemplateLookupTemplateAdapter := provideSessionTemplateLookupTemplateAdapter(bootstrapSessionTypeLookupAdapter)
	createSessionTemplate := application13.NewCreateSessionTemplate(sessionTemplateRepository, bootstrapSiteExistsCheckerAdapter, bootstrapSessionTemplateLookupTemplateAdapter, transactionManager, writer)
	updateSessionTemplate := application13.NewUpdateSessionTemplate(sessionTemplateRepository, bootstrapSiteExistsCheckerAdapter, bootstrapSessionTemplateLookupTemplateAdapter, transactionManager, writer)
	listSessionTemplates := application13.NewListSessionTemplates(sessionTemplateRepository)
	getSessionTemplate := application13.NewGetSessionTemplate(sessionTemplateRepository)
	archiveSessionTemplate := application13.NewArchiveSessionTemplate(sessionTemplateRepository, transactionManager, writer)
	reactivateSessionTemplate := application13.NewReactivateSessionTemplate(sessionTemplateRepository, transactionManager, writer)
	httpsessiontemplatesHandler := httpsessiontemplates.NewHandler(createSessionTemplate, updateSessionTemplate, listSessionTemplates, getSessionTemplate, archiveSessionTemplate, reactivateSessionTemplate, logger)
	termRepository := postgres15.NewTermRepository(pool)
	bootstrapBookingPatternLookupAdapter := provideBookingPatternLookupAdapter(childRepository)
	bootstrapSiteRateProviderAdapter := provideSiteRateProviderAdapter(ownerRepository)
	createTermUseCase := application14.NewCreateTermUseCase(termRepository, transactionManager, writer, bootstrapBookingPatternLookupAdapter, bootstrapSiteRateProviderAdapter)
	getTermUseCase := application14.NewGetTermUseCase(termRepository)
	getCurrentTermForChildUseCase := application14.NewGetCurrentTermForChildUseCase(termRepository)
	listTermsForChildUseCase := application14.NewListTermsForChildUseCase(termRepository)
	listExpiringTermsUseCase := application14.NewListExpiringTermsUseCase(termRepository)
	terminateTermUseCase := application14.NewTerminateTermUseCase(termRepository, transactionManager, writer)
	coreTermUseCases := httpterm.CoreTermUseCases{
		Create:       createTermUseCase,
		Get:          getTermUseCase,
		GetCurrent:   getCurrentTermForChildUseCase,
		List:         listTermsForChildUseCase,
		ListExpiring: listExpiringTermsUseCase,
		Terminate:    terminateTermUseCase,
	}
	scheduleChangeRepository := postgres15.NewScheduleChangeRepository(pool)
	requestScheduleChangeUseCase := application14.NewRequestScheduleChangeUseCase(termRepository, scheduleChangeRepository, transactionManager, writer, bootstrapBookingPatternLookupAdapter)
	approveScheduleChangeUseCase := application14.NewApproveScheduleChangeUseCase(scheduleChangeRepository, writer, transactionManager)
	rejectScheduleChangeUseCase := application14.NewRejectScheduleChangeUseCase(scheduleChangeRepository, writer, transactionManager)
	scheduleChangeUseCases := httpterm.ScheduleChangeUseCases{
		Request: requestScheduleChangeUseCase,
		Approve: approveScheduleChangeUseCase,
		Reject:  rejectScheduleChangeUseCase,
	}
	termHandlerConfig := httpterm.TermHandlerConfig{
		Core:    coreTermUseCases,
		Changes: scheduleChangeUseCases,
	}
	httptermHandler := httpterm.NewHandler(termHandlerConfig, logger)
	bootstrapAppComponents := appComponents{
		Logger:                  logger,
		Config:                  cfg,
		Pool:                    pool,
		Recorder:                recorder,
		Registry:                registry,
		TokenParser:             tokenParser,
		AuthHandler:             handler,
		ResetHandler:            httpresetHandler,
		ChildrenHandler:         httpchildHandler,
		MappingsHandler:         httpmappingHandler,
		AttendanceHandler:       httpattendanceHandler,
		AbsenceHandler:          httpabsenceHandler,
		FundingHandler:          httpfundingHandler,
		BillingHandler:          httpbillingHandler,
		PaymentsHandler:         httpaymentHandler,
		InviteHandler:           httpinviteHandler,
		OwnerHandler:            httpownerHandler,
		RoomsHandler:            httproomsHandler,
		SessionTypesHandler:     httpsessiontypesHandler,
		SessionTemplatesHandler: httpsessiontemplatesHandler,
		TermHandler:             httptermHandler,
	}
	engine := buildGinEngine(bootstrapAppComponents)
	return engine, nil
}

// wire.go:

var authSet = wire.NewSet(
	provideTokenManager, postgres.NewRepository, wire.Bind(new(domain.UserRepository), new(*postgres.Repository)), wire.Bind(new(domain.SessionRepository), new(*postgres.Repository)), wire.Bind(new(application.TokenGenerator), new(*tokens.TokenManager)), application.NewLoginUseCase, application.NewRefreshUseCase, application.NewLogoutUseCase, application.NewSwitchMembershipUseCase, httpauth.NewHandler,
)

func provideMarkAbsent(
	repo domain2.Repository,
	childChecker domain2.ChildEnrollmentChecker,
	txMgr *transaction.Manager, audit2 *audit.Writer,
	clock *application5.AttendanceClock,
) *application15.MarkAbsent {
	return application15.NewMarkAbsent(repo, childChecker, txMgr, audit2, clock)
}

func provideClearMarker(
	repo domain2.Repository,
	txMgr *transaction.Manager, audit2 *audit.Writer,
	clock *application5.AttendanceClock,
) *application15.ClearMarker {
	return application15.NewClearMarker(repo, txMgr, audit2, clock)
}

func provideUpsertProfile(
	repo domain3.Repository,
	txMgr *transaction.Manager, audit2 *audit.Writer,
) *application6.UpsertProfile {
	return application6.NewUpsertProfile(repo, txMgr, audit2)
}

var passwordResetSet = wire.NewSet(
	provideResetTokenManager, postgres2.NewRepository, wire.Bind(new(domain4.Repository), new(*postgres2.Repository)), application2.NewTokenGeneratorAdapter, wire.Bind(new(application2.TokenGenerator), new(*application2.TokenGeneratorAdapter)), application2.NewEmailAdapter, wire.Bind(new(domain4.EmailSender), new(*application2.EmailAdapter)), application2.NewRequestResetUseCase, application2.NewSetNewPasswordUseCase, provideResetHandler,
)

var childrenSet = wire.NewSet(postgres3.NewChildRepository, wire.Bind(new(domain5.Repository), new(*postgres3.ChildRepository)), provideSessionTypeLookupAdapter, wire.Bind(new(application3.SessionTypeLookup), new(*sessionTypeLookupAdapter)), provideClock,
	provideTodayFunc, application3.NewListChildren, application3.NewGetChild, application3.NewCreateChildWithFullProfile, application3.NewUpdateChild, application3.NewMarkInactive, application3.NewListAttendance, application3.NewGetProfile, application3.NewUpdateProfile, application3.NewGetContacts, application3.NewReplaceContacts, application3.NewGetHealth, application3.NewUpdateHealth, application3.NewGetSafeguarding, application3.NewUpdateSafeguarding, application3.NewGetConsent, application3.NewUpdateConsent, application3.NewGetFunding, application3.NewUpdateFunding, application3.NewGetCollectionSetting, application3.NewSetCollectionPassword, application3.NewListRoomAssignments, application3.NewCreateRoomAssignment, application3.NewCloseRoomAssignment, application3.NewGetBillingProfile, application3.NewUpdateBillingProfile, application3.NewGetLeavingRecord, application3.NewListBookingPatterns, application3.NewGetBookingPattern, application3.NewGetCurrentBookingPattern, application3.NewCreateBookingPattern, application3.NewUpdateBookingPattern, wire.Struct(new(httpchild.CoreUseCases), "*"), wire.Struct(new(httpchild.ProfileUseCases), "*"), wire.Struct(new(httpchild.ContactsUseCases), "*"), wire.Struct(new(httpchild.HealthUseCases), "*"), wire.Struct(new(httpchild.SafeguardingUseCases), "*"), wire.Struct(new(httpchild.ConsentUseCases), "*"), wire.Struct(new(httpchild.FundingUseCases), "*"), wire.Struct(new(httpchild.CollectionUseCases), "*"), wire.Struct(new(httpchild.RoomAssignmentUseCases), "*"), wire.Struct(new(httpchild.BillingProfileUseCases), "*"), wire.Struct(new(httpchild.BookingPatternUseCases), "*"), wire.Struct(new(httpchild.ChildrenHandlerConfig), "*"), httpchild.NewHandler,
)

var parentChildMappingsSet = wire.NewSet(postgres5.NewParentChildMappingRepository, wire.Bind(new(domain6.Repository), new(*postgres5.ParentChildMappingRepository)), provideMembershipCheckerAdapter, wire.Bind(new(domain6.MembershipChecker), new(*membershipCheckerAdapter)), provideChildScopeCheckerAdapter, wire.Bind(new(application4.ChildChecker), new(*childScopeCheckerAdapter)), application4.NewCreateMappingUseCase, application4.NewEndMappingUseCase, httpmapping.NewHandler)

var attendanceSet = wire.NewSet(postgres6.NewAttendanceRepository, wire.Bind(new(domain7.Repository), new(*postgres6.AttendanceRepository)), provideChildEnrollmentCheckerAdapter, wire.Bind(new(domain7.ChildEnrollmentChecker), new(*childEnrollmentCheckerAdapter)), provideChildCorrectionCheckerAdapter, wire.Bind(new(domain7.ChildCorrectionChecker), new(*childCorrectionCheckerAdapter)), application5.NewCheckInChild, application5.NewCheckOutChild, application5.NewCorrectAttendance, application5.NewListCorrectionSessions, application5.NewListCorrectionHistory, httpattendance.NewHandler)

var absenceSet = wire.NewSet(postgres7.NewAbsenceRepository, wire.Bind(new(domain2.Repository), new(*postgres7.AbsenceRepository)), provideAbsenceMarkerCheckerAdapter, wire.Bind(new(domain7.AbsenceMarkerChecker), new(*absenceMarkerCheckerAdapter)), provideMarkAbsent,
	provideClearMarker, httpabsence.NewHandler,
)

var fundingSet = wire.NewSet(postgres8.NewRepository, wire.Bind(new(domain3.Repository), new(*postgres8.Repository)), application6.NewGetProfile, provideUpsertProfile, application6.NewListOverview, httpfunding.NewHandler)

var billingSet = wire.NewSet(postgres9.NewRepository, wire.Bind(new(domain8.BillingRepository), new(*postgres9.Repository)), provideSiteRateUpdateAdapter, wire.Bind(new(domain8.SiteRateRepository), new(*siteRateUpdateAdapter)), application7.NewPreflightDraftInvoices, application7.NewGenerateDraftInvoices, application7.NewListInvoices, application7.NewGetInvoice, application7.NewIssueInvoice, application7.NewBulkIssueInvoices, application7.NewOverrideAttendanceBlockUseCase, application7.NewListParentInvoices, application7.NewGetParentInvoice, application7.NewUpdateSiteRateUseCase, wire.Struct(new(httpbilling.DraftUseCases), "*"), wire.Struct(new(httpbilling.LifecycleUseCases), "*"), wire.Struct(new(httpbilling.ParentInvoiceUseCases), "*"), wire.Struct(new(httpbilling.AdminUseCases), "*"), wire.Struct(new(httpbilling.BillingHandlerConfig), "*"), httpbilling.NewHandler)

func provideCreateCheckoutSession(
	repo *postgres11.Repository,
	paymentsTxMgr *txManagerAdapter,
	checkoutProvider domain9.CheckoutProvider,
	cfg config.Config,
	logger *slog.Logger,
	recorder *metrics.Recorder,
) *application8.CreateCheckoutSession {
	stripeConfigured := checkoutProvider != nil
	uc := application8.NewCreateCheckoutSession(repo, paymentsTxMgr, checkoutProvider, cfg.WebBaseURL, stripeConfigured)
	return uc.WithObservability(logger, recorder)
}

func provideHandleStripeWebhook(
	repo *postgres11.Repository,
	webhookVerifier domain9.WebhookVerifier,
	paymentsTxMgr *txManagerAdapter,
	auditWriter *auditSystemWriterAdapter,
	logger *slog.Logger,
	recorder *metrics.Recorder,
) *application8.HandleStripeWebhook {
	if webhookVerifier == nil {
		return nil
	}
	uc := application8.NewHandleStripeWebhook(repo, webhookVerifier, paymentsTxMgr, auditWriter)
	return uc.WithObservability(logger, recorder)
}

var paymentsSet = wire.NewSet(postgres11.NewRepository, provideTxManagerAdapter,
	provideAuditSystemWriterAdapter,
	provideStripeClient, wire.Bind(new(domain9.CheckoutProvider), new(*stripe.Client)), provideWebhookVerifier, wire.Bind(new(domain9.WebhookVerifier), new(*stripe.WebhookVerifier)), provideManagerPaymentRepo,
	provideCreateCheckoutSession,
	provideHandleStripeWebhook, application8.NewGetManagerPaymentStatus, application8.NewListManagerPaymentEvents, providePaymentsHandler,
)

var invitesSet = wire.NewSet(
	provideInviteTokenManager, postgres12.NewRepository, wire.Bind(new(domain10.Repository), new(*postgres12.Repository)), application9.NewTokenGeneratorAdapter, wire.Bind(new(application9.TokenGenerator), new(*application9.TokenGeneratorAdapter)), application9.NewInviteEmailAdapter, wire.Bind(new(application9.EmailSender), new(*application9.InviteEmailAdapter)), application9.NewCreateInviteUseCase, application9.NewListInvitesUseCase, application9.NewResendInviteUseCase, application9.NewRevokeInviteUseCase, application9.NewAcceptInviteUseCase, provideInviteIPLimiter, httpinvite.NewHandler,
)

func provideResetHandler(
	requestReset *application2.RequestResetUseCase,
	setPassword *application2.SetNewPasswordUseCase,
	recorder *metrics.Recorder,
	logger *slog.Logger,
) *httpreset.Handler {
	emailLimiter := ratelimit.NewFixedWindowLimiter(5, 15*time.Minute)
	ipLimiter := ratelimit.NewFixedWindowLimiter(20, 15*time.Minute)
	return httpreset.NewHandler(requestReset, setPassword, emailLimiter, ipLimiter, recorder, logger)
}

func provideOwnerHandler(
	summaries *application10.GetSiteSummariesUseCase,
	listAccess *application10.ListManagerAccessUseCase,
	grant *application10.GrantManagerAccessUseCase,
	deactivate *application10.DeactivateManagerAccessUseCase,
	reactivate *application10.ReactivateManagerAccessUseCase,
	updateBilling *application10.UpdateSiteBillingSetupUseCase,
	recorder *metrics.Recorder,
	logger *slog.Logger,
) *httpowner.Handler {
	return httpowner.NewHandler(summaries, listAccess, grant, deactivate, reactivate, recorder, logger).
		WithUpdateBillingSetup(updateBilling)
}

var ownerSet = wire.NewSet(postgres10.NewRepository, wire.Bind(new(domain11.SummaryRepository), new(*postgres10.OwnerRepository)), wire.Bind(new(domain11.ManagerAccessRepository), new(*postgres10.OwnerRepository)), application10.NewGetSiteSummariesUseCase, application10.NewListManagerAccessUseCase, provideInviteTokenGeneratorAdapter, wire.Bind(new(domain11.InviteTokenGenerator), new(*inviteTokenGeneratorAdapter)), provideEmailSenderAdapter, wire.Bind(new(domain11.ManagerInviteSender), new(*emailSenderAdapter)), application10.NewGrantManagerAccessUseCase, application10.NewDeactivateManagerAccessUseCase, application10.NewReactivateManagerAccessUseCase, application10.NewUpdateSiteBillingSetupUseCase, provideOwnerHandler)

var roomsSet = wire.NewSet(postgres13.NewRepository, wire.Bind(new(domain12.Repository), new(*postgres13.RoomRepository)), application11.NewCreateRoom, application11.NewUpdateRoom, application11.NewListRooms, application11.NewGetRoom, application11.NewArchiveRoom, application11.NewReactivateRoom, httprooms.NewHandler)

var sessionTypesSet = wire.NewSet(application12.NewCreateSessionType, application12.NewUpdateSessionType, application12.NewListSessionTypes, application12.NewGetSessionType, application12.NewArchiveSessionType, application12.NewReactivateSessionType, httpsessiontypes.NewHandler)

var sessionTemplatesSet = wire.NewSet(postgres14.NewRepository, wire.Bind(new(domain13.Repository), new(*postgres14.SessionTemplateRepository)), provideSessionTemplateLookupTemplateAdapter, wire.Bind(new(application13.SessionTypeLookup), new(*sessionTemplateLookupTemplateAdapter)), application13.NewCreateSessionTemplate, application13.NewUpdateSessionTemplate, application13.NewListSessionTemplates, application13.NewGetSessionTemplate, application13.NewArchiveSessionTemplate, application13.NewReactivateSessionTemplate, httpsessiontemplates.NewHandler)

var termSet = wire.NewSet(postgres15.NewTermRepository, postgres15.NewScheduleChangeRepository, wire.Bind(new(domain14.Repository), new(*postgres15.TermRepository)), wire.Bind(new(domain14.ScheduleChangeRepository), new(*postgres15.ScheduleChangeRepository)), provideBookingPatternLookupAdapter, wire.Bind(new(application14.BookingPatternLookup), new(*bookingPatternLookupAdapter)), provideSiteRateProviderAdapter, wire.Bind(new(application14.SiteRateProvider), new(*siteRateProviderAdapter)), application14.NewCreateTermUseCase, application14.NewGetTermUseCase, application14.NewGetCurrentTermForChildUseCase, application14.NewListTermsForChildUseCase, application14.NewListExpiringTermsUseCase, application14.NewRequestScheduleChangeUseCase, application14.NewApproveScheduleChangeUseCase, application14.NewRejectScheduleChangeUseCase, application14.NewTerminateTermUseCase, wire.Struct(new(httpterm.CoreTermUseCases), "*"), wire.Struct(new(httpterm.ScheduleChangeUseCases), "*"), wire.Struct(new(httpterm.TermHandlerConfig), "*"), httpterm.NewHandler)
